// Code generated by internal/appwirets; DO NOT EDIT. Run make generate.

export interface AgentMessageDeltaParams {
  threadId: string;
  ref?: string;
  turnId: string;
  itemId: string;
  delta: string;
}

export interface AgentMessageResetParams {
  threadId: string;
  ref?: string;
  turnId: string;
  itemId: string;
}

export interface AuthApiKeySetParams {
  provider: string;
  value: string;
}

export interface AuthDevicePollParams {
  provider: string;
  flowId: string;
}

export interface AuthDevicePollResponse {
  state: string;
  status?: AuthStatusResponse;
}

export interface AuthDeviceStartParams {
  provider: string;
}

export interface AuthDeviceStartResponse {
  provider: string;
  flowId: string;
  userCode: string;
  verificationUrl: string;
  intervalSeconds: number;
  fallback?: boolean;
}

export interface AuthListResponse {
  providers: AuthStatusResponse[];
}

export interface AuthLoginCompleteParams {
  provider: string;
  flowId: string;
  redirectUrl: string;
}

export interface AuthLoginCompleteResponse {
  status: AuthStatusResponse;
}

export interface AuthLoginStartParams {
  provider: string;
}

export interface AuthLoginStartResponse {
  provider: string;
  flowId: string;
  url: string;
}

export interface AuthLogoutParams {
  provider: string;
}

export interface AuthLogoutResponse {
  removed: boolean;
  status: AuthStatusResponse;
}

export interface AuthStatusParams {
  provider: string;
}

export interface AuthStatusResponse {
  provider: string;
  supported: boolean;
  signedIn: boolean;
  activeSource: string;
  authModes?: string[];
  hasStoredOAuth: boolean;
  hasStoredFile?: boolean;
  envVar?: string;
  email?: string;
  storedEmail?: string;
  accountId?: string;
  workspaceId?: string;
  needsRefresh?: boolean;
  needsLogin?: boolean;
  error?: string;
}

export interface Capabilities {
  experimentalApi: boolean;
  optOutNotificationMethods?: string[];
}

export interface ClientInfo {
  name: string;
  version: string;
}

export interface CommandDescriptor {
  name: string;
  pluginName: string;
  description?: string;
  argumentHint?: string;
}

export interface CommandListResponse {
  commands: CommandDescriptor[];
}

export interface DiagnosticCause {
  kind: string;
  provider?: string;
  model?: string;
  status?: number;
}

export interface EmptyParams {
}

export interface EmptyResponse {
}

export interface FeatureSet {
  threadList: boolean;
  threadTurnsList: boolean;
  turnStart: boolean;
  turnSteer: boolean;
  threadClear: boolean;
  threadShutdown: boolean;
  forkFromTurn: boolean;
  tasks: boolean;
  transcriptList: boolean;
  modelList: boolean;
  directoryComplete: boolean;
  auth: boolean;
}

export interface GitInfo {
  sha?: string;
  branch?: string;
  originUrl?: string;
}

export interface GoalSetParams {
  ref: string;
  objective?: string;
}

export interface GoalSetResponse {
  started: boolean;
}

export interface GoalState {
  status: string;
  iterations: number;
}

export interface HarnessDescriptor {
  id: string;
  label: string;
  kind?: string;
  emptyTaskUnsupportedReason?: string;
  emptyTaskUnsupportedNextAction?: string;
}

export interface HarnessListParams {
}

export interface HarnessListResponse {
  data: HarnessDescriptor[];
}

export interface InitializeParams {
  clientInfo: ClientInfo;
  capabilities: Capabilities;
}

export interface InitializeResponse {
  serverInfo: ServerInfo;
  protocolVersion: string;
  sourceId: string;
  features: FeatureSet;
}

export interface InputItem {
  type: string;
  text?: string;
  url?: string;
  mediaType?: string;
  data?: string;
  name?: string;
  path?: string;
  metadata?: Record<string, string>;
}

export interface InstanceCreateParams {
  type: string;
  name: string;
  apiStyle: string;
  baseUrl: string;
}

export interface InstanceEditParams {
  name: string;
  apiStyle: string;
  baseUrl: string;
}

export interface InstanceEntry {
  name: string;
  type: string;
  apiStyle: string;
  baseUrl: string;
  isDefault: boolean;
  authModes?: string[];
  activeSource: string;
  hasStoredFile?: boolean;
  hasStoredOAuth: boolean;
  envVar?: string;
  storedEmail?: string;
}

export interface InstanceListResponse {
  instances: InstanceEntry[];
  availableTypes: string[];
}

export interface InstanceRemoveParams {
  name: string;
}

export interface InstanceSetDefaultParams {
  name: string;
}

export interface ItemCompletedPayload {
}

export interface ItemStartedPayload {
}

export interface LaunchConfigDiagnostic {
  layer: string;
  field: string;
  message: string;
}

export interface LaunchConfigGetLayerParams {
  cwd: string;
  layer: string;
}

export interface LaunchConfigLayer {
  schema?: number;
  model?: string;
  fastCheapModel?: string;
  agent?: string;
  reasoningEffort?: string;
  contextStrategy?: string;
  openAIResponsesContinuation?: string;
  sandbox?: string;
  sandboxNet?: boolean;
  maxRounds?: number;
  maxSubagentDepth?: number;
  maxConcurrentDelegateTurns?: number;
  maxRetainedTerminal?: number;
  noProjectPrompts?: boolean;
  nonInteractive?: boolean;
  appReplaySize?: number;
  skillsDirs?: string[];
  pluginDirs?: string[];
  mcpConfigs?: string[];
  systemPromptMode?: string;
  systemPromptFile?: string;
  systemPromptText?: string;
  systemPromptAppendMode?: string;
  systemPromptAppendFile?: string;
  systemPromptAppendText?: string;
  systemPromptAppend?: string[];
  modelFallbacks?: string[];
  mcps?: MCPServerSpec[];
  env?: Record<string, string>;
  verbose?: boolean;
  traceFile?: string;
  cpuProfile?: string;
  exportATIFPath?: string;
  exportATIFProviderHandles?: string;
}

export interface LaunchConfigResolveParams {
  cwd: string;
  launchOverrides?: LaunchConfigLayer;
}

export interface LaunchConfigResolved {
  effective: LaunchConfigLayer;
  layers: Record<string, LaunchConfigLayer>;
  provenance: Record<string, string>;
  repo?: RepoLaunchConfigStatus;
  diagnostics?: LaunchConfigDiagnostic[];
}

export interface LaunchConfigSetLayerParams {
  cwd: string;
  layer: string;
  config: LaunchConfigLayer;
}

export interface LaunchConfigTrustRepoParams {
  cwd: string;
  hash: string;
}

export interface LaunchOption {
  field: string;
  wireField: string;
  label: string;
  description?: string;
  group: string;
  kind: string;
  pathKind?: string;
  repeatable?: boolean;
  defaultableLayers?: string[];
  perLaunch: boolean;
  debugOnly?: boolean;
  envFallback?: LaunchOptionEnvFallback;
  choices?: LaunchOptionChoice[];
  driverSupport?: Record<string, boolean>;
}

export interface LaunchOptionChoice {
  value: string;
  label: string;
  disabled?: boolean;
  hint?: string;
}

export interface LaunchOptionEnvFallback {
  name: string;
  secret?: boolean;
}

export interface LaunchOptionSchemaResponse {
  options: LaunchOption[];
  excluded?: Record<string, string>;
}

export interface MCPServerSpec {
  name: string;
  command: string;
  args?: string[];
}

export interface MarketplaceAddParams {
  name?: string;
  source: MarketplaceSourceInput;
}

export interface MarketplaceBrowseParams {
  name: string;
}

export interface MarketplaceBrowseResponse {
  name: string;
  description?: string;
  plugins: MarketplaceCatalogPlugin[];
}

export interface MarketplaceCatalogPlugin {
  name: string;
  description?: string;
  category?: string;
  homepage?: string;
  author?: string;
}

export interface MarketplaceEntry {
  name: string;
  source: MarketplaceSourceInput;
  installLocation?: string;
  lastUpdated: number;
}

export interface MarketplaceListResponse {
  marketplaces: MarketplaceEntry[];
}

export interface MarketplaceNameParams {
  name: string;
}

export interface MarketplaceSourceInput {
  kind: string;
  repo?: string;
  url?: string;
  path?: string;
  ref?: string;
  sha?: string;
}

export interface ModelDescriptor {
  provider: string;
  model: string;
}

export interface ModelListDiagnostic {
  provider?: string;
  source?: string;
  title?: string;
  message: string;
  hint?: string;
}

export interface ModelListParams {
  harness?: string;
  cwd?: string;
}

export interface ModelListResponse {
  data: ModelDescriptor[];
  diagnostics?: ModelListDiagnostic[];
  recent?: ModelDescriptor[];
}

export interface OutputImage {
  source: string;
  name?: string;
  mediaType?: string;
  size?: number;
  url?: string;
  sha?: string;
  path?: string;
}

export interface PathValidateParams {
  path: string;
  kind?: string;
}

export interface PathValidateResponse {
  path: string;
  valid: boolean;
  error?: string;
}

export interface PathsCompleteParams {
  prefix: string;
  limit?: number;
  includeFiles?: boolean;
}

export interface PathsCompleteResponse {
  data: string[];
}

export interface PluginCheckNowResponse {
  updated?: string[];
  errors?: string[];
}

export interface PluginEntry {
  plugin: string;
  marketplace: string;
  version: string;
  enabled: boolean;
  autoUpgrade: boolean;
  broken: boolean;
  installPath: string;
  gitCommitSha?: string;
  installedAt: number;
  lastUpdated: number;
}

export interface PluginListResponse {
  plugins: PluginEntry[];
}

export interface PluginRefParams {
  plugin: string;
  marketplace: string;
}

export interface PluginSetAutoUpgradeParams {
  plugin: string;
  marketplace: string;
  autoUpgrade: boolean;
}

export interface ProjectsRecentParams {
  limit?: number;
}

export interface ProjectsRecentResponse {
  data: string[];
}

export interface QueueState {
  depth?: number;
  preview?: string[];
  ids?: string[];
  texts?: string[];
}

export interface ReasoningSummaryDeltaParams {
  threadId: string;
  ref?: string;
  turnId: string;
  itemId: string;
  summaryIndex: number;
  delta: string;
}

export interface RepoLaunchConfigStatus {
  path: string;
  hash?: string;
  trust: string;
  preview?: string;
}

export interface SandboxEscalationRequested {
  threadId?: string;
  ref?: string;
  escalationId: string;
  mode: string;
  tool: string;
  kind: string;
  deniedPath: string;
  command?: string;
  outputSoFar?: string;
  partiallyRan?: boolean;
}

export interface SandboxEscalationResolveParams {
  threadId?: string;
  ref?: string;
  escalationId: string;
  approve: boolean;
}

export interface SandboxEscalationResolved {
  threadId?: string;
  ref?: string;
  escalationId: string;
}

export interface SerfAttentionChangedPayload {
}

export interface SerfAuthUpdatedPayload {
}

export interface SerfDiagnostics {
  tools?: SerfToolInfo[];
  mcp?: SerfMCPServerInfo[];
  skills?: SerfSkillInfo[];
  plugins?: SerfPluginInfo[];
  hooks?: Record<string, number>;
  jobs?: SerfJobInfo[];
  agents?: string[];
}

export interface SerfJobFinishedPayload {
}

export interface SerfJobInfo {
  jobId: string;
  jobType: string;
  status: string;
  reason?: string;
  exhaustionBudget?: string;
  exhaustionLimit?: number;
  resumable?: boolean;
  exitCode?: number;
  outputBytes: number;
  transcriptRef?: string;
  fromWatch?: boolean;
  background?: boolean;
  command?: string;
  delegateId?: string;
  task?: string;
  originTurnId?: string;
  originToolCallId?: string;
  originItemId?: string;
}

export interface SerfJobStartedPayload {
}

export interface SerfLaunchUpdatedPayload {
}

export interface SerfMCPServerInfo {
  name: string;
  tools: string[];
  status?: string;
  error?: string;
}

export interface SerfMarketplaceUpdatedPayload {
}

export interface SerfPluginInfo {
  name: string;
  version?: string;
  skillCount: number;
  agentCount: number;
  hookCount: number;
  mcpCount: number;
}

export interface SerfPluginUpdatedPayload {
}

export interface SerfSkillInfo {
  name: string;
  description?: string;
}

export interface SerfSteeringInjectedPayload {
}

export interface SerfSubagentPreviewParams {
  ref: string;
  limit?: number;
}

export interface SerfSubagentPreviewResponse {
  ref: string;
  items: ThreadItem[];
  truncated: boolean;
}

export interface SerfThread {
  ref: string;
  parentRef?: string;
  kind?: string;
  profile?: string;
  activeTurnId?: string;
  contextPressure?: number;
  contextUsed?: number;
  contextWindow?: number;
  contextRemaining?: number;
  capabilities: ThreadCapabilities;
  diagnostics?: SerfDiagnostics;
  queue: QueueState;
  goal?: GoalState;
  usage?: SerfUsage;
  workMillis?: number;
  activeTurnStartedAt?: number;
  cost?: string;
  askPending?: boolean;
  pendingEscalations?: SandboxEscalationRequested[];
  reasoningEffort?: string;
  reasoningEffortLevels?: string[];
  supportsReasoning?: boolean;
}

export interface SerfToolInfo {
  name: string;
  source: string;
}

export interface SerfTreeChangedPayload {
}

export interface SerfUsage {
  inputTokens?: number;
  outputTokens?: number;
  cacheReadTokens?: number;
  totalTokens?: number;
}

export interface ServerInfo {
  name: string;
  version: string;
}

export interface SettingsAgentEntry {
  name: string;
  editPath?: string;
}

export interface SettingsCodexLaunchEntry {
  id: string;
  binary?: string;
  workingDir?: string;
  listen?: string;
  timeoutMillis?: number;
  envKeys?: string[];
}

export interface SettingsHubOverview {
  version?: string;
  commit?: string;
  listenAddr?: string;
  runDir?: string;
  spawnTimeout?: string;
  bearerTokenAge?: string;
  pastIndex?: SettingsPastIndexOverview;
}

export interface SettingsMCPOverview {
  servers?: SettingsMCPServerEntry[];
  error?: string;
}

export interface SettingsMCPServerEntry {
  name: string;
  transport?: string;
  status?: string;
  error?: string;
}

export interface SettingsOverviewResponse {
  hub?: SettingsHubOverview;
  storage?: SettingsStorageOverview;
  agents?: SettingsAgentEntry[];
  codexLaunches?: SettingsCodexLaunchEntry[];
  mcpDiscovered?: SettingsMCPOverview;
}

export interface SettingsPastIndexOverview {
  path?: string;
  size?: string;
  perPage?: number;
  count?: number;
}

export interface SettingsStorageOverview {
  stateDir?: string;
}

export interface TaskListParams {
  ref?: string;
}

export interface TaskListResponse {
  data: unknown;
}

export interface TaskUpdatedParams {
  threadId?: string;
  ref?: string;
  total: number;
  done: number;
}

export interface Thread {
  id: string;
  sessionId: string;
  projectId?: string;
  projectPath?: string;
  forkedFromId?: string;
  preview: string;
  ephemeral: boolean;
  modelProvider: string;
  createdAt: number;
  updatedAt: number;
  status: ThreadStatus;
  path?: string;
  cwd: string;
  cliVersion: string;
  source: string;
  threadSource?: string;
  agentNickname?: string;
  agentRole?: string;
  gitInfo?: GitInfo;
  name?: string;
  turns?: Turn[];
  serf: SerfThread;
}

export interface ThreadCapabilities {
  send: boolean;
  steer: boolean;
  interrupt: boolean;
  compact: boolean;
  clear: boolean;
  forkFromTurn: boolean;
  shutdown: boolean;
  changeModel: boolean;
  queue: boolean;
  goal: boolean;
  rename: boolean;
}

export interface ThreadClearParams {
  ref: string;
}

export interface ThreadClearResponse {
  thread: Thread;
  ref: string;
}

export interface ThreadClosedPayload {
}

export interface ThreadCompactStartParams {
  ref: string;
}

export interface ThreadForkParams {
  ref: string;
  sourceTurnId: string;
  editedInput?: string;
  label?: string;
  modelProvider?: string;
  model?: string;
  deferInput?: boolean;
  aside?: boolean;
}

export interface ThreadForkResponse {
  thread: Thread;
  originalInput?: string;
}

export interface ThreadItem {
  type: string;
  id: string;
  turnId?: string;
  transcriptEntryIndex?: number;
  text?: string;
  delta?: string;
  images?: InputItem[];
  toolName?: string;
  callId?: string;
  argumentsJson?: string;
  description?: string;
  output?: string;
  error?: string;
  outputImages?: OutputImage[];
  status?: string;
  startedAt?: number;
  completedAt?: number;
  durationMs?: number;
  exitCode?: number;
  raw?: unknown;
  eventKind?: string;
  source?: string;
}

export interface ThreadListParams {
  cursor?: string;
  limit?: number;
  sortKey?: string;
  sortDirection?: string;
  searchTerm?: string;
  statuses?: string[];
  sourceIds?: string[];
  includeSubagents?: boolean;
}

export interface ThreadListResponse {
  data: Thread[];
  nextCursor?: string;
  backwardsCursor?: string;
}

export interface ThreadModelChangedParams {
  threadId: string;
  ref: string;
  modelProvider: string;
  model: string;
  reasoningEffortLevels?: string[];
  supportsReasoning?: boolean;
}

export interface ThreadModelSetParams {
  ref: string;
  modelProvider: string;
  model: string;
}

export interface ThreadNameChangedParams {
  threadId: string;
  ref: string;
  name: string;
  source?: string;
}

export interface ThreadNameSetParams {
  ref: string;
  name: string;
}

export interface ThreadQueueChangedParams {
  threadId?: string;
  ref?: string;
  queue: QueueState;
}

export interface ThreadReadParams {
  threadId?: string;
  ref?: string;
  includeTurns: boolean;
  itemsView?: string;
  subscribe?: boolean;
  replaceSubscription?: boolean;
  turnLimit?: number;
}

export interface ThreadReadResponse {
  thread: Thread;
  olderCursor?: string;
}

export interface ThreadReasoningEffortChangedParams {
  threadId: string;
  ref: string;
  reasoningEffort?: string;
}

export interface ThreadReasoningEffortSetParams {
  ref: string;
  reasoningEffort: string;
}

export interface ThreadResumeParams {
  ref?: string;
  sessionId?: string;
}

export interface ThreadResumeResponse {
  thread: Thread;
}

export interface ThreadShutdownParams {
  ref: string;
}

export interface ThreadStartParams {
  harness?: string;
  cwd: string;
  input?: InputItem[];
  modelProvider?: string;
  model?: string;
  profile?: string;
  reasoningEffort?: string;
  nonInteractive?: boolean;
  launchOverrides?: LaunchConfigLayer;
}

export interface ThreadStartResponse {
  thread: Thread;
  turn: Turn;
}

export interface ThreadStartedPayload {
}

export interface ThreadStatus {
  type: string;
  activeFlags?: string[];
}

export interface ThreadStatusChangedParams {
  threadId: string;
  ref?: string;
  status: ThreadStatus;
}

export interface ThreadTranscriptListParams {
  ref: string;
}

export interface ThreadTranscriptListResponse {
  data: ThreadTranscriptTarget[];
}

export interface ThreadTranscriptTarget {
  ref: string;
  threadId?: string;
  title: string;
  kind: string;
  status?: string;
  source?: string;
  turnsUsed?: number;
}

export interface ThreadTurnItemsListParams {
  threadId?: string;
  ref?: string;
  turnId: string;
  cursor?: string;
  limit?: number;
}

export interface ThreadTurnItemsListResponse {
  data: ThreadItem[];
  nextCursor?: string;
}

export interface ThreadTurnsListParams {
  threadId?: string;
  ref?: string;
  cursor?: string;
  limit?: number;
  itemsView?: string;
}

export interface ThreadTurnsListResponse {
  data: Turn[];
  nextCursor?: string;
}

export interface ToolOutputDeltaParams {
  threadId?: string;
  ref?: string;
  turnId?: string;
  itemId: string;
  callId: string;
  delta: string;
}

export interface Turn {
  id: string;
  items?: ThreadItem[];
  itemsView: string;
  status: string;
  error?: TurnError;
  startedAt?: number;
  completedAt?: number;
  durationMs?: number;
  usage?: SerfUsage;
  cost?: string;
}

export interface TurnCancelQueuedParams {
  ref: string;
  index: number;
  expectedEntryId?: string;
}

export interface TurnCancelQueuedResponse {
  removedText: string;
  removedImages?: number;
}

export interface TurnCompletedParams {
  turnId: string;
  turn: Turn;
}

export interface TurnDrainAsSteerParams {
  ref: string;
  input?: InputItem[];
}

export interface TurnError {
  message: string;
  additionalDetails?: string;
  codexErrorInfo?: unknown;
  source?: string;
  title?: string;
  hint?: string;
  cause?: DiagnosticCause;
}

export interface TurnInterruptParams {
  ref?: string;
  threadId?: string;
  expectedTurnId?: string;
}

export interface TurnPromoteQueuedAsSteerParams {
  ref: string;
  index: number;
  expectedEntryId?: string;
}

export interface TurnQueueParams {
  ref: string;
  input?: InputItem[];
}

export interface TurnStartParams {
  ref?: string;
  threadId?: string;
  input?: InputItem[];
}

export interface TurnStartResponse {
  turn: Turn;
}

export interface TurnStartedPayload {
}

export interface TurnSteerParams {
  ref?: string;
  threadId?: string;
  expectedTurnId?: string;
  input?: InputItem[];
}

export interface UpgradeParams {
  requested?: string;
}

export interface UpgradeResponse {
  release: string;
  channel: string;
  url: string;
  archive: string;
  prefix: string;
  binDir: string;
  shareBinDir: string;
  installed: string[];
  restartMessage: string;
}

export interface WarningPayload {
}

export const METHOD_NAMES = [
  "initialize",
  "ping",
  "thread/list",
  "thread/read",
  "thread/turns/list",
  "thread/turns/items/list",
  "thread/start",
  "thread/resume",
  "thread/fork",
  "thread/clear",
  "thread/model/set",
  "serf/thread/name/set",
  "thread/reasoning-effort/set",
  "thread/compact/start",
  "thread/shutdown",
  "turn/start",
  "turn/steer",
  "turn/interrupt",
  "turn/queue",
  "turn/drainAsSteer",
  "turn/promoteQueuedAsSteer",
  "turn/cancelQueued",
  "goal/set",
  "serf/tasks/list",
  "serf/thread/transcripts/list",
  "serf/subagentPreview",
  "serf/paths/complete",
  "serf/projects/recent",
  "serf/path/validate",
  "serf/harnesses/list",
  "serf/upgrade",
  "serf/auth/status",
  "serf/auth/login/start",
  "serf/auth/login/complete",
  "serf/auth/logout",
  "serf/auth/list",
  "serf/auth/apiKey/set",
  "serf/auth/device/start",
  "serf/auth/device/poll",
  "serf/launch/resolve",
  "serf/launch/schema",
  "serf/launch/getLayer",
  "serf/launch/setLayer",
  "serf/launch/trustRepo",
  "model/list",
  "serf/instance/list",
  "serf/instance/create",
  "serf/instance/edit",
  "serf/instance/remove",
  "serf/instance/setDefault",
  "serf/plugin/checkNow",
  "serf/marketplace/list",
  "serf/marketplace/add",
  "serf/marketplace/remove",
  "serf/marketplace/refresh",
  "serf/marketplace/browse",
  "serf/plugin/list",
  "serf/plugin/install",
  "serf/plugin/upgrade",
  "serf/plugin/remove",
  "serf/plugin/enable",
  "serf/plugin/disable",
  "serf/plugin/setAutoUpgrade",
  "serf/command/list",
  "serf/settings/overview",
  "serf/sandbox/escalation/resolve",
] as const;

export type MethodName = (typeof METHOD_NAMES)[number];

export type NotificationName =
  | "thread/started"
  | "thread/closed"
  | "thread/status/changed"
  | "thread/queueChanged"
  | "serf/thread/name/changed"
  | "thread/model/changed"
  | "thread/reasoning-effort/changed"
  | "turn/started"
  | "turn/completed"
  | "item/started"
  | "item/completed"
  | "item/agentMessage/delta"
  | "item/agentMessage/reset"
  | "item/reasoning/summaryTextDelta"
  | "item/toolOutput/delta"
  | "warning"
  | "serf/steering/injected"
  | "serf/job/started"
  | "serf/job/finished"
  | "serf/auth/updated"
  | "serf/launch/updated"
  | "serf/attention/changed"
  | "serf/marketplace/updated"
  | "serf/plugin/updated"
  | "serf/task/updated"
  | "serf/sandbox/escalation/requested"
  | "serf/sandbox/escalation/resolved"
  | "serf/tree/changed";

export interface MethodTypes {
  "initialize": { params: InitializeParams; result: InitializeResponse };
  "ping": { params: EmptyParams; result: EmptyResponse };
  "thread/list": { params: ThreadListParams; result: ThreadListResponse };
  "thread/read": { params: ThreadReadParams; result: ThreadReadResponse };
  "thread/turns/list": { params: ThreadTurnsListParams; result: ThreadTurnsListResponse };
  "thread/turns/items/list": { params: ThreadTurnItemsListParams; result: ThreadTurnItemsListResponse };
  "thread/start": { params: ThreadStartParams; result: ThreadStartResponse };
  "thread/resume": { params: ThreadResumeParams; result: ThreadResumeResponse };
  "thread/fork": { params: ThreadForkParams; result: ThreadForkResponse };
  "thread/clear": { params: ThreadClearParams; result: ThreadClearResponse };
  "thread/model/set": { params: ThreadModelSetParams; result: EmptyResponse };
  "serf/thread/name/set": { params: ThreadNameSetParams; result: EmptyResponse };
  "thread/reasoning-effort/set": { params: ThreadReasoningEffortSetParams; result: EmptyResponse };
  "thread/compact/start": { params: ThreadCompactStartParams; result: EmptyResponse };
  "thread/shutdown": { params: ThreadShutdownParams; result: EmptyResponse };
  "turn/start": { params: TurnStartParams; result: TurnStartResponse };
  "turn/steer": { params: TurnSteerParams; result: EmptyResponse };
  "turn/interrupt": { params: TurnInterruptParams; result: EmptyResponse };
  "turn/queue": { params: TurnQueueParams; result: EmptyResponse };
  "turn/drainAsSteer": { params: TurnDrainAsSteerParams; result: EmptyResponse };
  "turn/promoteQueuedAsSteer": { params: TurnPromoteQueuedAsSteerParams; result: EmptyResponse };
  "turn/cancelQueued": { params: TurnCancelQueuedParams; result: TurnCancelQueuedResponse };
  "goal/set": { params: GoalSetParams; result: GoalSetResponse };
  "serf/tasks/list": { params: TaskListParams; result: TaskListResponse };
  "serf/thread/transcripts/list": { params: ThreadTranscriptListParams; result: ThreadTranscriptListResponse };
  "serf/subagentPreview": { params: SerfSubagentPreviewParams; result: SerfSubagentPreviewResponse };
  "serf/paths/complete": { params: PathsCompleteParams; result: PathsCompleteResponse };
  "serf/projects/recent": { params: ProjectsRecentParams; result: ProjectsRecentResponse };
  "serf/path/validate": { params: PathValidateParams; result: PathValidateResponse };
  "serf/harnesses/list": { params: HarnessListParams; result: HarnessListResponse };
  "serf/upgrade": { params: UpgradeParams; result: UpgradeResponse };
  "serf/auth/status": { params: AuthStatusParams; result: AuthStatusResponse };
  "serf/auth/login/start": { params: AuthLoginStartParams; result: AuthLoginStartResponse };
  "serf/auth/login/complete": { params: AuthLoginCompleteParams; result: AuthLoginCompleteResponse };
  "serf/auth/logout": { params: AuthLogoutParams; result: AuthLogoutResponse };
  "serf/auth/list": { params: EmptyParams; result: AuthListResponse };
  "serf/auth/apiKey/set": { params: AuthApiKeySetParams; result: AuthStatusResponse };
  "serf/auth/device/start": { params: AuthDeviceStartParams; result: AuthDeviceStartResponse };
  "serf/auth/device/poll": { params: AuthDevicePollParams; result: AuthDevicePollResponse };
  "serf/launch/resolve": { params: LaunchConfigResolveParams; result: LaunchConfigResolved };
  "serf/launch/schema": { params: EmptyParams; result: LaunchOptionSchemaResponse };
  "serf/launch/getLayer": { params: LaunchConfigGetLayerParams; result: LaunchConfigLayer };
  "serf/launch/setLayer": { params: LaunchConfigSetLayerParams; result: LaunchConfigResolved };
  "serf/launch/trustRepo": { params: LaunchConfigTrustRepoParams; result: LaunchConfigResolved };
  "model/list": { params: ModelListParams; result: ModelListResponse };
  "serf/instance/list": { params: EmptyParams; result: InstanceListResponse };
  "serf/instance/create": { params: InstanceCreateParams; result: InstanceListResponse };
  "serf/instance/edit": { params: InstanceEditParams; result: InstanceListResponse };
  "serf/instance/remove": { params: InstanceRemoveParams; result: InstanceListResponse };
  "serf/instance/setDefault": { params: InstanceSetDefaultParams; result: InstanceListResponse };
  "serf/plugin/checkNow": { params: EmptyParams; result: PluginCheckNowResponse };
  "serf/marketplace/list": { params: EmptyParams; result: MarketplaceListResponse };
  "serf/marketplace/add": { params: MarketplaceAddParams; result: MarketplaceListResponse };
  "serf/marketplace/remove": { params: MarketplaceNameParams; result: MarketplaceListResponse };
  "serf/marketplace/refresh": { params: MarketplaceNameParams; result: MarketplaceListResponse };
  "serf/marketplace/browse": { params: MarketplaceBrowseParams; result: MarketplaceBrowseResponse };
  "serf/plugin/list": { params: EmptyParams; result: PluginListResponse };
  "serf/plugin/install": { params: PluginRefParams; result: PluginListResponse };
  "serf/plugin/upgrade": { params: PluginRefParams; result: PluginListResponse };
  "serf/plugin/remove": { params: PluginRefParams; result: PluginListResponse };
  "serf/plugin/enable": { params: PluginRefParams; result: PluginListResponse };
  "serf/plugin/disable": { params: PluginRefParams; result: PluginListResponse };
  "serf/plugin/setAutoUpgrade": { params: PluginSetAutoUpgradeParams; result: PluginListResponse };
  "serf/command/list": { params: EmptyParams; result: CommandListResponse };
  "serf/settings/overview": { params: EmptyParams; result: SettingsOverviewResponse };
  "serf/sandbox/escalation/resolve": { params: SandboxEscalationResolveParams; result: EmptyResponse };
}

export interface NotificationTypes {
  "thread/started": ThreadStartedPayload;
  "thread/closed": ThreadClosedPayload;
  "thread/status/changed": ThreadStatusChangedParams;
  "thread/queueChanged": ThreadQueueChangedParams;
  "serf/thread/name/changed": ThreadNameChangedParams;
  "thread/model/changed": ThreadModelChangedParams;
  "thread/reasoning-effort/changed": ThreadReasoningEffortChangedParams;
  "turn/started": TurnStartedPayload;
  "turn/completed": TurnCompletedParams;
  "item/started": ItemStartedPayload;
  "item/completed": ItemCompletedPayload;
  "item/agentMessage/delta": AgentMessageDeltaParams;
  "item/agentMessage/reset": AgentMessageResetParams;
  "item/reasoning/summaryTextDelta": ReasoningSummaryDeltaParams;
  "item/toolOutput/delta": ToolOutputDeltaParams;
  "warning": WarningPayload;
  "serf/steering/injected": SerfSteeringInjectedPayload;
  "serf/job/started": SerfJobStartedPayload;
  "serf/job/finished": SerfJobFinishedPayload;
  "serf/auth/updated": SerfAuthUpdatedPayload;
  "serf/launch/updated": SerfLaunchUpdatedPayload;
  "serf/attention/changed": SerfAttentionChangedPayload;
  "serf/marketplace/updated": SerfMarketplaceUpdatedPayload;
  "serf/plugin/updated": SerfPluginUpdatedPayload;
  "serf/task/updated": TaskUpdatedParams;
  "serf/sandbox/escalation/requested": SandboxEscalationRequested;
  "serf/sandbox/escalation/resolved": SandboxEscalationResolved;
  "serf/tree/changed": SerfTreeChangedPayload;
}

export type AnyNotification = { [K in NotificationName]: { method: K; params: NotificationTypes[K] } }[NotificationName];
