//go:build serffuzz

package main

import "testing"

// FuzzRootTUIFactories replays the root TUI's deterministic constructor,
// control, update, and render scenarios as a fuzz-selectable program. The
// scenarios keep effects behind their existing fake appwire, filesystem, and
// clipboard boundaries; terminal-backed E2E cases are deliberately excluded.
func FuzzRootTUIFactories(f *testing.F) {
	programs := []func(*testing.T){
		TestErroredLane_TUI,
		TestStateColorNormalizesRawWireStatus,
		TestNeedsYouCount,
		TestNeedsYouBadge,
		TestDashboardHeaderBadgeKeepsExactWidth,
		TestDisplayWord_UnifiedVocabulary,
		TestHubNodeFromThread_CarriesAskPending,
		TestHubDetailFromThread_CarriesAskPending,
		TestDashboardSessionRow_AskPendingMarker,
		TestNoticePanelTextIncludesCategoryAndNextAction,
		TestHubModelNoticesPersistUntilDismissed,
		TestHubModelDashboardRendersNotices,
		TestHubModelNoticesRenderAsPane,
		TestHubModelClearsActionUnavailableNoticeWhenSessionChanges,
		TestHubModelAuthErrorsRenderStructuredNoticeAndClearOnSuccess,
		TestNoticePanel_CauseProviderClassifiesProvider,
		TestNoticePanel_NoCauseFallsBackToMessageMatch,
		TestNoticePanel_NoCauseNonProviderMessage,
		TestHubModelAppWireAndProviderErrorsRenderStructuredNotices,
		TestHubModelSessionComposerAwaitingQuestionKeyedOnPendingSet,
		TestSessionComposerMode_RestedAwaitingShowsSend,
		TestSessionComposerMode_ActiveStillQueues,
		TestModelPickerItems_SetsGroupAndPrettifiedDisplay,
		TestModelPickerItems_MetaTailFromCatalog,
		TestModelPickerItems_UncataloguedModelStillRendersEmptyMeta,
		TestModelPickerItems_SortsDatedSnapshotLastWithinProvider,
		TestModelPickerItemProvider_ReadsGroupNotDisplay,
		TestModelPickerItemsFromResponse_PrependsRecentGroup,
		TestModelPickerItemsFromResponse_RecentPreservesServerRecencyOrderAcrossProviders,
		TestModelPickerItemsFromResponse_NoRecentOmitsGroup,
		TestNoticePanelHasStateBar,
		TestHubModelDisablesLegacySessionBackends,
		TestHubCommandRoutingStaysInsideAppWireClientBoundary,
		TestSendHubGoalSetsObjective,
		TestSendHubGoalClears,
		TestHubGoalStatusText,
		TestSessionHeaderShowsGoalChip,
		TestHubModelSandboxEscalation_NotificationSurfacesPromptForViewed,
		TestHubModelSandboxEscalation_BareAndComposerKeysDoNotAnswer,
		TestHubModelSandboxEscalation_ChordDeniesOnAck,
		TestHubModelSandboxEscalation_TransportFailureReSurfaces,
		TestHubModelSandboxEscalation_ConflictIsTerminal,
		TestHubModelSandboxEscalation_SameSessionResyncReSurfaces,
		TestHubModelSandboxEscalation_NonViewedEnqueuedAndSurfacedOnEntry,
		TestHubModelSandboxEscalation_ReEntryDoesNotAutoDeny,
		TestHubModelSandboxEscalation_ConcurrentQueueBothAnswerable,
		TestHubModelSandboxEscalation_SnapshotSurfacesOnEntry,
		TestHubModelSandboxEscalation_SnapshotDeDupesLive,
		TestComposerChipStripShowsChips,
		TestComposerChipStripIncludesModeChip,
		TestComposerFooterHintsAreModeAware,
		TestComposerFooterHintsQueueCanSteer,
		TestHubTUISampleCorpusCoversRequiredVariants,
		TestHubTUISampleCorpusHasGoldenRendersForCoreSurfaces,
		TestHubTUISampleCorpusHasShellAndWidgetStateRenders,
		TestHubTUISampleCorpusHasFocusAndDraftInteractionSamples,
		TestGoldenRendersAcrossThemes,
		TestSampleRenders_EachThemeProducesNonEmptyView,
		TestHubModelSessionPaletteKeepsSelectionVisibleWhenWindowed,
		TestPendingCoordinator_RegisterEmitsRegisteredMsg,
		TestPendingCoordinator_FailEmitsFailedMsg,
		TestPendingCoordinator_TimeoutMarksFailed,
		TestPendingCoordinator_TimedOutEntryReconcilesLateNotification,
		TestPendingCoordinator_ReconcilePrefersLivePendingOverFailedDuplicate,
		TestPendingCoordinator_TryReconcile_MatchesByMethodAndText,
		TestPendingCoordinator_TryReconcile_DrainSpecialIgnoresText,
		TestPendingCoordinator_TryReconcile_MatchesOldestDuplicate,
		TestPendingCoordinator_TryReconcile_DrainMatchesOldest,
		TestPendingCoordinator_TryReconcile_NoMatchReturnsFalse,
		TestPendingCoordinator_TryReconcileScopesByRef,
		TestReconcilePendingFromNotification_ImageOnlyUserMessage,
		TestReconcilePendingFromNotification_TurnCompletedUserMessage,
		TestReconcilePendingFromNotification_TurnCompletedImageOnlyUserMessage,
		TestPendingCoordinator_FailIsIdempotent,
		TestPendingCoordinator_DispatchDoesNotDropBeyondFormerOutboxCap,
		TestHubReducer_RendersPendingChatMessage,
		TestHubReducer_MarksFailed,
		TestHubReducer_RemovesPendingOnConfirm,
		TestHubReducer_PendingUserConfirmPreservesAuthoritativeMetadata,
		TestHubModelBrowseKJMovesSelectionAndReachesFork,
		TestHubModelBrowseSelectionScrollsIntoView,
		TestPendingAskQuestions_EmptyTranscriptHasNoPending,
		TestPendingAskQuestions_CompletedNonErrorAskIsPending,
		TestPendingAskQuestions_UserReplyResolvesEverythingBeforeIt,
		TestPendingAskQuestions_ErroredOrIncompleteCallsExcluded,
		TestPendingAskQuestions_MultipleCallsInOneRoundConcatenateInPostingOrder,
		TestPendingAskQuestions_SteeringDoesNotResolve,
		TestComposeAskAnswers_SpecGoldenExample,
		TestComposeAskAnswers_UnresolvedComposesAsSkipped,
		TestComposeAskAnswers_FallbackEmbedsStatedIfUnanswered,
		TestComposeAskAnswers_MultiSelectJoinsQuotedLabels,
		TestQuestionOverlay_OptionPickSingleSelect,
		TestQuestionOverlay_OptionPickMultiSelectToggles,
		TestQuestionOverlay_NoteAttachesToWhicheverResolutionIsChosen,
		TestQuestionOverlay_NoteEscCancelsWithoutChangingIt,
		TestQuestionOverlay_YouDecideWithLeaning,
		TestQuestionOverlay_YouDecideWithoutLeaningIsStillCommitted,
		TestQuestionOverlay_DoThatOnlyAvailableWhenIfUnanswered,
		TestQuestionOverlay_SkipByLeavingUnansweredComposesAsSkipped,
		TestQuestionOverlay_TabPagesToNextQuestion,
		TestQuestionOverlay_EscDefersKeepingAnswers,
		TestQuestionOverlay_ReviewStepListsAnswersAndWarnsOnUnanswered,
		TestUpdateQuestionOverlayKey_StaleReadyToSubmitDoesNotResendAfterRollback,
		TestReturnToDashboard_DefersLiveQuestionOverlay,
		TestReturnToDashboard_DeferredOverlayDoesNotHauntADifferentSession,
		TestHubModelAppShellKeepsDashboardFooterUnderPaletteOverlay,
		TestHubModelAppShellBoundsPaletteOverlayToShortHeight,
		TestHubModelAppShellKeepsPaletteSelectionVisibleWhenWindowed,
		TestHubModelAppShellSessionTopBarAndComposerRegion,
		TestHubModelAppShellAddsSubtleChromeStyles,
		TestHubModelAppShellAnchorsFooterToKnownHeight,
		TestHubModelCtrlOReturnsDashboardFromCommandPaletteOverlay,
		TestHubModelCtrlOClearsSessionOverlay,
		TestActionBarWrapsBeforeDroppingDashboardHint,
		TestDashboardFooterUsesTextKeyNames,
		TestDashboardFooterContainsKbdHintChrome,
		TestDashboardHeaderUsesSectionDivider,
		TestSendHubInputIncludesAttachments,
		TestSendHubQueueIncludesAttachments,
		TestSendHubDrainAsSteerIncludesAttachments,
		TestSendHubDrainAsSteerAlwaysUsesInputShape,
		TestSendClearsPendingAttachmentsOnSuccess,
		TestSendClearsOnlySubmittedAttachmentSnapshot,
		TestSendKeepsPendingAttachmentsOnError,
		TestSendDoesNotRestoreSubmittedAttachmentSnapshotOverNewDraft,
		TestSendRestoresSubmittedAttachmentSnapshotOnErrorWhenComposerUnchanged,
		TestAttachmentBytesReadFromTempFile,
		TestSubmitSnapshotsAttachmentSliceBeforeAsyncCommand,
		TestSessionHeaderHasThreeMainSections,
		TestSessionHeaderShowsRichContextWhenWindowKnown,
		TestParseTUIStartupOptionsDefaults,
		TestParseTUIStartupOptionsUsesEnvironmentDefaults,
		TestParseTUIStartupOptionsFlagsOverrideEnvironment,
		TestParseTUIStartupOptionsHelpReturnsErrHelp,
		TestParseTUIStartupOptionsHelpUsesEnvironmentHubAddr,
		TestPostQuitMessageFromHubModel,
		TestPostQuitMessageIgnoresOtherModels,
		TestHubModelAuthCommandsUseAppWire,
		TestHubModelAuthCommandsAppearInHelp,
		TestHubAuthStatusSummaryDistinguishesRefreshAndExpiredOAuth,
		TestHubModelLiveAgentCompletionUpdatesDeltaWithoutDuplicate,
		TestToolGroupRendersErrorResult,
		TestHubModelBrowseSelectedToolRendersFocusedAndCtrlTToggles,
		TestHubModelActionUnavailableNoticeIncludesSourceAndReason,
		TestDetailsDrawerShowsCapabilities,
		TestDetailsDrawerShowsHubDiagnostics,
		TestDetailsDrawerShowsMissingDiagnostics,
		TestHubModelSessionComposerIsVisibleWhenEmpty,
		TestHubModelSessionComposerShowsReadOnlyReasonAndDraft,
		TestHubModelBusyComposerShowsQueueOrReadOnlyMode,
		TestHubModelBusyEnterWithoutQueuePreservesDraftAndExplainsReason,
		TestHubModelBusyEnterRoutesToQueueAndClearsDraft,
		TestHubModelEnterSendsImageOnlySubmission,
		TestHubModelBusyEnterQueuesImageOnlySubmission,
		TestHubModelBusyEnterRestoresAttachmentsOnQueueFailure,
		TestHubModelBusyCtrlSDrainsQueueAsSteer,
		TestHubModelBusyCtrlSDrainFailureRestoresDraft,
		TestHubModelBusyCtrlSQueuedDrainPartialDoesNotRestoreDraft,
		TestHubModelBusyCtrlSWithEmptyQueueAndEmptyComposerBanner,
		TestHubModelSessionComposerAltEnterInsertsNewline,
		TestHubModelSessionComposerCtrlJInsertsNewline,
		TestHubModelSessionComposerUsesHistoryNavigationOnlyWhenEmpty,
		TestHubModelSessionComposerAddsSentPromptsToHistory,
		TestHubModelFailedSendPreservesDraftExactly,
		TestHubModelFailureRestorePreservesNewerComposerDraft,
		TestHubModelFailureRestorePreservesNewerAttachments,
		TestHubModelSessionComposerBoundsRenderedDraftHeight,
		TestHubModelSessionComposerShowsStaticCursorWhenEmpty,
		TestRenderComposerDraftSoftWrapsLongLines,
		TestHubModelSessionPickerOverlayKeepsComposerDraftVisible,
		TestHubModelSpawnModelPickerKeepsFormDraftVisible,
		TestHubModelSpawnPromptIsGroupedWithLaunchFields,
		TestPendingAttachmentsMutability,
		TestAttachmentChipsRender,
		TestRemoveAttachmentDropsByIndex,
		TestSessionSwitchClearsPendingAttachmentsAndTempFiles,
		TestRemoveAttachmentDefersTempCleanupDuringSubmit,
		TestTextOnlyCompletionDoesNotReleaseDeferredAttachmentCleanup,
		TestAltBackspaceRemovesLastAttachment,
		TestCtrlHWithAttachmentsFallsThrough,
		TestAltBackspaceDoesNotFireDuringPalette,
		TestCtrlVKeybindAttachesClipboardImage,
		TestCtrlAltVKeybindAttachesClipboardImage,
		TestPastedPathAttachesImage,
		TestPastedNonPathFallsThroughToTextarea,
		TestPastedNonImagePathFallsThroughToTextarea,
		TestDetailsDrawerHasSectionLabels,
		TestDetailsDrawerShowsMCPServerStatusAndError,
		TestDetailsDrawerShowsWorkTimeAndTokens,
		TestDetailsDrawerHidesWorkTimeAndTokensWhenAbsent,
		TestAddPendingAttachment_InsertsMarkerAtCursor,
		TestAddPendingAttachment_NumbersMonotonic,
		TestAddPendingAttachment_InsertsAtCursorPosition,
		TestRemovePendingAttachment_StripsMarker,
		TestNextMarker_AfterRemoval_DoesNotReuse,
		TestNextMarker_AfterRemovingHighest_DoesNotReuse,
		TestRemovePendingAttachment_NoOpForUnassignedMarker,
		TestCommandPaletteShowsSlashItems,
		TestRenderToolCall_Collapsed,
		TestRenderToolCall_Expanded,
		TestRenderToolCall_FocusedChangesArrow,
		TestRenderToolCall_DoneVsInProgress,
		TestRenderTasks_Empty,
		TestRenderTasks_SingleTask,
		TestRenderTasks_AllStatuses,
		TestRenderTasks_Dependencies,
		TestRenderTasks_ReasoningEffort,
		TestRenderTasks_WidthMinimum,
		TestToolIndices_Empty,
		TestToolIndices_MixedMessages,
		TestToolIndices_NoTools,
		TestFocusTool_InitialDown,
		TestFocusTool_UpDown,
		TestFocusTool_NoTools,
		TestIsToolFocused,
		TestIsToolFocused_NotInScrollMode,
		TestRenderMessage_PassesFocusedToTool,
		TestTaskStatus_Constants,
		TestTaskType_Constants,
		TestRenderToolCall_OutputHiddenWhenCollapsed,
		TestRenderToolCall_OutputShownWhenExpanded,
		TestTask_JSON,
		TestHubCommandRegistryHasQuit,
		TestHubSlashCommandHelpListsQuit,
		TestHubModelAgentsPickerReadsSelectedTranscriptThroughAppWire,
		TestHubModelUnavailableAgentTranscriptKeepsParentSession,
		TestHubTranscriptPickerItemsIncludeSourceStatusAndTurns,
		TestHubModelAgentsPickerShowsCodexSourceAndLiveSubagent,
		TestFetchHubTreeUsesAppWireThreadList,
		TestSendHubInputUsesAppWireTurnStart,
		TestHubModelAppliesAppWireNotifications,
		TestHubModelStreamsReasoningThenCollapsesOnAnswer,
		TestHubModelCompletesLiveToolWithoutDuplicateMessage,
		TestHubModelAppliesSteeringInjectedNotification,
		TestHubModelAppliesQueueChangedNotification,
		TestHubModelSurfacesStructuredWarningDiagnostic,
		TestHubModelTurnCompletedAppliesSnapshotItems,
		TestMessagesFromThreadIncludesFailedTurnDiagnostic,
		TestHubThreadFixtureKeepsSplitToolResultsGrouped,
		TestHubModelAppliesSerfJobNotificationsToDelegateTool,
		TestSessionRowAwaitingHasStateColor,
		TestSessionRowsHaveNoTreeConnectors,
		TestDashboardRowLess_AskPendingBandsAboveYourMove,
		TestRenderHubSessionStatusWithoutDiagnosticsMatchesThinSummary,
		TestRenderHubSessionStatusRendersDiagnosticsSections,
		TestRenderHubSessionStatusShortensLongDelegateJobIDs,
		TestFormatContextFragment,
		TestHubDetailFromThreadMapsWorkingStateFields,
		TestHubDetailFromThreadLeavesUsageNilWhenThreadHasNone,
		TestRenderHubSessionStatusShowsWorkAndTokenLines,
		TestSessionHeaderShowsWorkAndTokenChip,
		TestWriteWrappedStatusListWrapsAtWidth,
		TestParseSlashCommand,
		TestHubModelInitialFetchRendersLiveAndRecentRows,
		TestHubModelDashboardShowsFullSessionTreeGroupedByProject,
		TestHubModelDashboardRendersProjectTreeHierarchy,
		TestHubModelDashboardLaunchRowOpensUnscopedSpawn,
		TestHubModelDashboardLaunchSelectionSurvivesTreeRefresh,
		TestHubModelDashboardNewFromProjectRowUsesProjectDir,
		TestHubModelDashboardClampsRowsToTerminalHeight,
		TestRenderDashboardRowsKeepsLongPromptsSingleLineAndProjectVisible,
		TestHubModelDashboardSelectedRowUsesVisualStyle,
		TestHubModelDashboardSelectedTreeRowsDoNotMixCursorAndBranchGlyphs,
		TestHubModelDashboardDetailsRendersAsPane,
		TestHubModelDashboardSortsByAttentionThenRecency,
		TestHubModelDashboardShowsSourceLabels,
		TestHubModelDashboardNarrowUsesOneColumnWithEllipses,
		TestHubModelDashboardWideDetailsFollowSelection,
		TestHubModelDashboardWideDrawerDoesNotStealTextInput,
		TestHubModelDashboardWideDetailsShowDiagnosticSelection,
		TestHubModelDashboardUsesNForNewSession,
		TestHubModelDashboardSlashOpensCommandPalette,
		TestBuildProjectRowsShowsLiveThenRecent,
		TestHubModelEndedSessionCanResumeOnSend,
		TestHubModelCommandPaletteOwnsPrintableKeys,
		TestHubModelCommandPaletteCanOpenNewSession,
		TestHubModelDashboardProjectHeaderTogglesChildren,
		TestHubModelSessionEscEntersBrowseInsteadOfDashboard,
		TestHubModelBrowseSelectionHighlightsSelectedMessage,
		TestHubModelBrowsePageKeysScrollDisplayedLines,
		TestHubModelSessionBrowsePageUpShowsEarlierTranscript,
		TestHubModelBrowseArrowKeysStayWithComposer,
		TestHubModelEscBrowseArrowKeysScrollTranscriptWhenComposerEmpty,
		TestHubModelBrowseUpDownUseComposerHistory,
		TestHubModelBrowseMouseWheelScrollsViewport,
		TestHubModelMouseWheelFromComposeEntersBrowseAndScrolls,
		TestHubModelBrowseKeepsComposerVisibleAndTyping,
		TestHubModelBrowseCtrlTTogglesAllToolEntries,
		TestHubModelBrowseCtrlTExpandsReasoning,
		TestHubModelBrowseEnterTogglesSelectedDetail,
		TestHubModelSessionBrowseExitKeysReturnToCompose,
		TestHubModelCtrlOReturnsDashboardFromSession,
		TestHubModelSlashDashboardAndProjectNavigate,
		TestHubModelEnterOpensSessionDetail,
		TestHubModelSessionHeaderShowsCodexMetadata,
		TestHubModelSessionHeaderShowsProviderWhenModelUnknown,
		TestHubModelSessionStatusLineUsesProfileWhenModelHasNoProviderPrefix,
		TestHubModelSessionHeaderHandlesMissingMetadata,
		TestHubModelSessionHeaderTruncatesLongLabels,
		TestHubModelSessionStatusLineShowsConnectionAuthBusyAndError,
		TestHubModelSessionStatusLineReflectsCapabilityChanges,
		TestHubModelDashboardSpawnUsesSelectedProjectWorkingDir,
		TestHubSpawnSendsHarnessSeparatelyFromModel,
		TestHubModelSpawnCyclesConfiguredHarnesses,
		TestHubModelCodexSpawnSurvivesModelListFailure,
		TestHubModelCodexSpawnOpensHarnessModelPicker,
		TestHubModelSpawnRejectsHubUnsupportedEmptyTaskBeforeStart,
		TestHubModelSpawnDefaultsToEnabledModelWhenAuthRequired,
		TestHubModelDashboardSpawnOpensFormBeforePosting,
		TestHubModelDashboardSpawnEditsWorkingDirBeforePosting,
		TestHubModelSpawnDirectoryTabCompletesPath,
		TestHubModelSpawnPromptAcceptsHarnessAndModelLetters,
		TestHubModelSpawnFormFocusControlsHarnessAndModel,
		TestHubDashboardSpawnWaitsForSlowHubSpawn,
		TestHubModelNotificationClosedIsNotError,
		TestHubModelStatusIdleRefreshesSessionCapabilities,
		TestHubModelStatusProcessingRefreshesSessionCapabilities,
		TestHubModelStatusRefreshIgnoresStaleSessionRead,
		TestStatusRefreshStatesMatchExpectedRequiresCurrentAndPayload,
		TestHubModelSendUsesAppWireTurnStart,
		TestHubModelBusySendPreservesInput,
		TestHubModelTasksAndDetailsUseAppWire,
		TestHubModelSameSessionRefreshReplacesTranscript,
		TestHubModelExpectedStatusRefreshDoesNotReplaceTranscript,
		TestFetchHubSessionSubscribesToLiveThread,
		TestFetchHubSessionStatusRefreshDoesNotReplaceLiveSubscription,
		TestHubModelStatusUsesHubThreadTasksAndAuth,
		TestHubModelSessionPanelRendersAsCenteredModalOverlay,
		TestHubModelSessionPanelBoundsLongTranscriptToVisibleShell,
		TestHubModelActionsAndClearUseAppWire,
		TestHubModelDirectModelCommandSplitsProviderQualifiedModel,
		TestHubModelSessionModelPickerUsesHubModels,
		TestHubModelSessionModelPickerDisablesAuthRequiredModels,
		TestHubModelSessionModelPickerRequiresCapability,
		TestHubModelThemePicker,
		TestHubModelThemePickerPersistsStateDirPreference,
		TestHubModelTurnStartEnablesTurnActions,
		TestHubModelIgnoresAsyncCompletionForDifferentSession,
		TestHubModelSendErrorRemovesOptimisticUserEcho,
		TestHubModelBrowseForkDraftPostsForkAndNavigatesToChild,
		TestHubModelBrowseForkRequiresUserTurnWithTurnIndex,
		TestHubModelBrowseForkRequiresSelectedUserMessage,
		TestHubModelForkFailurePreservesDraftAndLabel,
		TestHubModelDashboardShowsRecentWhenNothingLive,
		TestHubModelDashboardCanExpandRecentOnlyProject,
		TestHubModelActionBarsUseApprovedNewSessionKey,
		TestHubModelSpawnFormDoesNotAdvertiseOrAcceptCtrlS,
		TestHubModelSessionFooterShowsBrowseAndDashboardKeys,
		TestHubModelForkCommandEntersBrowseMode,
		TestHubModelHelpRespectsSessionCapabilities,
		TestHubModelHelpAndPaletteShareSessionCommands,
		TestHubModelUpgradeSlashCommandCallsHub,
		TestHubModelSessionCommandPaletteDoesNotShowOtherSessions,
		TestHubModelSessionPaletteShowsDisabledCommandReasons,
		TestHubModelDashboardPaletteCanSearchOtherSessions,
		TestHubModelDashboardOnlyCommandIsNotASessionCommand,
		TestHubModelSessionPaletteShortcutDoesNotExposeCrossSessionSearch,
		TestHubModelSessionLeadingSlashOpensCommandPalette,
		TestHubModelCtrlCQuitsWithoutInAppWarningFromSession,
		TestHubModelSecondCtrlCStoresPostQuitRestoreMessage,
		TestHubModelCtrlCWarningExpires,
		TestHubModelFirstCtrlCInterruptsActiveTurn,
		TestHubModelFirstCtrlCWithoutInterruptCapabilityDoesNotDispatch,
		TestHubModelCtrlCQuitsOutsideSessionButArmsQuitInSession,
		TestHubModelUnrecognizedSlashCommandForwardsToSession,
		TestHubModelUnrecognizedSlashCommandForwardsExactText,
		TestHubModelUnrecognizedSlashCommandForwardsExactText_NoArgs,
		TestHubDetailFromThreadIncludesActiveTurnID,
		TestHubModelIgnoresNotificationsForOtherSessions,
		TestHubModelIgnoresPendingCoordinatorMessagesForOtherSessions,
		TestUserMessageGetsAccentBar,
		TestAssistantMessageGetsStateBar,
		TestScrollBrowseFocusedTurnHasDoubleBar,
		TestForkDraftHasSectionDivider,
		TestTopmostOverlayNameEmpty,
		TestTopmostOverlayNameCredentials,
		TestTopmostOverlayNamePlugins,
		TestTopmostOverlayNameFollowupTakesPrecedence,
		TestKeyAllowedThroughTrap_Esc,
		TestKeyAllowedThroughTrap_CtrlO,
		TestKeyAllowedThroughTrap_CtrlP_Rejected,
		TestCmdPRejectedWhenCredentialsOpen,
		TestEscClosesTopmostOverlayOnly,
		TestCtrlOEscapesAllOverlays,
		TestSlashRejectedWhenCredentialsOpen,
		TestEscClosesPluginsOverlay,
		TestCtrlOEscapesPluginsOverlay,
		TestCmdPRejectedWhenPluginsOpen,
	}
	f.Add(0)
	f.Add(1)
	f.Add(2)
	f.Add(3)
	f.Add(4)
	f.Add(5)
	f.Add(6)
	f.Add(7)
	f.Add(8)
	f.Add(9)
	f.Add(10)
	f.Add(11)
	f.Add(12)
	f.Add(13)
	f.Add(14)
	f.Add(15)
	f.Add(16)
	f.Add(17)
	f.Add(18)
	f.Add(19)
	f.Add(20)
	f.Add(21)
	f.Add(22)
	f.Add(23)
	f.Add(24)
	f.Add(25)
	f.Add(26)
	f.Add(27)
	f.Add(28)
	f.Add(29)
	f.Add(30)
	f.Add(31)
	f.Add(32)
	f.Add(33)
	f.Add(34)
	f.Add(35)
	f.Add(36)
	f.Add(37)
	f.Add(38)
	f.Add(39)
	f.Add(40)
	f.Add(41)
	f.Add(42)
	f.Add(43)
	f.Add(44)
	f.Add(45)
	f.Add(46)
	f.Add(47)
	f.Add(48)
	f.Add(49)
	f.Add(50)
	f.Add(51)
	f.Add(52)
	f.Add(53)
	f.Add(54)
	f.Add(55)
	f.Add(56)
	f.Add(57)
	f.Add(58)
	f.Add(59)
	f.Add(60)
	f.Add(61)
	f.Add(62)
	f.Add(63)
	f.Add(64)
	f.Add(65)
	f.Add(66)
	f.Add(67)
	f.Add(68)
	f.Add(69)
	f.Add(70)
	f.Add(71)
	f.Add(72)
	f.Add(73)
	f.Add(74)
	f.Add(75)
	f.Add(76)
	f.Add(77)
	f.Add(78)
	f.Add(79)
	f.Add(80)
	f.Add(81)
	f.Add(82)
	f.Add(83)
	f.Add(84)
	f.Add(85)
	f.Add(86)
	f.Add(87)
	f.Add(88)
	f.Add(89)
	f.Add(90)
	f.Add(91)
	f.Add(92)
	f.Add(93)
	f.Add(94)
	f.Add(95)
	f.Add(96)
	f.Add(97)
	f.Add(98)
	f.Add(99)
	f.Add(100)
	f.Add(101)
	f.Add(102)
	f.Add(103)
	f.Add(104)
	f.Add(105)
	f.Add(106)
	f.Add(107)
	f.Add(108)
	f.Add(109)
	f.Add(110)
	f.Add(111)
	f.Add(112)
	f.Add(113)
	f.Add(114)
	f.Add(115)
	f.Add(116)
	f.Add(117)
	f.Add(118)
	f.Add(119)
	f.Add(120)
	f.Add(121)
	f.Add(122)
	f.Add(123)
	f.Add(124)
	f.Add(125)
	f.Add(126)
	f.Add(127)
	f.Add(128)
	f.Add(129)
	f.Add(130)
	f.Add(131)
	f.Add(132)
	f.Add(133)
	f.Add(134)
	f.Add(135)
	f.Add(136)
	f.Add(137)
	f.Add(138)
	f.Add(139)
	f.Add(140)
	f.Add(141)
	f.Add(142)
	f.Add(143)
	f.Add(144)
	f.Add(145)
	f.Add(146)
	f.Add(147)
	f.Add(148)
	f.Add(149)
	f.Add(150)
	f.Add(151)
	f.Add(152)
	f.Add(153)
	f.Add(154)
	f.Add(155)
	f.Add(156)
	f.Add(157)
	f.Add(158)
	f.Add(159)
	f.Add(160)
	f.Add(161)
	f.Add(162)
	f.Add(163)
	f.Add(164)
	f.Add(165)
	f.Add(166)
	f.Add(167)
	f.Add(168)
	f.Add(169)
	f.Add(170)
	f.Add(171)
	f.Add(172)
	f.Add(173)
	f.Add(174)
	f.Add(175)
	f.Add(176)
	f.Add(177)
	f.Add(178)
	f.Add(179)
	f.Add(180)
	f.Add(181)
	f.Add(182)
	f.Add(183)
	f.Add(184)
	f.Add(185)
	f.Add(186)
	f.Add(187)
	f.Add(188)
	f.Add(189)
	f.Add(190)
	f.Add(191)
	f.Add(192)
	f.Add(193)
	f.Add(194)
	f.Add(195)
	f.Add(196)
	f.Add(197)
	f.Add(198)
	f.Add(199)
	f.Add(200)
	f.Add(201)
	f.Add(202)
	f.Add(203)
	f.Add(204)
	f.Add(205)
	f.Add(206)
	f.Add(207)
	f.Add(208)
	f.Add(209)
	f.Add(210)
	f.Add(211)
	f.Add(212)
	f.Add(213)
	f.Add(214)
	f.Add(215)
	f.Add(216)
	f.Add(217)
	f.Add(218)
	f.Add(219)
	f.Add(220)
	f.Add(221)
	f.Add(222)
	f.Add(223)
	f.Add(224)
	f.Add(225)
	f.Add(226)
	f.Add(227)
	f.Add(228)
	f.Add(229)
	f.Add(230)
	f.Add(231)
	f.Add(232)
	f.Add(233)
	f.Add(234)
	f.Add(235)
	f.Add(236)
	f.Add(237)
	f.Add(238)
	f.Add(239)
	f.Add(240)
	f.Add(241)
	f.Add(242)
	f.Add(243)
	f.Add(244)
	f.Add(245)
	f.Add(246)
	f.Add(247)
	f.Add(248)
	f.Add(249)
	f.Add(250)
	f.Add(251)
	f.Add(252)
	f.Add(253)
	f.Add(254)
	f.Add(255)
	f.Add(256)
	f.Add(257)
	f.Add(258)
	f.Add(259)
	f.Add(260)
	f.Add(261)
	f.Add(262)
	f.Add(263)
	f.Add(264)
	f.Add(265)
	f.Add(266)
	f.Add(267)
	f.Add(268)
	f.Add(269)
	f.Add(270)
	f.Add(271)
	f.Add(272)
	f.Add(273)
	f.Add(274)
	f.Add(275)
	f.Add(276)
	f.Add(277)
	f.Add(278)
	f.Add(279)
	f.Add(280)
	f.Add(281)
	f.Add(282)
	f.Add(283)
	f.Add(284)
	f.Add(285)
	f.Add(286)
	f.Add(287)
	f.Add(288)
	f.Add(289)
	f.Add(290)
	f.Add(291)
	f.Add(292)
	f.Add(293)
	f.Add(294)
	f.Add(295)
	f.Add(296)
	f.Add(297)
	f.Add(298)
	f.Add(299)
	f.Add(300)
	f.Add(301)
	f.Add(302)
	f.Add(303)
	f.Add(304)
	f.Add(305)
	f.Add(306)
	f.Add(307)
	f.Add(308)
	f.Add(309)
	f.Add(310)
	f.Add(311)
	f.Add(312)
	f.Add(313)
	f.Add(314)
	f.Add(315)
	f.Add(316)
	f.Add(317)
	f.Add(318)
	f.Add(319)
	f.Add(320)
	f.Add(321)
	f.Add(322)
	f.Add(323)
	f.Add(324)
	f.Add(325)
	f.Add(326)
	f.Add(327)
	f.Add(328)
	f.Add(329)
	f.Add(330)
	f.Add(331)
	f.Add(332)
	f.Add(333)
	f.Add(334)
	f.Add(335)
	f.Add(336)
	f.Add(337)
	f.Add(338)
	f.Add(339)
	f.Add(340)
	f.Add(341)
	f.Add(342)
	f.Add(343)
	f.Add(344)
	f.Add(345)
	f.Add(346)
	f.Add(347)
	f.Add(348)
	f.Add(349)
	f.Add(350)
	f.Add(351)
	f.Add(352)
	f.Add(353)
	f.Add(354)
	f.Add(355)
	f.Add(356)
	f.Add(357)
	f.Add(358)
	f.Add(359)
	f.Add(360)
	f.Add(361)
	f.Add(362)
	f.Add(363)
	f.Add(364)
	f.Add(365)
	f.Add(366)
	f.Add(367)
	f.Add(368)
	f.Add(369)
	f.Add(370)
	f.Add(371)
	f.Add(372)
	f.Add(373)
	f.Add(374)
	f.Add(375)
	f.Add(376)
	f.Add(377)
	f.Add(378)
	f.Add(379)
	f.Add(380)
	f.Add(381)
	f.Add(382)
	f.Add(383)
	f.Add(384)
	f.Add(385)
	f.Add(386)
	f.Add(387)
	f.Add(388)
	f.Add(389)
	f.Add(390)
	f.Add(391)
	f.Fuzz(func(t *testing.T, program int) {
		if program < 0 {
			program = -(program + 1)
		}
		programs[program%len(programs)](t)
	})
}
