package promoter

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// goTestTemplate renders a deterministic regression test that replays a
// minimized artifact against the failing seam and asserts the bug is fixed. The
// ReplayBody is adapter-provided (it decodes the artifact, drives the seam, and
// asserts no-panic / invariant-holds / clean-error). The provenance trailer in
// the header comment makes the generated diff human-reviewable.
var goTestTemplate = template.Must(template.New("goregression").Parse(
	`// Code generated by fuzz/promoter from a fuzzing failure. DO NOT EDIT by hand.
// Surface: {{.Surface}}  Oracle: {{.Oracle}}  Signature: {{.Signature}}
{{- if .Seam}}
// Seam: {{.Seam}}{{end}}
package {{.Package}}

import "testing"

func {{.FuncName}}(t *testing.T) {
{{.ReplayBody}}
}
`))

// GoTest is the input to the Go regression-test emitter.
type GoTest struct {
	// Package is the package clause for the emitted file (the surface's package).
	Package string
	// Surface and Oracle name the failure; they appear in the test name and the
	// provenance comment.
	Surface string
	Oracle  OracleTag
	// Signature is the short bucket id for the provenance comment.
	Signature string
	// Seam optionally names the seam under test for the provenance comment.
	Seam string
	// Hash uniquifies the test name; if empty it is derived from the failure.
	Hash string
	// ReplayBody is the adapter-rendered test body (already indented as desired).
	ReplayBody string
}

// FuncName is the deterministic regression-test function name.
func (g GoTest) FuncName() string {
	return fmt.Sprintf("TestRegression_%s_%s_%s",
		sanitizeIdent(g.Surface), sanitizeIdent(string(g.Oracle)), g.Hash)
}

// RenderGoTest renders (and gofmt-formats) the regression test source.
func RenderGoTest(g GoTest) ([]byte, error) {
	if g.Package == "" {
		return nil, errors.New("RenderGoTest: empty package")
	}
	if g.Hash == "" {
		return nil, errors.New("RenderGoTest: empty hash")
	}
	var buf bytes.Buffer
	if err := goTestTemplate.Execute(&buf, g); err != nil {
		return nil, fmt.Errorf("render go test: %w", err)
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt generated test (body likely malformed): %w", err)
	}
	return formatted, nil
}

// WriteGoTest renders the regression test and writes it under dir, returning the
// path written. The filename is derived from the deterministic function name.
func WriteGoTest(dir string, g GoTest) (string, error) {
	src, err := RenderGoTest(g)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", fmt.Errorf("create output dir: %w", err)
	}
	path := filepath.Join(dir, strings.ToLower(g.FuncName())+"_test.go")
	if err := os.WriteFile(path, src, 0o644); err != nil {
		return "", fmt.Errorf("write regression test: %w", err)
	}
	return path, nil
}

// ShortHash derives a stable short hash from a failure's artifact and detail,
// for use as GoTest.Hash and as a Signature key component.
func ShortHash(f Failure) string {
	h := sha256.New()
	h.Write([]byte(f.Surface))
	h.Write([]byte{0})
	h.Write([]byte(f.Detail))
	h.Write([]byte{0})
	h.Write(f.Artifact)
	return hex.EncodeToString(h.Sum(nil))[:12]
}

// sanitizeIdent makes s safe to embed in a Go identifier: non-alphanumeric runes
// become underscores. An empty or leading-digit result is prefixed with "x".
func sanitizeIdent(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	out := b.String()
	if out == "" || (out[0] >= '0' && out[0] <= '9') {
		out = "x" + out
	}
	return out
}
