// Controller-owned barrel: streams building later widget batches (T2-T4)
// report their exports for the controller to add here at merge time; they
// do not edit this file directly. See docs/superpowers/plans/
// 2026-07-20-webui-rewrite-wave2-design-system.md, "Locked widget APIs".

export type { BadgeProps, BadgeTone } from "./badge";
export { Badge } from "./badge";
export type { ButtonProps, ButtonSize, ButtonVariant } from "./button";
export { Button } from "./button";
export type { CadenceProps, CadenceState } from "./cadence";
export { Cadence } from "./cadence";
export type { CardProps } from "./card";
export { Card } from "./card";
export type { ChipProps, ChipTone } from "./chip";
export { Chip } from "./chip";
export type { CodeBlockProps } from "./codeblock";
export { CodeBlock } from "./codeblock";
export type { CollectionAddResult, CollectionEditorProps } from "./collectioneditor";
export { CollectionEditor } from "./collectioneditor";
export type { ComboboxOption, ComboboxProps } from "./combobox";
export { Combobox } from "./combobox";
export type { ConfirmDialogProps } from "./confirmdialog";
export { ConfirmDialog } from "./confirmdialog";
export type { DialogProps } from "./dialog";
export { Dialog } from "./dialog";
export type { DiffBlockProps } from "./diffblock";
export { DiffBlock } from "./diffblock";
export type { EmptyStateProps } from "./emptystate";
export { EmptyState } from "./emptystate";
export type { FocusScopeProps } from "./focusscope";
// --- overlays batch (W2T3) ---
export { FocusScope } from "./focusscope";
export type { FormRowProps } from "./formrow";
export { FormRow } from "./formrow";
export type { IconButtonProps } from "./iconbutton";
// --- primitives batch (W2T2) ---
export { IconButton } from "./iconbutton";
export type { InputProps } from "./input";
export { Input } from "./input";
export type { KeyHintProps } from "./keyhint";
export { KeyHint } from "./keyhint";
export type { MarkdownProps } from "./markdown";
export { Markdown } from "./markdown";
export type { MenuItem, MenuProps } from "./menu";
export { Menu } from "./menu";
export type { MeterProps, MeterTone } from "./meter";
export { Meter } from "./meter";
export type { PaneScaffoldProps } from "./panescaffold";
// --- data batch (W2T4) ---
export { PaneScaffold } from "./panescaffold";
export type { PathPickerProps } from "./pathpicker";
export { PathPicker } from "./pathpicker";
export type { RadioGroupOption, RadioGroupProps } from "./radiogroup";
export { RadioGroup } from "./radiogroup";
export type { SelectOption, SelectProps } from "./select";
export { Select } from "./select";
export type { SheetProps, SheetSide } from "./sheet";
export { Sheet } from "./sheet";
export type { SkeletonProps } from "./skeleton";
export { Skeleton } from "./skeleton";
export type { StatusDotProps } from "./statusdot";
export { StatusDot } from "./statusdot";
export type { SwitchProps } from "./switch";
export { Switch } from "./switch";
export type { TextareaProps } from "./textarea";
export { Textarea } from "./textarea";
export type { ToastKind } from "./toast";
export { Toast, useToasts } from "./toast";
export type { TooltipProps } from "./tooltip";
export { Tooltip } from "./tooltip";
export type { TreeNode, TreeProps, TreeRowInfo } from "./tree";
export { Tree } from "./tree";
export type { VirtualListHandle, VirtualListProps } from "./virtuallist";
export { VirtualList } from "./virtuallist";
