// Controller-owned barrel: streams building later widget batches (T2-T4)
// report their exports for the controller to add here at merge time; they
// do not edit this file directly. See docs/superpowers/plans/
// 2026-07-20-webui-rewrite-wave2-design-system.md, "Locked widget APIs".

export { Button } from "./button";
export type { ButtonProps, ButtonVariant, ButtonSize } from "./button";

export { Cadence } from "./cadence";
export type { CadenceProps, CadenceState } from "./cadence";

// --- primitives batch (W2T2) ---
export { IconButton } from "./iconbutton";
export type { IconButtonProps } from "./iconbutton";
export { Chip } from "./chip";
export type { ChipProps, ChipTone } from "./chip";
export { Badge } from "./badge";
export type { BadgeProps, BadgeTone } from "./badge";
export { StatusDot } from "./statusdot";
export type { StatusDotProps } from "./statusdot";
export { Input } from "./input";
export type { InputProps } from "./input";
export { Textarea } from "./textarea";
export type { TextareaProps } from "./textarea";
export { Select } from "./select";
export type { SelectProps, SelectOption } from "./select";
export { Switch } from "./switch";
export type { SwitchProps } from "./switch";
export { KeyHint } from "./keyhint";
export type { KeyHintProps } from "./keyhint";
export { Meter } from "./meter";
export type { MeterProps, MeterTone } from "./meter";
export { Skeleton } from "./skeleton";
export type { SkeletonProps } from "./skeleton";
export { EmptyState } from "./emptystate";
export type { EmptyStateProps } from "./emptystate";
export { Card } from "./card";
export type { CardProps } from "./card";

// --- overlays batch (W2T3) ---
export { FocusScope } from "./focusscope";
export type { FocusScopeProps } from "./focusscope";
export { Dialog } from "./dialog";
export type { DialogProps } from "./dialog";
export { Sheet } from "./sheet";
export type { SheetProps, SheetSide } from "./sheet";
export { Menu } from "./menu";
export type { MenuProps, MenuItem } from "./menu";
export { Tooltip } from "./tooltip";
export type { TooltipProps } from "./tooltip";
export { Toast, useToasts } from "./toast";
export type { ToastKind } from "./toast";
export { Combobox } from "./combobox";
export type { ComboboxProps, ComboboxOption } from "./combobox";
