import { METHOD_NAMES, NOTIFICATION_NAMES } from "@evener/appwire-client";

// A listed recipe exercises these requests; this is not branch/outcome coverage.
const recipes = {
  "hub-setup.mjs": ["initialize", "evener/dirs/create", "evener/mobile/pairing"],
  "saved-items.mjs": [
    "initialize",
    "evener/favorite/set",
    "evener/archive/set",
    "evener/project/delete",
    "evener/session/delete",
  ],
  "session-lineage.mjs": [
    "initialize",
    "thread/read",
    "thread/resume",
    "thread/fork",
    "evener/thread/transcripts/list",
    "evener/subagentPreview",
  ],
  "maintenance-checks.mjs": ["initialize", "ping", "evener/auth/test", "evener/plugin/checkNow"],
  "hub-upgrade.mjs": ["initialize", "evener/settings/overview", "evener/upgrade"],
  "navigation-invalidation.mjs": ["initialize", "evener/navigation/read"],
  "session-notifications.mjs": ["initialize", "thread/read", "thread/unsubscribe"],
  "work-notifications.mjs": [
    "initialize",
    "thread/read",
    "evener/tasks/list",
    "evener/jobs/list",
    "thread/unsubscribe",
  ],
  "streaming-notifications.mjs": ["initialize", "thread/read", "thread/unsubscribe"],
  "hub-notifications.mjs": [
    "initialize",
    "evener/auth/list",
    "evener/marketplace/list",
    "evener/plugin/list",
    "evener/settings/transcriptDisplay/get",
    "evener/settings/keybindings/get",
    "evener/navigation/read",
    "thread/read",
    "thread/unsubscribe",
  ],
  "oauth.mjs": [
    "initialize",
    "evener/auth/status",
    "evener/auth/device/start",
    "evener/auth/device/poll",
    "evener/auth/login/start",
    "evener/auth/login/complete",
  ],
  "credentials.mjs": [
    "initialize",
    "evener/auth/list",
    "evener/auth/status",
    "evener/auth/apiKey/set",
    "evener/auth/apiKey/clear",
    "evener/auth/credentialJson/set",
    "evener/auth/logout",
  ],
  "discovery.mjs": [
    "initialize",
    "evener/paths/complete",
    "evener/projects/recent",
    "evener/path/validate",
    "evener/git/head",
    "evener/search",
    "evener/harnesses/list",
    "evener/settings/overview",
  ],
  "session-management.mjs": [
    "initialize",
    "thread/read",
    "evener/thread/name/set",
    "thread/clear",
    "thread/compact/start",
    "thread/shutdown",
  ],
  "commands.mjs": ["initialize", "evener/command/list"],
  "session-settings.mjs": [
    "initialize",
    "thread/read",
    "thread/model/set",
    "thread/reasoning-effort/set",
    "thread/vision-model/set",
  ],
  "preferences.mjs": [
    "initialize",
    "evener/settings/keybindings/get",
    "evener/settings/keybindings/patch",
    "evener/settings/transcriptDisplay/get",
    "evener/settings/transcriptDisplay/patch",
  ],
  "session-lifecycle.mjs": [
    "initialize",
    "model/list",
    "thread/start",
    "thread/read",
    "turn/start",
    "turn/interrupt",
    "thread/unsubscribe",
  ],
  "streaming-rejoin.mjs": ["initialize", "thread/read", "thread/turns/list", "thread/unsubscribe"],
  "organization.mjs": [
    "initialize",
    "evener/navigation/read",
    "evener/session-pin/assign",
    "evener/session-pin/unpin",
    "evener/pin-section/rename",
    "evener/pin-section/delete",
  ],
  "plugins.mjs": ["initialize", "evener/plugin/preview"],
  "plugin-management.mjs": [
    "initialize",
    "evener/plugin/list",
    "evener/plugin/install",
    "evener/plugin/upgrade",
    "evener/plugin/remove",
    "evener/plugin/enable",
    "evener/plugin/disable",
    "evener/plugin/setAutoUpgrade",
  ],
  "instances.mjs": [
    "initialize",
    "evener/instance/list",
    "evener/instance/create",
    "evener/instance/edit",
    "evener/instance/remove",
    "evener/instance/setDefault",
  ],
  "marketplaces.mjs": [
    "initialize",
    "evener/marketplace/list",
    "evener/marketplace/browse",
    "evener/marketplace/add",
    "evener/marketplace/remove",
    "evener/marketplace/refresh",
  ],
  "approvals.mjs": ["initialize", "thread/read", "evener/sandbox/escalation/resolve"],
  "questions.mjs": ["initialize", "thread/read", "thread/turns/list", "turn/start"],
  "goals.mjs": ["initialize", "thread/read", "goal/set"],
  "tasks.mjs": ["initialize", "evener/tasks/list"],
  "job-output.mjs": ["initialize", "evener/jobs/output"],
  "activity.mjs": ["initialize", "evener/jobs/list"],
  "queue.mjs": [
    "initialize",
    "thread/read",
    "turn/steer",
    "turn/queue",
    "turn/cancelQueued",
    "turn/promoteQueuedAsSteer",
    "turn/drainAsSteer",
  ],
  "repository-trust.mjs": ["initialize", "evener/launch/resolve", "evener/launch/trustRepo"],
  "project-layer.mjs": [
    "initialize",
    "evener/launch/schema",
    "evener/launch/getLayer",
    "evener/launch/setLayer",
    "evener/launch/resolve",
  ],
  "inspect.mjs": ["initialize", "model/list", "thread/list", "evener/launch/schema", "evener/launch/resolve"],
  "thread-force-stop.mjs": ["initialize", "evener/thread/forceStop"],
  "update.mjs": ["initialize", "evener/update/check", "evener/update/apply"],
  "agents-doc.mjs": ["initialize", "evener/settings/agentsDoc/get", "evener/settings/agentsDoc/set"],
  "agents-doc-notifications.mjs": ["initialize", "evener/settings/agentsDoc/get"],
};
const coveredNotifications = [
  "evener/launch/updated",
  "turn/started",
  "turn/completed",
  "item/started",
  "item/completed",
  "item/agentMessage/delta",
  "item/agentMessage/reset",
  "evener/thread/resync",
  "evener/navigation/invalidated",
  "thread/started",
  "thread/closed",
  "thread/status/changed",
  "thread/queueChanged",
  "evener/thread/name/changed",
  "thread/model/changed",
  "thread/reasoning-effort/changed",
  "thread/vision-model/changed",
  "evener/job/started",
  "evener/job/finished",
  "evener/delegate/updated",
  "evener/jobs/treeUpdated",
  "evener/task/updated",
  "evener/goal/updated",
  "evener/auth/updated",
  "evener/attention/changed",
  "evener/marketplace/updated",
  "evener/plugin/updated",
  "evener/sandbox/escalation/requested",
  "evener/sandbox/escalation/resolved",
  "evener/settings/transcriptDisplay/changed",
  "evener/settings/keybindings/changed",
  "item/reasoning/summaryTextDelta",
  "item/toolOutput/delta",
  "warning",
  "evener/thread/modelRetry",
  "evener/steering/injected",
  "evener/settings/agentsDoc/changed",
];
const covered = new Set(Object.values(recipes).flat());
for (const method of covered) {
  if (!METHOD_NAMES.includes(method)) throw new Error(`Unknown recipe method: ${method}`);
}
console.log(
  JSON.stringify(
    {
      recipes,
      coveredMethods: covered.size,
      catalogMethods: METHOD_NAMES.length,
      missingMethods: METHOD_NAMES.filter((method) => !covered.has(method)),
      missingNotifications: NOTIFICATION_NAMES.filter((name) => !coveredNotifications.includes(name)),
      coveredNotifications,
      note: "Catalog includes reserved methods; classify support and expected rejection when adding recipes. Notification coverage records names handled by bounded recipes; it does not claim continuous reducer, ordering, outcome, or replay coverage.",
    },
    null,
    2,
  ),
);
