// Bundles the native mermaid WebView page: mermaid + DOMPurify + the bootstrap
// in src/mermaidPageContent.ts into a single self-contained HTML string,
// committed as src/generated/mermaidPage.ts. Regenerate after any change to the
// bootstrap or the mermaid/DOMPurify versions:
//   npx tsx scripts/build-mermaid-page.mts
// Print the HTML without writing it (the freshness test's fallback path):
//   npx tsx scripts/build-mermaid-page.mts --stdout
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { build } from "esbuild";
// The one source for the forbid list: the web frontend's forbidTags leaf owns
// it, and this generator substitutes it into the native page bundle so the two
// frontends cannot drift. The leaf has no imports, so this resolves under the
// native job's own install (no frontend node_modules needed); imported as TS
// (this script runs under tsx), while the emitted page stays a plain inlined
// bundle.
import { MERMAID_FORBID_TAGS } from "../../cmd/evener-hub/frontend/src/widgets/mermaid/forbidTags";

const nativeRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const GENERATED_FILE = path.join(nativeRoot, "src", "generated", "mermaidPage.ts");
const GENERATED_HEADER =
	"// GENERATED by scripts/build-mermaid-page.mts - do not edit (regenerate: npx tsx scripts/build-mermaid-page.mts)\n";

// Nothing may load: the bundle is inlined, and the page fetches no resources.
const CSP = "default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'";

// Evaluated inside the bundle. The bootstrap module carries its own `import
// mermaid` / `import DOMPurify`, which esbuild follows and inlines here.
const ENTRY = 'import { bootstrapMermaidPage } from "./src/mermaidPageContent.ts";\nbootstrapMermaidPage();\n';

function renderHtml(bundle: string): string {
	return [
		"<!doctype html>",
		'<html lang="en">',
		"<head>",
		'<meta charset="utf-8">',
		'<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">',
		`<meta http-equiv="Content-Security-Policy" content="${CSP}">`,
		"<style>html,body{margin:0;padding:0;background:transparent}#mermaid-container{display:block}</style>",
		"</head>",
		"<body>",
		'<div id="mermaid-container"></div>',
		`<script>${bundle}</script>`,
		"</body>",
		"</html>",
	].join("\n");
}

export async function buildMermaidPageHtml(): Promise<string> {
	const result = await build({
		stdin: {
			contents: ENTRY,
			resolveDir: nativeRoot,
			sourcefile: "mermaid-page-entry.ts",
			loader: "ts",
		},
		bundle: true,
		format: "iife",
		platform: "browser",
		target: "es2020",
		write: false,
		minify: true,
		// "eof" keeps mermaid's and DOMPurify's MIT license headers in the shipped
		// bundle: "none" would strip them, and the MIT terms require retaining them.
		legalComments: "eof",
		charset: "utf8",
		// mermaidPageContent.ts declares MERMAID_FORBID_TAGS; esbuild substitutes
		// the web module's current list here, so the page carries no copy of it.
		define: { MERMAID_FORBID_TAGS: JSON.stringify(MERMAID_FORBID_TAGS) },
	});
	const [output] = result.outputFiles ?? [];
	if (!output) throw new Error("esbuild produced no bundle for the mermaid page");
	return renderHtml(output.text);
}

export function generatedModule(html: string): string {
	// JSON.stringify keeps the huge inlined bundle safe from template-literal
	// escaping; the result is still a plain string literal TypeScript module.
	return `${GENERATED_HEADER}export const MERMAID_PAGE_HTML = ${JSON.stringify(html)};\n`;
}

async function main(): Promise<void> {
	const html = await buildMermaidPageHtml();
	if (process.argv.includes("--stdout")) {
		process.stdout.write(html);
		return;
	}
	mkdirSync(path.dirname(GENERATED_FILE), { recursive: true });
	writeFileSync(GENERATED_FILE, generatedModule(html));
	process.stdout.write(`wrote ${path.relative(nativeRoot, GENERATED_FILE)}\n`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
	await main();
}
