//go:build serffuzz

package plugins

import "testing"

// FuzzPackageUnion replays every deterministic package scenario under fuzz coverage.

func FuzzPackageUnion(f *testing.F) {

	f.Add(uint8(0))

	f.Fuzz(func(t *testing.T, _ uint8) {

		t.Run("TestComputeVersion", TestComputeVersion)
		t.Run("TestValidatePluginDir", TestValidatePluginDir)
		t.Run("TestAcquireLock_ExclusiveWithTimeout", TestAcquireLock_ExclusiveWithTimeout)
		t.Run("TestUpgrade_NewShaDirOldRemains", TestUpgrade_NewShaDirOldRemains)
		t.Run("TestUpgrade_NoOpKeepsLiveDir", TestUpgrade_NoOpKeepsLiveDir)
		t.Run("TestUpgrade_ManifestLessPlugin_FallbackAppliedToNewShaDir", TestUpgrade_ManifestLessPlugin_FallbackAppliedToNewShaDir)
		t.Run("TestSource_UnmarshalObjectForms", TestSource_UnmarshalObjectForms)
		t.Run("TestSource_UnmarshalStringForm", TestSource_UnmarshalStringForm)
		t.Run("TestSource_MarshalNeverWritesGit", TestSource_MarshalNeverWritesGit)
		t.Run("TestSource_UnmarshalRejectsUnknownKind", TestSource_UnmarshalRejectsUnknownKind)
		t.Run("TestSource_RelSurvivesRoundTrip", TestSource_RelSurvivesRoundTrip)
		t.Run("TestList_FlagsBroken", TestList_FlagsBroken)
		t.Run("TestUpdateAll_UpgradesGitBackedSkipsRelative", TestUpdateAll_UpgradesGitBackedSkipsRelative)
		t.Run("TestUpdateAll_SkipsEmptyEntry", TestUpdateAll_SkipsEmptyEntry)
		t.Run("TestRemoveEnableDisable", TestRemoveEnableDisable)
		t.Run("TestRemove_DirectorySourceKeepsContents", TestRemove_DirectorySourceKeepsContents)
		t.Run("TestFetchPluginSource_RelativeCopiesFromMarketplace", TestFetchPluginSource_RelativeCopiesFromMarketplace)
		t.Run("TestInstall_MaterializesAndRegisters", TestInstall_MaterializesAndRegisters)
		t.Run("TestInstall_LazyFetchesSeededPointer", TestInstall_LazyFetchesSeededPointer)
		t.Run("TestInstall_FromGitSubdirMarketplace", TestInstall_FromGitSubdirMarketplace)
		t.Run("TestInstall_ManifestLessPlugin_MCPServerRegisters", TestInstall_ManifestLessPlugin_MCPServerRegisters)
		t.Run("TestInstall_ManifestLessPlugin_NoUsableFields_Installs", TestInstall_ManifestLessPlugin_NoUsableFields_Installs)
		t.Run("TestInstall_BareNPMRepo_AutoWiresMCP", TestInstall_BareNPMRepo_AutoWiresMCP)
		t.Run("TestInstall_BareNPMRepo_UnbuiltBin_NotePersisted", TestInstall_BareNPMRepo_UnbuiltBin_NotePersisted)
		t.Run("TestInstall_PluginWithOwnManifest_EntryIgnored", TestInstall_PluginWithOwnManifest_EntryIgnored)
		t.Run("TestGitClone_CopiesRepoAtSha", TestGitClone_CopiesRepoAtSha)
		t.Run("TestGitClone_RejectsFlagLikeArgs", TestGitClone_RejectsFlagLikeArgs)
		t.Run("TestFetchPluginSource_RejectsExtTransport", TestFetchPluginSource_RejectsExtTransport)
		t.Run("TestGc_NoCacheDirYet", TestGc_NoCacheDirYet)
		t.Run("TestGc_RemovesOrphanedKeepsReferenced", TestGc_RemovesOrphanedKeepsReferenced)
		t.Run("TestGc_DirectorySourceInstallPathNeverConsidered", TestGc_DirectorySourceInstallPathNeverConsidered)
		t.Run("TestSeedDefaultMarketplaces_FirstRunOnly", TestSeedDefaultMarketplaces_FirstRunOnly)
		t.Run("TestBrowse_LazyFetchesSeededPointer", TestBrowse_LazyFetchesSeededPointer)
		t.Run("TestEnabledPluginDirs_FiltersDisabledAndBroken", TestEnabledPluginDirs_FiltersDisabledAndBroken)
		t.Run("TestEnabledPluginDirs_ExplicitFirstAndDeduped", TestEnabledPluginDirs_ExplicitFirstAndDeduped)
		t.Run("TestEnabledPluginDirs_WarnsOnDuplicateExplicit", TestEnabledPluginDirs_WarnsOnDuplicateExplicit)
		t.Run("TestDefaultRoot_UsesXDGConfigHome", TestDefaultRoot_UsesXDGConfigHome)
		t.Run("TestManagerPaths", TestManagerPaths)
		t.Run("TestDoctor_OrphanEntryMissingInstallPath", TestDoctor_OrphanEntryMissingInstallPath)
		t.Run("TestDoctor_OrphanEntryNotADirectory", TestDoctor_OrphanEntryNotADirectory)
		t.Run("TestDoctor_OrphanCacheDir", TestDoctor_OrphanCacheDir)
		t.Run("TestDoctor_OrphanCacheDir_NoneWhenReferenced", TestDoctor_OrphanCacheDir_NoneWhenReferenced)
		t.Run("TestDoctor_VersionMismatchWarns", TestDoctor_VersionMismatchWarns)
		t.Run("TestDoctor_VersionMatch_NoWarning", TestDoctor_VersionMatch_NoWarning)
		t.Run("TestDoctor_VersionMismatch_DirectorySource_HonestRemediation", TestDoctor_VersionMismatch_DirectorySource_HonestRemediation)
		t.Run("TestDoctor_VersionMismatch_GitSource_PointsAtUpgrade", TestDoctor_VersionMismatch_GitSource_PointsAtUpgrade)
		t.Run("TestDoctor_BrokenComponentFailsValidation", TestDoctor_BrokenComponentFailsValidation)
		t.Run("TestDoctor_DisabledBrokenPluginSkipsComponentCheck", TestDoctor_DisabledBrokenPluginSkipsComponentCheck)
		t.Run("TestDoctor_AutoUpgradeOnDirectorySourceWarns", TestDoctor_AutoUpgradeOnDirectorySourceWarns)
		t.Run("TestDoctor_AutoUpgradeOnRelSourceWarns", TestDoctor_AutoUpgradeOnRelSourceWarns)
		t.Run("TestDoctor_AutoUpgradeOnGitSource_NoWarning", TestDoctor_AutoUpgradeOnGitSource_NoWarning)
		t.Run("TestDoctor_MarketplaceMissingClone", TestDoctor_MarketplaceMissingClone)
		t.Run("TestDoctor_MarketplaceBadJSON", TestDoctor_MarketplaceBadJSON)
		t.Run("TestDoctor_MarketplaceSeededPointerIsOK", TestDoctor_MarketplaceSeededPointerIsOK)
		t.Run("TestDoctor_MarketplaceNotAGitRepo", TestDoctor_MarketplaceNotAGitRepo)
		t.Run("TestDoctor_MarketplaceStaleWarns", TestDoctor_MarketplaceStaleWarns)
		t.Run("TestDoctor_MarketplaceHealthy_DirectorySource", TestDoctor_MarketplaceHealthy_DirectorySource)
		t.Run("TestDoctor_EnvironmentWritable", TestDoctor_EnvironmentWritable)
		t.Run("TestDoctor_StoreRootNotYetCreated_DoesNotCreateOrFail", TestDoctor_StoreRootNotYetCreated_DoesNotCreateOrFail)
		t.Run("TestDoctor_CorruptRegistryReturnsError", TestDoctor_CorruptRegistryReturnsError)
		t.Run("TestDoctor_CorruptMarketplacesReturnsError", TestDoctor_CorruptMarketplacesReturnsError)
		t.Run("TestDoctor_CleanStoreHasNoFailOrWarn", TestDoctor_CleanStoreHasNoFailOrWarn)
		t.Run("TestLoadRegistry_AbsentReturnsEmptyV2", TestLoadRegistry_AbsentReturnsEmptyV2)
		t.Run("TestSaveLoadRegistry_RoundTrip", TestSaveLoadRegistry_RoundTrip)
		t.Run("TestLoadRegistry_RejectsUnknownVersion", TestLoadRegistry_RejectsUnknownVersion)
		t.Run("TestParseCatalog", TestParseCatalog)
		t.Run("TestParseCatalog_SkipsUnsupportedSourceAndReportsIt", TestParseCatalog_SkipsUnsupportedSourceAndReportsIt)
		t.Run("TestBrowse_SkipsUnsupportedSourceAndReturnsTheRest", TestBrowse_SkipsUnsupportedSourceAndReturnsTheRest)
		t.Run("TestCatalogPlugin_ParsesMarketplaceEntryManifestFields", TestCatalogPlugin_ParsesMarketplaceEntryManifestFields)
		t.Run("TestCatalogPlugin_ManifestFieldsOmittedWhenAbsent", TestCatalogPlugin_ManifestFieldsOmittedWhenAbsent)
		t.Run("TestAddListRemoveMarketplace", TestAddListRemoveMarketplace)
		t.Run("TestAddMarketplace_GitSubdirBrowse", TestAddMarketplace_GitSubdirBrowse)
		t.Run("TestAddMarketplace_RejectsTraversalName", TestAddMarketplace_RejectsTraversalName)
		t.Run("TestRemoveMarketplace_DirectorySourceKeepsContents", TestRemoveMarketplace_DirectorySourceKeepsContents)
		t.Run("TestRefreshMarketplace_ClonesUnfetchedSeed", TestRefreshMarketplace_ClonesUnfetchedSeed)
		t.Run("TestAtomicWriteFile_WritesAndOverwrites", TestAtomicWriteFile_WritesAndOverwrites)
		t.Run("TestUpdateAutoUpgrade_OnlyTouchesAutoUpgradeEnabled", TestUpdateAutoUpgrade_OnlyTouchesAutoUpgradeEnabled)
		t.Run("TestUpdateAutoUpgrade_NoOpNotReportedAsUpdated", TestUpdateAutoUpgrade_NoOpNotReportedAsUpdated)
		t.Run("TestUpdateAutoUpgrade_SkipsRelativeAndDirectorySources", TestUpdateAutoUpgrade_SkipsRelativeAndDirectorySources)
		t.Run("TestUpdateAutoUpgrade_AggregatesFailuresButKeepsGoing", TestUpdateAutoUpgrade_AggregatesFailuresButKeepsGoing)
		t.Run("TestUpdateAutoUpgrade_ConcurrentSweepDoesNotDuplicateReport", TestUpdateAutoUpgrade_ConcurrentSweepDoesNotDuplicateReport)
		t.Run("TestHasPluginManifest", TestHasPluginManifest)
		t.Run("TestEnsureManifestFallback_ExistingManifestIsNoop", TestEnsureManifestFallback_ExistingManifestIsNoop)
		t.Run("TestEnsureManifestFallback_NoManifestNoFields_Installs", TestEnsureManifestFallback_NoManifestNoFields_Installs)
		t.Run("TestEnsureManifestFallback_NotStaged_ClearError", TestEnsureManifestFallback_NotStaged_ClearError)
		t.Run("TestEnsureManifestFallback_SynthesizesManifest_MCPServerRegisters", TestEnsureManifestFallback_SynthesizesManifest_MCPServerRegisters)
		t.Run("TestEnsureManifestFallback_PackageJSONBin_WiresMCP", TestEnsureManifestFallback_PackageJSONBin_WiresMCP)
		t.Run("TestEnsureManifestFallback_BinTargetMissing_NoteNoWire", TestEnsureManifestFallback_BinTargetMissing_NoteNoWire)
		t.Run("TestEnsureManifestFallback_MultipleBins_PicksPluginName", TestEnsureManifestFallback_MultipleBins_PicksPluginName)
		t.Run("TestEnsureManifestFallback_MultipleBins_NoMatch_NoteSkip", TestEnsureManifestFallback_MultipleBins_NoMatch_NoteSkip)
		t.Run("TestEnsureManifestFallback_EntryMCPServersWin", TestEnsureManifestFallback_EntryMCPServersWin)
		t.Run("TestEnsureManifestFallback_MCPJSONPresent_NoBinWiring", TestEnsureManifestFallback_MCPJSONPresent_NoBinWiring)
		t.Run("TestEnsureManifestFallback_NoPackageJSON_LSPShape", TestEnsureManifestFallback_NoPackageJSON_LSPShape)
		t.Run("TestEnsureManifestFallback_PackageJSONNoBin", TestEnsureManifestFallback_PackageJSONNoBin)
		t.Run("TestEnsureManifestFallback_BinEscapesDir_NoteSkip", TestEnsureManifestFallback_BinEscapesDir_NoteSkip)
		t.Run("TestEnsureManifestFallback_MalformedPackageJSON", TestEnsureManifestFallback_MalformedPackageJSON)
		t.Run("TestEnsureManifestFallback_EmptyBinName_NoteSkip", TestEnsureManifestFallback_EmptyBinName_NoteSkip)
		t.Run("TestEnsureManifestFallback_StringBin_NoteSkip", TestEnsureManifestFallback_StringBin_NoteSkip)
		t.Run("TestEnsureManifestFallback_SkillsFieldNotHonored", TestEnsureManifestFallback_SkillsFieldNotHonored)
	})
}
