//go:build serffuzz

package msgrender

import "testing"

func init() {
	fuzzCoverageUnion = func(t *testing.T) {
		TestApplyPatchRenderer(t)
		TestApplyPatchRendererUnifiedDiff(t)
		TestApplyPatchRendererV4a(t)
		TestArgsJSONFromDescription(t)
		TestCheckmarkFor(t)
		TestContainsMarkdownSyntax(t)
		TestDelegateBodyHandlesNarrowWidth(t)
		TestDelegateBodyShowsSummaryWhenChildUnavailable(t)
		TestDelegateRenderer(t)
		TestDelegateSendRenderer(t)
		TestDiffBodyHandlesEmptyInput(t)
		TestDiffBodyTintsAddLines(t)
		TestDiffResultText(t)
		TestEditFileRenderer(t)
		TestExtractCommunicate(t)
		TestFileBodyShowsFirstLines(t)
		TestFormatDur(t)
		TestFormatDur_Ranges(t)
		TestGlobRenderer(t)
		TestGrepRenderer(t)
		TestHistoryToMessages_Empty(t)
		TestHistoryToMessages_ThinkingText(t)
		TestHistoryToMessages_ToolCalls(t)
		TestHistoryToMessages_UserAndCommunicate(t)
		TestIndentBlock(t)
		TestIsOrderedMarkdownListItem(t)
		TestJSONBody(t)
		TestJobReadOutputRenderer(t)
		TestJobSendMessageRenderer(t)
		TestJobStopRenderer(t)
		TestListDirRenderer(t)
		TestMCPFallbackTargetIncludesFirstArgs(t)
		TestMarkdownInvalidatorIsWired(t)
		TestReadFileResultLineCount(t)
		TestReasoningGist(t)
		TestRenderMessage_AcrossKinds(t)
		TestRenderMessage_CollapsedReasoningIsAOneLineGist(t)
		TestRenderMessage_EmptyReasoningRendersNothing(t)
		TestRenderMessage_ExpandedReasoningShowsWholeBlock(t)
		TestRenderMessage_KeepsPlainAssistantTextSearchable(t)
		TestRenderMessage_PendingAndFailedPrefix(t)
		TestRenderMessage_RendersAssistantMarkdown(t)
		TestRenderMessage_StreamingReasoningShowsWholeBlock(t)
		TestRenderSelectedMessage(t)
		TestRenderSubagentRailConsolidates(t)
		TestRenderSubagentRailKeepsTiedDoneRowVisible(t)
		TestRenderSubagentRailNamesBackgroundShellByCommand(t)
		TestRenderSubagentRailShowsLiveActivity(t)
		TestRenderToolCallShowsPurposeAsFirstBodyLine(t)
		TestRenderToolCallUsesRegistry(t)
		TestRenderToolCallUsesStructuredSubagentBody(t)
		TestRendererRegistryFallback(t)
		TestRendererRegistryHasReadFile(t)
		TestRendererRegistryMCPFallback(t)
		TestShellBodyHighlightsOutput(t)
		TestShellRenderer(t)
		TestStateColorForToolDone(t)
		TestTaskListBodyRendersPerTaskRows(t)
		TestTaskListRenderer(t)
		TestToolArgsFromJSON(t)
		TestToolArgsStr(t)
		TestUnknownToolHasJSONBody(t)
		TestUnknownToolRenderer(t)
		TestUseSkillRenderer(t)
		TestWebFetchRenderer(t)
		TestWebSearchBodyPassesThroughUnchanged(t)
		TestWebSearchRenderer(t)
		TestWrapText_Empty(t)
		TestWrapText_FitsOnOneLine(t)
		TestWrapText_HardBreaksUnbreakableWord(t)
		TestWrapText_MultiLine(t)
		TestWrapText_WrapsAtWordBoundary(t)
		TestWriteFileRenderer(t)

	}
}
