/**
 * RED test 2: Cross-layer invariant — every public plugin command is in
 * build.rs, has a generated allow permission, belongs to default.toml, and
 * the app capability grants evener-native:default.
 */

import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

const pluginRoot = path.join(
  __dirname,
  "..",
  "..",
  "tauri-plugin-evener-native",
);
const appRoot = path.join(__dirname, "..", "..", "src-tauri");

function read(rel: string, base: string = pluginRoot): string {
  return readFileSync(path.join(base, rel), "utf8");
}

const EXPECTED_COMMANDS = [
  "ping",
  "scan_and_preview_pairing",
  "haptic_perform",
  "content_size_get",
] as const;

describe("7A invariant: build.rs declares all public commands", () => {
  it("build.rs COMMANDS array includes all four commands", () => {
    const buildRs = read("build.rs");
    for (const cmd of EXPECTED_COMMANDS) {
      expect(buildRs).toContain(`"${cmd}"`);
    }
  });
});

describe("7A invariant: generated permission file per command", () => {
  it("each command has an autogenerated allow permission toml", () => {
    for (const cmd of EXPECTED_COMMANDS) {
      const permPath = path.join(
        pluginRoot,
        "permissions",
        "autogenerated",
        "commands",
        `${cmd}.toml`,
      );
      expect(existsSync(permPath)).toBe(true);
      const content = readFileSync(permPath, "utf8");
      expect(content).toContain(`allow-${cmd.replace(/_/g, "-")}`);
      expect(content).toContain(`commands.allow = ["${cmd}"]`);
    }
  });
});

describe("7A invariant: default.toml allows all commands", () => {
  it("permissions/default.toml lists all four allow-* permissions", () => {
    const defaultToml = read("permissions/default.toml");
    for (const cmd of EXPECTED_COMMANDS) {
      const allowName = `allow-${cmd.replace(/_/g, "-")}`;
      expect(defaultToml).toContain(allowName);
    }
  });
});

describe("7A invariant: app capability grants evener-native:default", () => {
  it("src-tauri/capabilities/default.json includes evener-native:default", () => {
    const capPath = path.join(appRoot, "capabilities", "default.json");
    const cap = JSON.parse(readFileSync(capPath, "utf8")) as {
      permissions: string[];
    };
    expect(cap.permissions).toContain("evener-native:default");
  });
});
