/**
 * Cross-layer invariant — every public plugin command is in build.rs, has a
 * generated allow permission, belongs to the `[default]` table of
 * default.toml (not a stray top-level key), and the app capability grants
 * evener-native:default. The generated reference must list all four under
 * the Default Permission section.
 */
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

const pluginRoot = path.join(
  __dirname,
  "..",
  "..",
  "tauri-plugin-evener-native",
);
const appRoot = path.join(__dirname, "..", "..", "src-tauri");

function read(rel: string, base: string = pluginRoot): string {
  return readFileSync(path.join(base, rel), "utf8");
}

const EXPECTED_COMMANDS = [
  "ping",
  "scan_and_preview_pairing",
  "haptic_perform",
  "content_size_get",
] as const;

const EXPECTED_ALLOWS = EXPECTED_COMMANDS.map(
  (cmd) => `allow-${cmd.replace(/_/g, "-")}`,
);

describe("7A invariant: build.rs declares all public commands", () => {
  it("build.rs COMMANDS array includes all four commands", () => {
    const buildRs = read("build.rs");
    for (const cmd of EXPECTED_COMMANDS) {
      expect(buildRs).toContain(`"${cmd}"`);
    }
  });
});

describe("7A invariant: generated permission file per command", () => {
  it("each command has an autogenerated allow permission toml", () => {
    for (const cmd of EXPECTED_COMMANDS) {
      const permPath = path.join(
        pluginRoot,
        "permissions",
        "autogenerated",
        "commands",
        `${cmd}.toml`,
      );
      expect(existsSync(permPath)).toBe(true);
      const content = readFileSync(permPath, "utf8");
      expect(content).toContain(`allow-${cmd.replace(/_/g, "-")}`);
      expect(content).toContain(`commands.allow = ["${cmd}"]`);
    }
  });
});

describe("7A invariant: [default] table grants all commands", () => {
  it("default.toml has a [default] table with all four allow-* permissions", () => {
    const defaultToml = read("permissions/default.toml");
    // Parse the [default] table specifically — a stray top-level `permissions`
    // key must NOT satisfy this invariant.
    const defaultMatch = defaultToml.match(
      /\[default\][\s\S]*?permissions\s*=\s*\[([^\]]*)\]/,
    );
    expect(defaultMatch).not.toBeNull();
    const permsArray = defaultMatch?.[1] ?? "";
    for (const allow of EXPECTED_ALLOWS) {
      expect(permsArray).toContain(`"${allow}"`);
    }
  });

  it("default.toml has no stray top-level permissions key outside [default]", () => {
    const defaultToml = read("permissions/default.toml");
    // A top-level `permissions =` that appears before `[default]` is a stray.
    const beforeDefault = defaultToml.split(/\[default\]/)[0] ?? "";
    expect(beforeDefault).not.toMatch(/^permissions\s*=/m);
  });
});

describe("7A invariant: generated reference lists default permissions", () => {
  it("reference.md Default Permission section lists all four allow-*", () => {
    const ref = read("permissions/autogenerated/reference.md");
    // Slice only the Default Permission section (before ## Permission Table)
    // so the test fails if default bullets omit haptic/content but the
    // Permission Table still contains them.
    const defaultSection = ref.split("## Permission Table")[0] ?? "";
    for (const allow of EXPECTED_ALLOWS) {
      // allow is already the full permission name e.g. "allow-ping"
      expect(defaultSection).toContain(`- \`${allow}\``);
    }
  });
});

describe("7A invariant: app capability grants evener-native:default", () => {
  it("src-tauri/capabilities/default.json includes evener-native:default", () => {
    const capPath = path.join(appRoot, "capabilities", "default.json");
    const cap = JSON.parse(readFileSync(capPath, "utf8")) as {
      permissions: string[];
    };
    expect(cap.permissions).toContain("evener-native:default");
  });
});
