//go:build serffuzz

package main

import "testing"

// FuzzRootCommandSeedCoverage brings the deterministic command integration
// scenarios into the committed fuzz replay. Each scenario keeps its existing
// external-boundary fakes; no provider or network traffic is introduced.
func FuzzRootCommandSeedCoverage(f *testing.F) {
	f.Add(uint8(0))
	f.Fuzz(func(t *testing.T, _ uint8) {
		tests := []struct {
			name string
			fn   func(*testing.T)
		}{
			{"client provider", TestClientHasProvider},
			{"openai status formatting", TestFormatOpenAIStatus},
			{"run args", TestRunWithArgs},
			{"run tool events", TestRunEmitsToolEvents},
			{"run missing prompt", TestRunMissingPrompt},
			{"run missing key", TestRunMissingAPIKey},
			{"run bare model", TestRunBareModelRejected},
			{"run invalid schema", TestRunInvalidOutputSchema},
			{"run cheap model", TestRunFastCheapModelValidation},
			{"run missing model", TestRunMissingModel},
			{"sessions formatted", TestListSessions_PrintsFormattedList},
			{"sessions empty", TestListSessions_EmptyDir},
			{"resume id", TestResume_NonexistentID},
			{"resume last", TestResumeLast_NoSessions},
			{"verbose events", TestDrainEventsVerbose},
			{"human events", TestDrainEventsHuman},
			{"plugin dirs", TestRunPluginDirsPassthrough},
			{"slash expansion", TestRun_SlashCommandExpansion},
			{"plugin events", TestDrainEventsHuman_PluginEvents},
			{"context strategy", TestRunWithContextStrategy_DoesNotError},
			{"sandbox off", TestConfigureSandboxOffIsNoop},
			{"sandbox carrier", TestConfigureSandboxNonOffCarriesInert},
			{"sandbox invalid", TestConfigureSandboxBadValues},
			{"sandbox flag off", TestSandboxFlagOffIsInert},
			{"sandbox restricted", TestSandboxFlagRestrictedEnforces},
			{"sandbox reprovision", TestSandboxReprovisionAfterCleanup},
			{"sandbox clear", TestReconcileClearSandbox},
			{"sandbox net", TestParseSandboxNet},
			{"profile config", TestBuildInitialProfile_ConfigPath},
			{"profile schema", TestBuildInitialProfile_ConfigPathInvalidOutputSchema},
			{"profile unknown", TestBuildInitialProfile_UnknownInstanceError},
			{"profile materialized", TestBuildInitialProfile_MaterializedInstance},
			{"serve bare model", TestRunServe_BareModelRejected},
			{"serve missing model", TestRunServe_MissingModel},
			{"serve env", TestPrintServeEnvVars_IncludesOpenAIResponsesContinuation},
			{"serve rendezvous", TestServe_WritesAndRemovesRendezvousFile},
			{"serve noninteractive", TestRunServeNonInteractiveFlagControlsPromptAddendum},
			{"serve shutdown", TestRunServeShutdownWaitsForInFlightInput},
			{"serve api log", TestServeClient_APILogWritesJSONL},
			{"status empty", TestAgentToServerDetailedStatus_Empty},
			{"status partial", TestAgentToServerDetailedStatus_Partial},
			{"usage zero", TestSerfUsageFromLLM_ZeroReturnsNil},
			{"usage totals", TestSerfUsageFromLLM_MapsTotals},
			{"usage cache", TestSerfUsageFromLLM_NonZeroCacheReadOnlyStillReturns},
			{"serve resume", TestRunServe_ResumeNonexistent},
			{"cheap same provider", TestApplyFastCheapModel_SameProviderOverridesCheapModel},
			{"cheap cross provider", TestApplyFastCheapModel_CrossProviderWhenRegistered},
			{"cheap missing provider", TestApplyFastCheapModel_CrossProviderRejectedWhenNotRegistered},
			{"cheap bare", TestApplyFastCheapModel_BareModelKeepsActiveProvider},
			{"cheap blank", TestApplyFastCheapModel_BlankKeepsDefault},
			{"session env", TestNewSessionFromEnv},
			{"simple prompt", TestProcessInputSimplePrompt},
			{"tool prompt", TestProcessInputWithToolUse},
			{"openai dispatch", TestOpenAIDispatchesFromTopLevel},
			{"openai help", TestOpenAIHelpShowsCommands},
			{"continuation", TestResolveOpenAIResponsesContinuation},
			{"run env", TestPrintRunEnvVars_IncludesOpenAIResponsesContinuation},
			{"openai subcommand help", TestOpenAISubcommandHelpReturnsErrHelp},
			{"top help effort", TestTopLevelHelpShowsReasoningEffort},
			{"top help commands", TestTopLevelHelpListsSubcommands},
			{"top help flags", TestTopLevelHelpListsEveryRegisteredFlag},
			{"openai state dir", TestOpenAIStateDirDefaultIsUserScoped},
			{"openai login", TestOpenAILoginPrintsURLAndSupportsManualFallback},
			{"openai device", TestOpenAIDeviceLoginPrintsCodeAndStatus},
			{"headless login", TestIsHeadlessLoginForDecisionTable},
			{"login mode", TestChooseLoginModeRespectsExplicitFlags},
			{"login conflict", TestOpenAILoginRejectsConflictingFlags},
			{"login auto device", TestOpenAILoginAutoSelectsDeviceWhenHeadless},
			{"openai compact status", TestOpenAIStatusIsCompactAndScriptFriendly},
			{"openai logout", TestOpenAILogoutDeletesOnlySerfOwnedAuthState},
			{"openai unknown", TestRunOpenAI_HelpAndUnknown},
			{"logout errors", TestRunOpenAILogout_Errors},
			{"redirect canceled", TestMakeRedirectURLReader_ContextCancelled},
			{"redirect empty", TestMakeRedirectURLReader_EmptyLine},
			{"serve dispatch error", TestDispatchCLICommand_ServeError},
			{"default dispatch", TestDispatchCLICommand_Default},
			{"empty dispatch", TestDispatchCLICommand_NoArgs},
			{"extra human events", TestDrainEventsHuman_CommunicateAndSkillActivated},
			{"login errors", TestRunOpenAILogin_Errors},
			{"market empty", TestPluginMarketplaceList_Empty},
			{"plugin unknown", TestPluginUnknownSubcommand},
			{"market source", TestParseMarketplaceSourceArg},
			{"market confirmation", TestPluginMarketplaceAdd_RequiresConfirmation},
			{"market remove", TestPluginMarketplaceRemove},
			{"market browse", TestPluginMarketplaceBrowse_ListsPluginsAndNotesSkipped},
			{"market browse json", TestPluginMarketplaceBrowse_JSON},
			{"market browse name", TestPluginMarketplaceBrowse_RequiresName},
			{"market list json", TestPluginMarketplaceList_WithJSON},
			{"plugin help", TestPluginHelp},
			{"plugin list json", TestPluginList_JSONEmpty},
			{"plugin ref", TestSplitPluginRef},
			{"plugin auto upgrade", TestPluginAutoUpgrade_RoundTripsInList},
			{"plugin auto ref", TestPluginAutoUpgrade_RequiresRef},
			{"plugin check", TestPluginCheckNow_FreshStoreReportsNothing},
			{"plugin check json", TestPluginCheckNow_JSON},
			{"plugin check directory", TestPluginCheckNow_SkipsDirectorySourcePlugin},
			{"plugin install confirmation", TestPluginInstall_RequiresConfirmation},
			{"plugin doctor json", TestPluginDoctor_JSON},
			{"plugin doctor human", TestPluginDoctor_Human},
			{"plugin doctor no seed", TestPluginDoctor_DoesNotSeedMarketplaces},
			{"plugin gc empty", TestPluginGc_NothingToRemove},
			{"plugin gc json", TestPluginGc_JSON},
			{"upgrade install", TestUpgradeSubcommandInstallsSnapshot},
			{"upgrade args", TestRunUpgrade_TooManyArgs},
			{"upgrade flag", TestRunUpgrade_InvalidFlag},
		}
		for _, tc := range tests {
			t.Run(tc.name, tc.fn)
		}
	})
}
