// Code generated by internal/appwirets; DO NOT EDIT. Run make generate.

export interface AgentMessageDeltaParams {
  threadId: string;
  ref: string;
  turnId: string;
  itemId: string;
  delta: string;
}

export interface AgentMessageResetParams {
  threadId: string;
  ref: string;
  turnId: string;
  itemId: string;
}

export interface ArchiveParams {
  kind: string;
  id: string;
  workingDir?: string;
  archived: boolean;
}

export interface ArchiveResponse {
  ok: boolean;
  navigation: NavigationMutation;
}

export interface AttentionChanged {
  threadId: string;
  title: string;
  project: string;
  level: string;
  askPending?: boolean;
  prevLevel: string;
}

export interface AttentionChangedPayload {
  changed: AttentionChanged[];
  summary: AttentionSummary;
}

export interface AttentionSummary {
  needsYou: number;
  error: number;
  working: number;
}

export interface AuthApiKeySetParams {
  provider: string;
  value: string;
}

export interface AuthDevicePollParams {
  provider: string;
  flowId: string;
}

export interface AuthDevicePollResponse {
  state: string;
  status?: AuthStatusResponse;
}

export interface AuthDeviceStartParams {
  provider: string;
}

export interface AuthDeviceStartResponse {
  provider: string;
  flowId: string;
  userCode: string;
  verificationUrl: string;
  intervalSeconds: number;
  fallback?: boolean;
}

export interface AuthListResponse {
  providers: AuthStatusResponse[];
}

export interface AuthLoginCompleteParams {
  provider: string;
  flowId: string;
  redirectUrl: string;
}

export interface AuthLoginCompleteResponse {
  status: AuthStatusResponse;
}

export interface AuthLoginStartParams {
  provider: string;
}

export interface AuthLoginStartResponse {
  provider: string;
  flowId: string;
  url: string;
}

export interface AuthLogoutParams {
  provider: string;
}

export interface AuthLogoutResponse {
  removed: boolean;
  status: AuthStatusResponse;
}

export interface AuthStatusParams {
  provider: string;
}

export interface AuthStatusResponse {
  provider: string;
  supported: boolean;
  signedIn: boolean;
  activeSource: string;
  authModes?: string[];
  hasStoredOAuth: boolean;
  hasStoredFile?: boolean;
  envVar?: string;
  email?: string;
  storedEmail?: string;
  accountId?: string;
  workspaceId?: string;
  needsRefresh?: boolean;
  needsLogin?: boolean;
  error?: string;
}

export interface AuthTestParams {
  provider: string;
}

export interface AuthTestResponse {
  provider: string;
  status: string;
  message: string;
}

export interface Capabilities {
  experimentalApi: boolean;
  optOutNotificationMethods?: string[];
}

export interface ClientInfo {
  name: string;
  version: string;
}

export interface CommandDescriptor {
  name: string;
  pluginName?: string;
  description?: string;
  argumentHint?: string;
  source?: string;
}

export interface CommandListResponse {
  commands: CommandDescriptor[];
}

export interface DeletionSkip {
  id: string;
  reason: string;
}

export interface DiagnosticCause {
  kind: string;
  provider?: string;
  model?: string;
  status?: number;
}

export interface DirsCreateParams {
  path: string;
}

export interface DirsCreateResponse {
  path: string;
  created: boolean;
}

export interface EmptyParams {
}

export interface EmptyResponse {
}

export interface EvenerAuthUpdatedParams {
  provider?: string;
  activeSource?: string;
}

export interface EvenerDelegateInfo {
  delegateId: string;
  ownerSessionId: string;
  rootSessionId: string;
  childSessionId: string;
  transcriptRef: string;
  parentDelegateId?: string;
  type: string;
  lifecycle: string;
  phase: string;
  status: string;
  outcome?: string;
  reason?: string;
  terminal?: boolean;
  resumable: boolean;
  needsAttention: boolean;
  notResumableReason?: string;
  projectionRevision: number;
  task?: string;
  description?: string;
  agentType?: string;
  requestedModel?: string;
  resolvedProfileId?: string;
  resolvedModel?: string;
  model?: string;
  reasoningEffort?: string;
  originTurnId?: string;
  originToolCallId?: string;
  originItemId?: string;
  runStartedAt?: string;
  runEndedAt?: string;
  latestActivityAt?: string;
  runningForMs?: number;
  quietForMs?: number;
  durationMs?: number;
  packetKind?: string;
  message?: unknown;
  structuredResult?: unknown;
  structuredResultValid?: boolean;
  structuredResultReason?: string;
  warnings?: string[];
  diagnostics?: string[];
  exhaustionBudget?: string;
  exhaustionLimit?: number;
  exhaustionResumable?: boolean;
  delegationAllowance?: number;
  parentWatchGranted?: boolean;
  usage?: EvenerUsage;
  worktree?: JobActivityWorktree;
}

export interface EvenerDelegateParams {
  threadId: string;
  ref: string;
  delegate: EvenerDelegateInfo;
}

export interface EvenerDiagnostics {
  tools?: EvenerToolInfo[];
  mcp?: EvenerMCPServerInfo[];
  skills?: EvenerSkillInfo[];
  plugins?: EvenerPluginInfo[];
  hookEvents?: EvenerHookEventStatus[];
  jobs?: EvenerJobInfo[];
  delegates?: EvenerDelegateInfo[];
  turnSlots?: EvenerTurnSlots;
  agents?: string[];
}

export interface EvenerHookEventStatus {
  event: string;
  count: number;
  tier?: string;
  supported: boolean;
}

export interface EvenerJobInfo {
  jobId: string;
  jobType: string;
  status: string;
  reason?: string;
  exhaustionBudget?: string;
  exhaustionLimit?: number;
  resumable?: boolean;
  exitCode?: number;
  outputBytes: number;
  transcriptRef?: string;
  fromWatch?: boolean;
  background?: boolean;
  command?: string;
  intent?: string;
  parentDelegateId?: string;
  delegateId?: string;
  task?: string;
  originTurnId?: string;
  originToolCallId?: string;
  originItemId?: string;
}

export interface EvenerJobParams {
  threadId: string;
  ref: string;
  job: EvenerJobInfo;
}

export interface EvenerLaunchUpdatedParams {
  cwd: string;
  layer: string;
}

export interface EvenerMCPServerInfo {
  name: string;
  tools: string[];
  status?: string;
  error?: string;
}

export interface EvenerPluginInfo {
  name: string;
  version?: string;
  skillCount: number;
  agentCount: number;
  hookCount: number;
  mcpCount: number;
}

export interface EvenerSkillInfo {
  name: string;
  description?: string;
}

export interface EvenerSteeringInjectedParams {
  threadId: string;
  ref: string;
  text?: string;
  images?: InputItem[];
  source?: string;
  kind?: string;
  clientMutationId?: string;
}

export interface EvenerSubagentPreviewParams {
  ref: string;
  limit?: number;
}

export interface EvenerSubagentPreviewResponse {
  ref: string;
  items: ThreadItem[];
  truncated: boolean;
}

export interface EvenerThread {
  ref: string;
  instanceId?: string;
  parentRef?: string;
  kind?: string;
  profile?: string;
  turnCount?: number;
  activeTurnId?: string;
  contextPressure?: number;
  contextUsed?: number;
  contextWindow?: number;
  contextRemaining?: number;
  capabilities: ThreadCapabilities;
  diagnostics?: EvenerDiagnostics;
  queue: QueueState;
  pendingMutations?: PendingMutation[];
  tasks?: TaskAggregate;
  goal?: GoalState;
  usage?: EvenerUsage;
  workMillis?: number;
  activeTurnStartedAt?: number;
  cost?: string;
  failedToolCalls?: number;
  askPending?: boolean;
  pendingEscalations?: SandboxEscalationRequested[];
  reasoningEffort?: string;
  reasoningEffortLevels?: string[];
  supportsReasoning?: boolean;
  visionModel?: string;
}

export interface EvenerToolInfo {
  name: string;
  source: string;
}

export interface EvenerTurnSlots {
  inUse: number;
  cap: number;
  jobs: number;
  driveTurns: number;
}

export interface EvenerUsage {
  inputTokens?: number;
  outputTokens?: number;
  cacheReadTokens?: number;
  totalTokens?: number;
}

export interface FavoriteSetParams {
  kind: string;
  id: string;
  favorited: boolean;
}

export interface FavoriteSetResponse {
  ok: boolean;
  navigation: NavigationMutation;
}

export interface FeatureSet {
  threadList: boolean;
  threadTurnsList: boolean;
  turnStart: boolean;
  turnSteer: boolean;
  threadClear: boolean;
  threadShutdown: boolean;
  forkFromTurn: boolean;
  tasks: boolean;
  transcriptList: boolean;
  modelList: boolean;
  directoryComplete: boolean;
  auth: boolean;
  transcriptDisplaySettings?: boolean;
}

export interface GitHeadParams {
  cwd: string;
}

export interface GitHeadResponse {
  head: string;
}

export interface GitInfo {
  sha?: string;
  branch?: string;
  originUrl?: string;
}

export interface GoalSetParams {
  ref: string;
  objective?: string;
}

export interface GoalSetResponse {
  started: boolean;
}

export interface GoalState {
  objective?: string;
  status: string;
  iterations: number;
}

export interface GoalUpdatedParams {
  threadId: string;
  ref: string;
  goal: GoalState | null;
}

export interface HarnessDescriptor {
  id: string;
  label: string;
  kind?: string;
  emptyTaskUnsupportedReason?: string;
  emptyTaskUnsupportedNextAction?: string;
}

export interface HarnessListParams {
}

export interface HarnessListResponse {
  data: HarnessDescriptor[];
}

export interface InitializeParams {
  protocolVersion: string;
  clientInfo: ClientInfo;
  capabilities: Capabilities;
}

export interface InitializeResponse {
  serverInfo: ServerInfo;
  protocolVersion: string;
  sourceId: string;
  features: FeatureSet;
  navigation?: NavigationCapability;
}

export interface InputItem {
  type: string;
  text?: string;
  url?: string;
  mediaType?: string;
  data?: string;
  name?: string;
  path?: string;
  metadata?: Record<string, string>;
}

export interface InstanceCreateParams {
  name: string;
  base: string;
  baseUrl?: string;
  protocol?: string;
  surface?: string;
  vars?: Record<string, string>;
  apiKeyEnv?: string;
  credentialHeader?: string;
}

export interface InstanceEditParams {
  name: string;
  baseUrl?: string;
  clearBaseUrl?: boolean;
  protocol?: string;
  surface?: string;
  vars?: Record<string, string>;
}

export interface InstanceEntry {
  name: string;
  base?: string;
  providerId: string;
  protocol: string;
  surface?: string;
  auth: string;
  baseUrl?: string;
  vars?: Record<string, string>;
  implicit: boolean;
  hidden?: boolean;
  isDefault: boolean;
  authModes?: string[];
  activeSource: string;
  hasStoredFile?: boolean;
  hasStoredOAuth: boolean;
  envVar?: string;
  storedEmail?: string;
  credentialRequired: boolean;
  warnings?: string[];
}

export interface InstanceListResponse {
  instances: InstanceEntry[];
  availableProviders: ProviderDescriptor[];
  diagnostics?: string[];
  userLayer?: string;
  writesRefused?: boolean;
}

export interface InstanceRemoveParams {
  name: string;
}

export interface InstanceSetDefaultParams {
  name: string;
}

export interface ItemLifecycleParams {
  threadId: string;
  ref: string;
  turnId: string;
  item: ThreadItem;
  failedToolCalls?: number;
}

export interface JobActivityBranchState {
  error?: string;
  truncated?: boolean;
  continuation?: string;
}

export interface JobActivityCounts {
  active: number;
  failed: number;
  completed: number;
  complete: boolean;
}

export interface JobActivityDelegate {
  delegateId: string;
  ownerSessionId?: string;
  rootSessionId?: string;
  childSessionId: string;
  childRef: string;
  parentDelegateId?: string;
  type?: string;
  lifecycle?: string;
  phase?: string;
  status?: string;
  projectionRevision?: number;
  outcome?: string;
  reason?: string;
  terminal?: boolean;
  resumable?: boolean;
  notResumableReason?: string;
  mandate?: string;
  task?: string;
  description?: string;
  agentType?: string;
  requestedModel?: string;
  resolvedProfileId?: string;
  resolvedModel?: string;
  model?: string;
  reasoningEffort?: string;
  originTurnId?: string;
  originToolCallId?: string;
  originItemId?: string;
  runStartedAt?: string;
  runEndedAt?: string;
  latestActivityAt?: string;
  runningForMs?: number;
  quietForMs?: number;
  durationMs?: number;
  packetKind?: string;
  message?: unknown;
  structuredResult?: unknown;
  structuredResultValid?: boolean;
  structuredResultReason?: string;
  warnings?: string[];
  diagnostics?: string[];
  exhaustionBudget?: string;
  exhaustionLimit?: number;
  exhaustionResumable?: boolean;
  delegationAllowance?: number;
  parentWatchGranted?: boolean;
  worktree?: JobActivityWorktree;
  turns: JobActivityJob[];
  child?: JobActivitySession;
  branch: JobActivityBranchState;
  usage?: EvenerUsage;
}

export interface JobActivityEntry {
  kind: string;
  job?: JobActivityJob;
  delegate?: JobActivityDelegate;
}

export interface JobActivityJob {
  jobId: string;
  ownerSessionId: string;
  ownerRef: string;
  transcriptRef?: string;
  type: string;
  status: string;
  outcome?: string;
  terminal: boolean;
  background: boolean;
  hasOutput: boolean;
  description: string;
  command?: string;
  task?: string;
  reason?: string;
  startedAt: string;
  endedAt?: string;
  exitCode?: number;
  outputBytes: number;
  lastOutputAt?: string;
}

export interface JobActivitySession {
  sessionId: string;
  ref: string;
  label: string;
  aggregate: string;
  counts: JobActivityCounts;
  entries: JobActivityEntry[];
  diagnostics?: string[];
  branch: JobActivityBranchState;
}

export interface JobActivityTree {
  revision: number;
  root: JobActivitySession;
}

export interface JobActivityWorktree {
  path: string;
  branch: string;
  headSha: string;
  ahead: number;
  dirty: boolean;
}

export interface JobsListParams {
  ref?: string;
  continuation?: string;
}

export interface JobsListResponse {
  data: unknown;
}

export interface JobsOutputParams {
  ref?: string;
  jobId: string;
  maxBytes?: number;
  beforeBytes?: number;
}

export interface JobsOutputResponse {
  data: unknown;
}

export interface JobsTreeUpdatedParams {
  threadId: string;
  ref: string;
  revision: number;
}

export interface LaunchConfigDiagnostic {
  layer: string;
  field: string;
  message: string;
}

export interface LaunchConfigGetLayerParams {
  cwd: string;
  layer: string;
}

export interface LaunchConfigLayer {
  schema?: number;
  model?: string;
  fastCheapModel?: string;
  agent?: string;
  reasoningEffort?: string;
  contextStrategy?: string;
  openAIResponsesContinuation?: string;
  sandbox?: string;
  sandboxNet?: boolean;
  maxRounds?: number;
  maxSubagentDepth?: number;
  maxConcurrentDelegateTurns?: number;
  maxRetainedTerminal?: number;
  noProjectPrompts?: boolean;
  nonInteractive?: boolean;
  appReplaySize?: number;
  skillsDirs?: string[];
  pluginDirs?: string[];
  mcpConfigs?: string[];
  systemPromptMode?: string;
  systemPromptFile?: string;
  systemPromptText?: string;
  systemPromptAppendMode?: string;
  systemPromptAppendFile?: string;
  systemPromptAppendText?: string;
  systemPromptAppend?: string[];
  modelFallbacks?: string[];
  enabledPlugins?: string[];
  mcps?: MCPServerSpec[];
  env?: Record<string, string>;
  verbose?: boolean;
  traceFile?: string;
  cpuProfile?: string;
  exportATIFPath?: string;
  exportATIFProviderHandles?: string;
}

export interface LaunchConfigResolveParams {
  cwd: string;
  launchOverrides?: LaunchConfigLayer;
}

export interface LaunchConfigResolved {
  effective: LaunchConfigLayer;
  layers: Record<string, LaunchConfigLayer>;
  provenance: Record<string, string>;
  repo?: RepoLaunchConfigStatus;
  diagnostics?: LaunchConfigDiagnostic[];
}

export interface LaunchConfigSetLayerParams {
  cwd: string;
  layer: string;
  config: LaunchConfigLayer;
}

export interface LaunchConfigTrustRepoParams {
  cwd: string;
  hash: string;
}

export interface LaunchOption {
  field: string;
  wireField: string;
  label: string;
  description?: string;
  group: string;
  kind: string;
  pathKind?: string;
  repeatable?: boolean;
  defaultableLayers?: string[];
  perLaunch: boolean;
  debugOnly?: boolean;
  envFallback?: LaunchOptionEnvFallback;
  choices?: LaunchOptionChoice[];
  driverSupport?: Record<string, boolean>;
  builtinDefault?: string;
  builtinDefaultInt?: number;
  builtinDefaultBool?: boolean;
  builtinDefaultLabel?: string;
}

export interface LaunchOptionChoice {
  value: string;
  label: string;
  disabled?: boolean;
  hint?: string;
}

export interface LaunchOptionEnvFallback {
  name: string;
}

export interface LaunchOptionSchemaResponse {
  options: LaunchOption[];
  excluded?: Record<string, string>;
}

export interface MCPServerSpec {
  name: string;
  command: string;
  args?: string[];
}

export interface MarketplaceAddParams {
  name?: string;
  source: MarketplaceSourceInput;
}

export interface MarketplaceBrowseParams {
  name: string;
}

export interface MarketplaceBrowseResponse {
  name: string;
  description?: string;
  plugins: MarketplaceCatalogPlugin[];
}

export interface MarketplaceCatalogPlugin {
  name: string;
  description?: string;
  category?: string;
  homepage?: string;
  author?: string;
}

export interface MarketplaceEntry {
  name: string;
  source: MarketplaceSourceInput;
  installLocation?: string;
  lastUpdated: number;
}

export interface MarketplaceListResponse {
  marketplaces: MarketplaceEntry[];
}

export interface MarketplaceNameParams {
  name: string;
}

export interface MarketplaceSourceInput {
  kind: string;
  repo?: string;
  url?: string;
  path?: string;
  ref?: string;
  sha?: string;
}

export interface MobilePairingParams {
  origin: string;
}

export interface MobilePairingResponse {
  authUrl: string;
}

export interface ModelDescriptor {
  provider: string;
  model: string;
  displayName?: string;
  contextWindow?: number;
  supportsTools?: boolean;
  supportsVision?: boolean;
  maxOutputTokens?: number;
  supportsWebSearch?: boolean;
  supportsReasoning?: boolean;
  inputCostPerMillion?: number;
  outputCostPerMillion?: number;
  reasoningEffortLevels?: string[];
}

export interface ModelListDiagnostic {
  provider?: string;
  source?: string;
  title?: string;
  message: string;
  hint?: string;
}

export interface ModelListParams {
  harness?: string;
  cwd?: string;
}

export interface ModelListResponse {
  data: ModelDescriptor[];
  diagnostics?: ModelListDiagnostic[];
  recent?: ModelDescriptor[];
}

export interface MutationReceipt {
  clientMutationId: string;
  disposition: string;
  threadId: string;
  instanceId?: string;
  turnId?: string;
  queueEntryIds?: string[];
  projectionState: string;
}

export interface NavigationCapability {
  version: number;
  generationId: string;
  sequence: number;
}

export interface NavigationCatalogs {
  projects: NavigationResourceDescriptor;
  archived_projects: NavigationResourceDescriptor;
  test_runs: NavigationResourceDescriptor;
}

export interface NavigationInvalidatedPayload {
  generationId: string;
  sequence: number;
  targets: NavigationInvalidationTarget[];
}

export interface NavigationInvalidationTarget {
  kind: "manifest" | "section" | "pin_catalog" | "pin_section" | "catalog" | "project" | "all_loaded_projects";
  section?: string;
  sectionId?: string;
  catalog?: string;
  projectKey?: string;
  revision?: number;
}

export interface NavigationJobSummary {
  job_id: string;
  job_type: string;
  status: string;
  command?: string;
  task?: string;
  reason?: string;
  intent?: string;
  full_command?: string;
}

export interface NavigationManifest {
  generation_id: string;
  revision: number;
  sources: Source[];
  attentionSummary: AttentionSummary;
  sections: NavigationSections;
  catalogs: NavigationCatalogs;
}

export interface NavigationMutation {
  generation_id: string;
  targets: NavigationInvalidationTarget[];
}

export interface NavigationPinSectionCatalog {
  generation_id: string;
  revision: number;
  pin_sections: NavigationPinSectionDescriptor[];
  remaining: number;
}

export interface NavigationPinSectionDescriptor {
  id: string;
  name: string;
  count: number;
}

export interface NavigationProjectCatalog {
  generation_id: string;
  revision: number;
  projects: NavigationProjectSummary[];
  remaining: number;
}

export interface NavigationProjectPage {
  generation_id: string;
  revision: number;
  key: string;
  tier: string;
  offset: number;
  sessions: NavigationSessionSummary[];
  remaining: number;
  truncated: boolean;
}

export interface NavigationProjectResource {
  generation_id: string;
  revision: number;
  key: string;
  current: NavigationTier;
  recent: NavigationTier;
  archived: NavigationTier;
  truncated: boolean;
}

export interface NavigationProjectSummary {
  key: string;
  name: string;
  working_dir?: string;
  rollup_state?: string;
  rollup_live?: number;
  rollup_attn?: number;
  default_expanded?: boolean;
  more_current?: number;
  more_recent?: number;
  more_archived?: number;
  worktrees?: number;
  is_archived?: boolean;
  favorite?: boolean;
  session_count: number;
}

export interface NavigationReadParams {
  resource: string;
  section?: string;
  sectionId?: string;
  catalog?: string;
  projectKey?: string;
  tier?: string;
  ref?: string;
  offset?: number;
  limit?: number;
  etag?: string;
}

export interface NavigationReadResponse {
  status: string;
  generationId: string;
  revision: number;
  etag: string;
  data?: unknown;
}

export interface NavigationResourceDescriptor {
  count: number;
}

export interface NavigationSectionResource {
  generation_id: string;
  revision: number;
  sessions: NavigationSessionSummary[];
  remaining: number;
  truncated: boolean;
}

export interface NavigationSections {
  live: NavigationResourceDescriptor;
  needs_you: NavigationResourceDescriptor;
  pin_sections: NavigationResourceDescriptor;
}

export interface NavigationSessionLocation {
  generation_id: string;
  revision: number;
  ref: string;
  top_level_ref: string;
  project_key?: string;
  top_level: boolean;
  tier?: string;
  pin_section_id?: string;
  session?: NavigationSessionSummary;
}

export interface NavigationSessionSummary {
  ref: string;
  host_id: string;
  session_id: string;
  title: string;
  project: string;
  state: string;
  kind: string;
  branch?: string;
  cluster_count?: number;
  favorite?: boolean;
  rename?: boolean;
  live: boolean;
  ask_pending?: boolean;
  dormant?: boolean;
  updated_at?: string;
  more_subagents?: number;
  omitted_descendants?: number;
  running_jobs?: NavigationJobSummary[];
  completed_jobs?: NavigationJobSummary[];
  children: NavigationSessionSummary[];
}

export interface NavigationTier {
  sessions: NavigationSessionSummary[];
  remaining: number;
}

export interface OutputImage {
  source: string;
  name?: string;
  mediaType?: string;
  size?: number;
  url?: string;
  sha?: string;
  path?: string;
}

export interface PathValidateParams {
  path: string;
  kind?: string;
}

export interface PathValidateResponse {
  path: string;
  valid: boolean;
  error?: string;
}

export interface PathsCompleteParams {
  prefix: string;
  limit?: number;
  includeFiles?: boolean;
}

export interface PathsCompleteResponse {
  data: string[];
}

export interface PendingMutation {
  clientMutationId: string;
  method: string;
  input?: InputItem[];
  executionState: string;
  turnId?: string;
  queueEntryIds?: string[];
  projectionState: string;
}

export interface PinSection {
  id: string;
  name: string;
  memberCount: number;
}

export interface PinSectionDeleteParams {
  sectionId: string;
}

export interface PinSectionDeleteResponse {
  ok: boolean;
  changed: boolean;
  memberCount: number;
  navigation: NavigationMutation;
}

export interface PinSectionRenameParams {
  sectionId: string;
  name: string;
}

export interface PinSectionRenameResponse {
  ok: boolean;
  changed: boolean;
  section: PinSection;
  navigation: NavigationMutation;
}

export interface PluginCheckNowResponse {
  updated?: string[];
  errors?: string[];
}

export interface PluginDiagnostic {
  name?: string;
  path?: string;
  source?: string;
  message: string;
}

export interface PluginEntry {
  plugin: string;
  marketplace: string;
  version: string;
  enabled: boolean;
  autoUpgrade: boolean;
  broken: boolean;
  installPath: string;
  gitCommitSha?: string;
  installedAt: number;
  lastUpdated: number;
}

export interface PluginLaunchCandidate {
  name: string;
  version?: string;
  description?: string;
  source: string;
  marketplace?: string;
  path?: string;
  selected: boolean;
  skillCount: number;
  agentCount: number;
  commandCount: number;
  hookCount: number;
  mcpCount: number;
}

export interface PluginListResponse {
  plugins: PluginEntry[];
}

export interface PluginPreviewParams {
  cwd: string;
  launchOverrides?: LaunchConfigLayer;
}

export interface PluginPreviewResponse {
  plugins: PluginLaunchCandidate[];
  diagnostics?: PluginDiagnostic[];
  selectionErrors?: PluginSelectionError[];
}

export interface PluginRefParams {
  plugin: string;
  marketplace: string;
}

export interface PluginSelectionError {
  name: string;
  reason: string;
}

export interface PluginSetAutoUpgradeParams {
  plugin: string;
  marketplace: string;
  autoUpgrade: boolean;
}

export interface ProjectDeleteParams {
  key: string;
  workingDir: string;
}

export interface ProjectDeleteResponse {
  deleted: string[];
  skipped: ProjectDeleteSkip[];
  navigation: NavigationMutation;
}

export interface ProjectDeleteSkip {
  id: string;
  reason: string;
}

export interface ProjectsRecentParams {
  limit?: number;
}

export interface ProjectsRecentResponse {
  data: string[];
}

export interface ProviderDescriptor {
  id: string;
  name?: string;
  protocol: string;
  auth: string;
  varsEnv?: string[];
  apiKeyEnv?: string[];
  implicit: boolean;
}

export interface QueueState {
  depth?: number;
  revision: number;
  preview?: string[];
  ids?: string[];
  clientMutationIds?: string[];
  texts?: string[];
}

export interface ReasoningSummaryDeltaParams {
  threadId: string;
  ref: string;
  turnId: string;
  itemId: string;
  summaryIndex: number;
  delta: string;
}

export interface RepoLaunchConfigStatus {
  path: string;
  hash?: string;
  trust: string;
  preview?: string;
}

export interface SandboxEscalationRequested {
  threadId: string;
  ref: string;
  escalationId: string;
  mode: string;
  tool: string;
  kind: string;
  deniedPath: string;
  command?: string;
  outputSoFar?: string;
  partiallyRan?: boolean;
}

export interface SandboxEscalationResolveParams {
  threadId?: string;
  ref?: string;
  escalationId: string;
  approve: boolean;
}

export interface SandboxEscalationResolved {
  threadId: string;
  ref: string;
  escalationId: string;
}

export interface SearchParams {
  query?: string;
}

export interface SearchResponse {
  live: SearchResult[];
  past: SearchResult[];
}

export interface SearchResult {
  id: string;
  title: string;
  project: string;
  state: string;
  age: string;
  ref: string;
}

export interface ServerInfo {
  name: string;
  version: string;
}

export interface SessionDeleteParams {
  ref: string;
}

export interface SessionDeleteResponse {
  deleted: string[];
  skipped: DeletionSkip[];
  navigation: NavigationMutation;
}

export interface SessionPinAssignParams {
  sessionRef: string;
  sectionId?: string;
  sectionName?: string;
}

export interface SessionPinAssignResponse {
  ok: boolean;
  changed: boolean;
  assignment: SessionPinAssignment;
  navigation: NavigationMutation;
}

export interface SessionPinAssignment {
  sessionRef: string;
  section: PinSection;
}

export interface SessionPinUnpinAssignment {
  sessionRef: string;
}

export interface SessionPinUnpinParams {
  sessionRef: string;
}

export interface SessionPinUnpinResponse {
  ok: boolean;
  changed: boolean;
  assignment: SessionPinUnpinAssignment;
  navigation: NavigationMutation;
}

export interface SettingsAgentEntry {
  name: string;
  editPath?: string;
}

export interface SettingsCodexLaunchEntry {
  id: string;
  binary?: string;
  workingDir?: string;
  listen?: string;
  timeoutMillis?: number;
  envKeys?: string[];
}

export interface SettingsHubOverview {
  version?: string;
  commit?: string;
  listenAddr?: string;
  runDir?: string;
  spawnTimeout?: string;
  bearerTokenAge?: string;
  pastIndex?: SettingsPastIndexOverview;
}

export interface SettingsMCPOverview {
  servers?: SettingsMCPServerEntry[];
  error?: string;
}

export interface SettingsMCPServerEntry {
  name: string;
  transport?: string;
  status?: string;
  error?: string;
}

export interface SettingsOverviewResponse {
  hub?: SettingsHubOverview;
  storage?: SettingsStorageOverview;
  agents?: SettingsAgentEntry[];
  codexLaunches?: SettingsCodexLaunchEntry[];
  mcpDiscovered?: SettingsMCPOverview;
}

export interface SettingsPastIndexOverview {
  path?: string;
  size?: string;
  perPage?: number;
  count?: number;
}

export interface SettingsStorageOverview {
  stateDir?: string;
}

export interface Source {
  id: string;
  label: string;
  kind: string;
  online: boolean;
}

export interface TaskAggregate {
  total: number;
  done: number;
  current?: TaskSummary;
}

export interface TaskListParams {
  ref?: string;
}

export interface TaskListResponse {
  data: unknown;
}

export interface TaskSummary {
  id: number;
  description: string;
}

export interface TaskUpdatedParams {
  threadId: string;
  ref: string;
  total: number;
  done: number;
  current?: TaskSummary;
}

export interface Thread {
  id: string;
  sessionId: string;
  projectId?: string;
  projectPath?: string;
  forkedFromId?: string;
  preview: string;
  ephemeral: boolean;
  modelProvider: string;
  createdAt: number;
  updatedAt: number;
  status: ThreadStatus;
  path?: string;
  cwd: string;
  cliVersion: string;
  source: string;
  threadSource?: string;
  agentNickname?: string;
  agentRole?: string;
  gitInfo?: GitInfo;
  name?: string;
  turns?: Turn[];
  evener: EvenerThread;
}

export interface ThreadCapabilities {
  send: boolean;
  steer: boolean;
  interrupt: boolean;
  compact: boolean;
  clear: boolean;
  forkFromTurn: boolean;
  shutdown: boolean;
  changeModel: boolean;
  changeVisionModel: boolean;
  queue: boolean;
  goal: boolean;
  rename: boolean;
}

export interface ThreadClearParams {
  ref: string;
  clientMutationId: string;
  expectedInstanceId: string;
}

export interface ThreadClearResponse {
  thread: Thread;
  ref: string;
  receipt: MutationReceipt;
}

export interface ThreadClosedParams {
  threadId: string;
  ref: string;
  reason?: string;
}

export interface ThreadCompactStartParams {
  ref: string;
}

export interface ThreadForkParams {
  ref: string;
  sourceTurnId: string;
  editedInput?: string;
  label?: string;
  modelProvider?: string;
  model?: string;
  deferInput?: boolean;
  aside?: boolean;
}

export interface ThreadForkResponse {
  thread: Thread;
  originalInput?: string;
}

export interface ThreadItem {
  type: string;
  id: string;
  turnId?: string;
  transcriptEntryIndex?: number;
  text?: string;
  delta?: string;
  images?: InputItem[];
  toolName?: string;
  callId?: string;
  argumentsJson?: string;
  description?: string;
  output?: string;
  error?: string;
  outputImages?: OutputImage[];
  status?: string;
  prevalOnly?: boolean;
  startedAt?: number;
  completedAt?: number;
  durationMs?: number;
  exitCode?: number;
  raw?: unknown;
  eventKind?: ThreadItemEventKind;
  source?: string;
  steeringKind?: string;
  clientMutationId?: string;
}

export interface ThreadListParams {
  cursor?: string;
  limit?: number;
  sortKey?: string;
  sortDirection?: string;
  searchTerm?: string;
  statuses?: string[];
  sourceIds?: string[];
  includeSubagents?: boolean;
}

export interface ThreadListResponse {
  data: Thread[];
  nextCursor?: string;
  backwardsCursor?: string;
}

export interface ThreadModelChangedParams {
  threadId: string;
  ref: string;
  modelProvider: string;
  model: string;
  reasoningEffortLevels?: string[];
  supportsReasoning?: boolean;
}

export interface ThreadModelRetryParams {
  threadId: string;
  ref: string;
  turnId?: string;
  attempt: number;
  maxAttempts: number;
  delayMs: number;
  errorClass?: string;
  statusCode?: number;
  message?: string;
  model?: string;
  groupElapsedMs: number;
  attemptCap: number;
}

export interface ThreadModelSetParams {
  ref: string;
  modelProvider: string;
  model: string;
}

export interface ThreadNameChangedParams {
  threadId: string;
  ref: string;
  name: string;
  source?: string;
}

export interface ThreadNameSetParams {
  ref: string;
  name: string;
}

export interface ThreadQueueChangedParams {
  threadId: string;
  ref: string;
  queue: QueueState;
}

export interface ThreadReadParams {
  threadId?: string;
  ref?: string;
  includeTurns: boolean;
  itemsView?: string;
  subscribe?: boolean;
  replaceSubscription?: boolean;
  turnLimit?: number;
}

export interface ThreadReadResponse {
  thread: Thread;
  olderCursor?: string;
}

export interface ThreadReasoningEffortChangedParams {
  threadId: string;
  ref: string;
  reasoningEffort?: string;
}

export interface ThreadReasoningEffortSetParams {
  ref: string;
  reasoningEffort: string;
}

export interface ThreadResumeParams {
  ref?: string;
  sessionId?: string;
}

export interface ThreadResumeResponse {
  thread: Thread;
}

export interface ThreadResyncParams {
  threadId: string;
  ref: string;
}

export interface ThreadShutdownParams {
  ref: string;
}

export interface ThreadStartParams {
  harness?: string;
  cwd: string;
  input?: InputItem[];
  modelProvider?: string;
  model?: string;
  profile?: string;
  reasoningEffort?: string;
  nonInteractive?: boolean;
  launchOverrides?: LaunchConfigLayer;
}

export interface ThreadStartResponse {
  thread: Thread;
  turn: Turn;
}

export interface ThreadStartedParams {
  threadId: string;
  ref: string;
  thread: Thread;
}

export interface ThreadStatus {
  type: string;
  activeFlags?: string[];
}

export interface ThreadStatusChangedParams {
  threadId: string;
  ref: string;
  status: ThreadStatus;
  failedToolCalls?: number;
  capabilities?: ThreadCapabilities;
}

export interface ThreadTranscriptListParams {
  ref: string;
}

export interface ThreadTranscriptListResponse {
  data: ThreadTranscriptTarget[];
}

export interface ThreadTranscriptTarget {
  ref: string;
  threadId?: string;
  title: string;
  kind: string;
  status?: string;
  source?: string;
  turnsUsed?: number;
}

export interface ThreadTurnItemsListParams {
  threadId?: string;
  ref?: string;
  turnId: string;
  cursor?: string;
  limit?: number;
}

export interface ThreadTurnItemsListResponse {
  data: ThreadItem[];
  nextCursor?: string;
}

export interface ThreadTurnsListParams {
  threadId?: string;
  ref?: string;
  cursor?: string;
  limit?: number;
  itemsView?: string;
}

export interface ThreadTurnsListResponse {
  data: Turn[];
  nextCursor?: string;
}

export interface ThreadUnsubscribeParams {
  threadId?: string;
  ref?: string;
}

export interface ThreadVisionModelChangedParams {
  threadId: string;
  ref: string;
  visionModel: string;
}

export interface ThreadVisionModelSetParams {
  ref: string;
  visionModel: string;
}

export interface ToolOutputDeltaParams {
  threadId: string;
  ref: string;
  turnId?: string;
  itemId: string;
  callId: string;
  delta: string;
}

export interface TranscriptDisplayAdvanced {
  roundTimings: boolean;
  tokenCounts: boolean;
  estimatedCost: boolean;
  systemEvents: boolean;
  promptEvents: boolean;
  hookExits: string;
}

export interface TranscriptDisplayChangedParams {
  layout: string;
  revision: number;
  config: TranscriptDisplayConfig;
}

export interface TranscriptDisplayConfig {
  version: number;
  content: TranscriptDisplayContent;
  advanced: TranscriptDisplayAdvanced;
}

export interface TranscriptDisplayContent {
  kind: string;
  level?: string;
  custom?: TranscriptDisplayCustomContent;
}

export interface TranscriptDisplayCustomContent {
  toolIntent: boolean;
  toolCalls: boolean;
  reasoning: boolean;
  expandByDefault: boolean;
}

export interface TranscriptDisplayDefault {
  revision: number;
  config: TranscriptDisplayConfig;
}

export interface TranscriptDisplayDefaults {
  desktop: TranscriptDisplayDefault;
  mobile: TranscriptDisplayDefault;
}

export interface TranscriptDisplayDefaultsPatchParams {
  layout: string;
  expectedRevision: number;
  config: TranscriptDisplayConfig;
}

export interface TranscriptDisplayPatchResponse {
  layout: string;
  revision: number;
  config: TranscriptDisplayConfig;
}

export interface Turn {
  id: string;
  items?: ThreadItem[];
  itemsView: string;
  status: string;
  error?: TurnError;
  startedAt?: number;
  completedAt?: number;
  durationMs?: number;
  usage?: EvenerUsage;
  cost?: string;
}

export interface TurnCancelQueuedParams {
  ref: string;
  index: number;
  clientMutationId: string;
  expectedInstanceId: string;
  expectedEntryId: string;
}

export interface TurnCancelQueuedResponse {
  removedText: string;
  removedImages?: number;
  receipt: MutationReceipt;
}

export interface TurnCompletedParams {
  threadId: string;
  ref: string;
  turnId: string;
  turn: Turn;
}

export interface TurnDrainAsSteerParams {
  ref: string;
  clientMutationId: string;
  expectedInstanceId: string;
  expectedQueueRevision: number;
  input?: InputItem[];
}

export interface TurnDrainAsSteerResponse {
  receipt: MutationReceipt;
}

export interface TurnError {
  message: string;
  additionalDetails?: string;
  codexErrorInfo?: unknown;
  source?: string;
  title?: string;
  hint?: string;
  cause?: DiagnosticCause;
}

export interface TurnInterruptParams {
  ref?: string;
  threadId?: string;
  clientMutationId: string;
  expectedInstanceId: string;
}

export interface TurnInterruptResponse {
  receipt: MutationReceipt;
}

export interface TurnPromoteQueuedAsSteerParams {
  ref: string;
  index: number;
  clientMutationId: string;
  expectedInstanceId: string;
  expectedEntryId: string;
}

export interface TurnPromoteQueuedAsSteerResponse {
  receipt: MutationReceipt;
}

export interface TurnQueueParams {
  ref: string;
  clientMutationId: string;
  expectedInstanceId: string;
  input?: InputItem[];
}

export interface TurnQueueResponse {
  receipt: MutationReceipt;
}

export interface TurnStartParams {
  ref?: string;
  threadId?: string;
  clientMutationId: string;
  expectedInstanceId: string;
  input?: InputItem[];
}

export interface TurnStartResponse {
  turn: Turn;
  receipt: MutationReceipt;
}

export interface TurnStartedParams {
  threadId: string;
  ref: string;
  turn: Turn;
}

export interface TurnSteerParams {
  ref?: string;
  threadId?: string;
  clientMutationId: string;
  expectedInstanceId: string;
  input?: InputItem[];
}

export interface TurnSteerResponse {
  receipt: MutationReceipt;
}

export interface UpgradeParams {
  requested?: string;
}

export interface UpgradeResponse {
  release: string;
  channel: string;
  url: string;
  archive: string;
  prefix: string;
  binDir: string;
  shareBinDir: string;
  installed: string[];
  restartMessage: string;
}

export interface WarningParams {
  threadId: string;
  ref: string;
  message?: string;
  source?: string;
  title?: string;
  hint?: string;
  warning?: unknown;
  cause?: DiagnosticCause;
}

export const METHOD_NAMES = [
  "initialize",
  "ping",
  "thread/list",
  "thread/read",
  "thread/unsubscribe",
  "thread/turns/list",
  "thread/turns/items/list",
  "thread/start",
  "thread/resume",
  "thread/fork",
  "thread/clear",
  "thread/model/set",
  "evener/thread/name/set",
  "thread/reasoning-effort/set",
  "thread/vision-model/set",
  "thread/compact/start",
  "thread/shutdown",
  "turn/start",
  "turn/steer",
  "turn/interrupt",
  "turn/queue",
  "turn/drainAsSteer",
  "turn/promoteQueuedAsSteer",
  "turn/cancelQueued",
  "goal/set",
  "evener/tasks/list",
  "evener/jobs/list",
  "evener/jobs/output",
  "evener/thread/transcripts/list",
  "evener/subagentPreview",
  "evener/paths/complete",
  "evener/dirs/create",
  "evener/projects/recent",
  "evener/path/validate",
  "evener/git/head",
  "evener/mobile/pairing",
  "evener/navigation/read",
  "evener/favorite/set",
  "evener/archive/set",
  "evener/project/delete",
  "evener/session/delete",
  "evener/pin-section/rename",
  "evener/pin-section/delete",
  "evener/session-pin/assign",
  "evener/session-pin/unpin",
  "evener/search",
  "evener/harnesses/list",
  "evener/upgrade",
  "evener/auth/status",
  "evener/auth/test",
  "evener/auth/login/start",
  "evener/auth/login/complete",
  "evener/auth/logout",
  "evener/auth/list",
  "evener/auth/apiKey/set",
  "evener/auth/device/start",
  "evener/auth/device/poll",
  "evener/launch/resolve",
  "evener/launch/schema",
  "evener/launch/getLayer",
  "evener/launch/setLayer",
  "evener/launch/trustRepo",
  "model/list",
  "evener/instance/list",
  "evener/instance/create",
  "evener/instance/edit",
  "evener/instance/remove",
  "evener/instance/setDefault",
  "evener/plugin/checkNow",
  "evener/plugin/preview",
  "evener/marketplace/list",
  "evener/marketplace/add",
  "evener/marketplace/remove",
  "evener/marketplace/refresh",
  "evener/marketplace/browse",
  "evener/plugin/list",
  "evener/plugin/install",
  "evener/plugin/upgrade",
  "evener/plugin/remove",
  "evener/plugin/enable",
  "evener/plugin/disable",
  "evener/plugin/setAutoUpgrade",
  "evener/command/list",
  "evener/settings/overview",
  "evener/settings/transcriptDisplay/get",
  "evener/settings/transcriptDisplay/patch",
  "evener/sandbox/escalation/resolve",
] as const;

export type MethodName = (typeof METHOD_NAMES)[number];

export const NOTIFICATION_NAMES = [
  "thread/started",
  "thread/closed",
  "thread/status/changed",
  "thread/queueChanged",
  "evener/thread/name/changed",
  "thread/model/changed",
  "thread/reasoning-effort/changed",
  "thread/vision-model/changed",
  "turn/started",
  "turn/completed",
  "item/started",
  "item/completed",
  "item/agentMessage/delta",
  "item/agentMessage/reset",
  "item/reasoning/summaryTextDelta",
  "item/toolOutput/delta",
  "warning",
  "evener/thread/modelRetry",
  "evener/steering/injected",
  "evener/job/started",
  "evener/job/finished",
  "evener/delegate/updated",
  "evener/jobs/treeUpdated",
  "evener/auth/updated",
  "evener/launch/updated",
  "evener/attention/changed",
  "evener/navigation/invalidated",
  "evener/marketplace/updated",
  "evener/plugin/updated",
  "evener/thread/resync",
  "evener/task/updated",
  "evener/goal/updated",
  "evener/sandbox/escalation/requested",
  "evener/sandbox/escalation/resolved",
  "evener/settings/transcriptDisplay/changed",
] as const;

export type NotificationName = (typeof NOTIFICATION_NAMES)[number];

export const STEERING_KINDS = [
  "interrupted",
  "agent-message",
  "hook-context",
  "precompact-hook",
  "compact-nudge",
  "image-description",
  "no-tool-calls",
  "loop-detected",
  "tasks-done",
  "task-nudge",
  "task-inactive",
  "note-handoff",
  "goal-objective",
  "transcript-pointer",
  "current-task",
  "task-list",
  "notification",
  "provider-failure",
] as const;

export type SteeringKind = (typeof STEERING_KINDS)[number];

export const THREAD_ITEM_EVENT_KINDS = [
  "system_prompt",
  "plugin_loaded",
  "skill_activated",
  "hook_completed",
  "prompt_loaded",
  "context_compaction",
  "compaction",
  "turn_limit",
  "loop_detection",
  "goal_ended",
  "fork_summary",
  "round_timings",
  "tool_repair",
  "model_switch",
  "error",
  "environment",
] as const;

export type ThreadItemEventKind = (typeof THREAD_ITEM_EVENT_KINDS)[number];

export interface MethodTypes {
  "initialize": { params: InitializeParams; result: InitializeResponse };
  "ping": { params: EmptyParams; result: EmptyResponse };
  "thread/list": { params: ThreadListParams; result: ThreadListResponse };
  "thread/read": { params: ThreadReadParams; result: ThreadReadResponse };
  "thread/unsubscribe": { params: ThreadUnsubscribeParams; result: EmptyResponse };
  "thread/turns/list": { params: ThreadTurnsListParams; result: ThreadTurnsListResponse };
  "thread/turns/items/list": { params: ThreadTurnItemsListParams; result: ThreadTurnItemsListResponse };
  "thread/start": { params: ThreadStartParams; result: ThreadStartResponse };
  "thread/resume": { params: ThreadResumeParams; result: ThreadResumeResponse };
  "thread/fork": { params: ThreadForkParams; result: ThreadForkResponse };
  "thread/clear": { params: ThreadClearParams; result: ThreadClearResponse };
  "thread/model/set": { params: ThreadModelSetParams; result: EmptyResponse };
  "evener/thread/name/set": { params: ThreadNameSetParams; result: EmptyResponse };
  "thread/reasoning-effort/set": { params: ThreadReasoningEffortSetParams; result: EmptyResponse };
  "thread/vision-model/set": { params: ThreadVisionModelSetParams; result: EmptyResponse };
  "thread/compact/start": { params: ThreadCompactStartParams; result: EmptyResponse };
  "thread/shutdown": { params: ThreadShutdownParams; result: EmptyResponse };
  "turn/start": { params: TurnStartParams; result: TurnStartResponse };
  "turn/steer": { params: TurnSteerParams; result: TurnSteerResponse };
  "turn/interrupt": { params: TurnInterruptParams; result: TurnInterruptResponse };
  "turn/queue": { params: TurnQueueParams; result: TurnQueueResponse };
  "turn/drainAsSteer": { params: TurnDrainAsSteerParams; result: TurnDrainAsSteerResponse };
  "turn/promoteQueuedAsSteer": { params: TurnPromoteQueuedAsSteerParams; result: TurnPromoteQueuedAsSteerResponse };
  "turn/cancelQueued": { params: TurnCancelQueuedParams; result: TurnCancelQueuedResponse };
  "goal/set": { params: GoalSetParams; result: GoalSetResponse };
  "evener/tasks/list": { params: TaskListParams; result: TaskListResponse };
  "evener/jobs/list": { params: JobsListParams; result: JobsListResponse };
  "evener/jobs/output": { params: JobsOutputParams; result: JobsOutputResponse };
  "evener/thread/transcripts/list": { params: ThreadTranscriptListParams; result: ThreadTranscriptListResponse };
  "evener/subagentPreview": { params: EvenerSubagentPreviewParams; result: EvenerSubagentPreviewResponse };
  "evener/paths/complete": { params: PathsCompleteParams; result: PathsCompleteResponse };
  "evener/dirs/create": { params: DirsCreateParams; result: DirsCreateResponse };
  "evener/projects/recent": { params: ProjectsRecentParams; result: ProjectsRecentResponse };
  "evener/path/validate": { params: PathValidateParams; result: PathValidateResponse };
  "evener/git/head": { params: GitHeadParams; result: GitHeadResponse };
  "evener/mobile/pairing": { params: MobilePairingParams; result: MobilePairingResponse };
  "evener/navigation/read": { params: NavigationReadParams; result: NavigationReadResponse };
  "evener/favorite/set": { params: FavoriteSetParams; result: FavoriteSetResponse };
  "evener/archive/set": { params: ArchiveParams; result: ArchiveResponse };
  "evener/project/delete": { params: ProjectDeleteParams; result: ProjectDeleteResponse };
  "evener/session/delete": { params: SessionDeleteParams; result: SessionDeleteResponse };
  "evener/pin-section/rename": { params: PinSectionRenameParams; result: PinSectionRenameResponse };
  "evener/pin-section/delete": { params: PinSectionDeleteParams; result: PinSectionDeleteResponse };
  "evener/session-pin/assign": { params: SessionPinAssignParams; result: SessionPinAssignResponse };
  "evener/session-pin/unpin": { params: SessionPinUnpinParams; result: SessionPinUnpinResponse };
  "evener/search": { params: SearchParams; result: SearchResponse };
  "evener/harnesses/list": { params: HarnessListParams; result: HarnessListResponse };
  "evener/upgrade": { params: UpgradeParams; result: UpgradeResponse };
  "evener/auth/status": { params: AuthStatusParams; result: AuthStatusResponse };
  "evener/auth/test": { params: AuthTestParams; result: AuthTestResponse };
  "evener/auth/login/start": { params: AuthLoginStartParams; result: AuthLoginStartResponse };
  "evener/auth/login/complete": { params: AuthLoginCompleteParams; result: AuthLoginCompleteResponse };
  "evener/auth/logout": { params: AuthLogoutParams; result: AuthLogoutResponse };
  "evener/auth/list": { params: EmptyParams; result: AuthListResponse };
  "evener/auth/apiKey/set": { params: AuthApiKeySetParams; result: AuthStatusResponse };
  "evener/auth/device/start": { params: AuthDeviceStartParams; result: AuthDeviceStartResponse };
  "evener/auth/device/poll": { params: AuthDevicePollParams; result: AuthDevicePollResponse };
  "evener/launch/resolve": { params: LaunchConfigResolveParams; result: LaunchConfigResolved };
  "evener/launch/schema": { params: EmptyParams; result: LaunchOptionSchemaResponse };
  "evener/launch/getLayer": { params: LaunchConfigGetLayerParams; result: LaunchConfigLayer };
  "evener/launch/setLayer": { params: LaunchConfigSetLayerParams; result: LaunchConfigResolved };
  "evener/launch/trustRepo": { params: LaunchConfigTrustRepoParams; result: LaunchConfigResolved };
  "model/list": { params: ModelListParams; result: ModelListResponse };
  "evener/instance/list": { params: EmptyParams; result: InstanceListResponse };
  "evener/instance/create": { params: InstanceCreateParams; result: InstanceListResponse };
  "evener/instance/edit": { params: InstanceEditParams; result: InstanceListResponse };
  "evener/instance/remove": { params: InstanceRemoveParams; result: InstanceListResponse };
  "evener/instance/setDefault": { params: InstanceSetDefaultParams; result: InstanceListResponse };
  "evener/plugin/checkNow": { params: EmptyParams; result: PluginCheckNowResponse };
  "evener/plugin/preview": { params: PluginPreviewParams; result: PluginPreviewResponse };
  "evener/marketplace/list": { params: EmptyParams; result: MarketplaceListResponse };
  "evener/marketplace/add": { params: MarketplaceAddParams; result: MarketplaceListResponse };
  "evener/marketplace/remove": { params: MarketplaceNameParams; result: MarketplaceListResponse };
  "evener/marketplace/refresh": { params: MarketplaceNameParams; result: MarketplaceListResponse };
  "evener/marketplace/browse": { params: MarketplaceBrowseParams; result: MarketplaceBrowseResponse };
  "evener/plugin/list": { params: EmptyParams; result: PluginListResponse };
  "evener/plugin/install": { params: PluginRefParams; result: PluginListResponse };
  "evener/plugin/upgrade": { params: PluginRefParams; result: PluginListResponse };
  "evener/plugin/remove": { params: PluginRefParams; result: PluginListResponse };
  "evener/plugin/enable": { params: PluginRefParams; result: PluginListResponse };
  "evener/plugin/disable": { params: PluginRefParams; result: PluginListResponse };
  "evener/plugin/setAutoUpgrade": { params: PluginSetAutoUpgradeParams; result: PluginListResponse };
  "evener/command/list": { params: EmptyParams; result: CommandListResponse };
  "evener/settings/overview": { params: EmptyParams; result: SettingsOverviewResponse };
  "evener/settings/transcriptDisplay/get": { params: EmptyParams; result: TranscriptDisplayDefaults };
  "evener/settings/transcriptDisplay/patch": { params: TranscriptDisplayDefaultsPatchParams; result: TranscriptDisplayPatchResponse };
  "evener/sandbox/escalation/resolve": { params: SandboxEscalationResolveParams; result: EmptyResponse };
}

export interface NotificationTypes {
  "thread/started": ThreadStartedParams;
  "thread/closed": ThreadClosedParams;
  "thread/status/changed": ThreadStatusChangedParams;
  "thread/queueChanged": ThreadQueueChangedParams;
  "evener/thread/name/changed": ThreadNameChangedParams;
  "thread/model/changed": ThreadModelChangedParams;
  "thread/reasoning-effort/changed": ThreadReasoningEffortChangedParams;
  "thread/vision-model/changed": ThreadVisionModelChangedParams;
  "turn/started": TurnStartedParams;
  "turn/completed": TurnCompletedParams;
  "item/started": ItemLifecycleParams;
  "item/completed": ItemLifecycleParams;
  "item/agentMessage/delta": AgentMessageDeltaParams;
  "item/agentMessage/reset": AgentMessageResetParams;
  "item/reasoning/summaryTextDelta": ReasoningSummaryDeltaParams;
  "item/toolOutput/delta": ToolOutputDeltaParams;
  "warning": WarningParams;
  "evener/thread/modelRetry": ThreadModelRetryParams;
  "evener/steering/injected": EvenerSteeringInjectedParams;
  "evener/job/started": EvenerJobParams;
  "evener/job/finished": EvenerJobParams;
  "evener/delegate/updated": EvenerDelegateParams;
  "evener/jobs/treeUpdated": JobsTreeUpdatedParams;
  "evener/auth/updated": EvenerAuthUpdatedParams;
  "evener/launch/updated": EvenerLaunchUpdatedParams;
  "evener/attention/changed": AttentionChangedPayload;
  "evener/navigation/invalidated": NavigationInvalidatedPayload;
  "evener/marketplace/updated": EmptyParams;
  "evener/plugin/updated": EmptyParams;
  "evener/thread/resync": ThreadResyncParams;
  "evener/task/updated": TaskUpdatedParams;
  "evener/goal/updated": GoalUpdatedParams;
  "evener/sandbox/escalation/requested": SandboxEscalationRequested;
  "evener/sandbox/escalation/resolved": SandboxEscalationResolved;
  "evener/settings/transcriptDisplay/changed": TranscriptDisplayChangedParams;
}

export type AnyNotification = { [K in NotificationName]: { method: K; params: NotificationTypes[K] } }[NotificationName];
