package launchconfig

import "testing"

// FuzzLaunchConfigBehaviorProgram replays one deterministic behavioral contract selected by the
// fuzz input. The seed corpus covers every production branch; mutation varies
// ordering and repetition without relying on network, wall clock, or host state.
func FuzzLaunchConfigBehaviorProgram(f *testing.F) {
	checks := []func(*testing.T){
		checkToEnv_BaselineSetsRunStateAndProvider,
		checkToEnv_PerLaunchEnvBeatsCredsStore,
		checkToEnv_OpenAICompatibleCredentialUsesAPIKeyEnv,
		checkToEnv_NoProviderNoInjection,
		checkToEnv_OpenAIStoredKeyInjectsOpenAIAPIKey,
		checkToEnv_ProvidersConfigPathSetsEnvVar,
		checkToEnv_NoProvidersConfigPathDoesNotSetEnvVar,
		checkToEnv_RawHTTPLoggingSetsRawLogEnv,
		checkToEnv_RawHTTPLoggingFalseOverridesInheritedEnv,
		checkToEnv_RawHTTPLoggingUnsetPreservesInheritedEnv,
		checkPathsFor_MetaAndLegacyProjectKeyedByStableRoot,
		checkResolve_TrustFromMainRootAppliesInLinkedWorktree,
		checkFromWire,
		checkToWire,
		checkToWirePreservesExplicitEmptyModelFallbacks,
		checkWire_SystemPromptAndDebugFieldsRoundTrip,
		checkWire_SandboxRoundTrips,
		checkWireOmitsUnsetModelFallbacks,
		checkResolvedToWire,
		checkLaunchConfigLayer_ConfigPlumbingRoundtrip,
		checkToWire_WithSchemaAndMCPs,
		checkToWire_NonNilPtrToNilSliceClears,
		checkWriteAtomicFSFailuresRemoveTemporaryFile,
		checkValidateRepoRelativePathResolutionError,
		checkDecodeTrustedRepoLayerError,
		checkCanonicalHashEncodeError,
		checkMergeAdditionalLaunchFields,
		checkResolveProjectLoadError,
		checkLoadProjectLayerLegacyStatError,
		checkComputeTrustStateUnknownDecision,
		checkLayerTOMLRoundTrip,
		checkLayerOmitEmptyOnEncode,
		checkToArgs_AllFields,
		checkToArgs_InlinePromptTextDoesNotEmitArgv,
		checkToArgs_SkipsUnset,
		checkToArgs_Sandbox,
		checkToArgs_BoolFalseDoesNotEmitFlag,
		checkCanonicalHash_StableAcrossWhitespace,
		checkCanonicalHash_DetectsSemanticChange,
		checkCanonicalHash_DistinguishesExplicitEmptyModelFallbacks,
		checkComputeTrustState,
		checkLaunchOptionSchema_FieldCoverage,
		checkLaunchOptionSchema_OpenAIResponsesContinuation,
		checkLaunchOptionSchema_ExportATIFProviderHandles,
		checkLaunchOptionSchema_Sandbox,
		checkLaunchOptionSchema_RawHTTPLoggingIsDebugLaunchSetting,
		checkLaunchOptionSchema_GroupOrder,
		checkLaunchOptionSchema_ExclusionsAreExplicit,
		checkContextChoices_NoRecall,
		checkResolve_LayersMerge,
		checkResolve_LegacyProjectLayerFallback,
		checkResolve_ProjectLayerPrefersLocalFileOverLegacy,
		checkResolve_UntrustedRepoSkipped,
		checkResolve_RejectedRepoSkippedSilently,
		checkResolve_RepoPathsExpandedAndValidated,
		checkResolve_GlobalProjectInvalidPathsReportDiagnostics,
		checkLoadProjectLayer_StatError,
		checkLoadProjectLayer_LegacyLoadError,
		checkLoadRepoLayer_ReadFileError,
		checkValidateAndExpandRepoLayer_InvalidPaths,
		checkPathsFor,
		checkValidateRepoPath,
		checkValidateAbsolutePath,
		checkMerge_ScalarPrecedence,
		checkMerge_Sandbox,
		checkMerge_SandboxNetWithoutModeDiagnostic,
		checkMerge_UnknownSandboxModeDiagnostic,
		checkMerge_ScalarPointerSemantics,
		checkMergeLayers_SystemPromptModesOverrideByLayer,
		checkMergeLayers_LegacySystemPromptAppendMigratesOneEntry,
		checkMergeLayers_LegacySystemPromptAppendMultiEntryUsesFirstWithDiagnostic,
		checkMergeLayers_ExplicitAppendModeBeatsLegacyAppendSameLayer,
		checkMerge_ListAppendInLayerOrder,
		checkMerge_EnvMapLastWriteWins,
		checkMerge_MCPsAppendWithDuplicateDiagnostic,
		checkMerge_ModelFallbacksReplaceNotAppend,
		checkMerge_ModelFallbacksGlobalOnly,
		checkMerge_EmptyModelFallbacksClearsInherited,
		checkMerge_BlockedCredentialEnvKeys,
		checkMerge_CoversRemainingScalarAndListFields,
		checkMerge_AppReplaySizeNonGlobalDiagnostic,
		checkMerge_AppReplaySizeGlobalApplied,
		checkIsCredentialEnvKey,
		checkLoadLayer_Missing,
		checkLoadLayer_Parses,
		checkLoadLayer_TracksExplicitEmptyModelFallbacks,
		checkSaveLayer_AtomicAndPermissions,
		checkSaveLayer_PersistsExplicitEmptyModelFallbacks,
		checkSaveMeta_AtomicAndPermissions,
		checkLoadLayer_ReadError,
		checkLoadLayer_ParseError,
		checkLoadMeta_ReadError,
		checkLoadMeta_ParseError,
		checkSaveLayer_WriteError,
		checkSaveMeta_WriteError,
		checkSaveLayer_MkdirAllError,
		checkSaveMeta_MkdirAllError,
		checkSaveLayer_RenameError,
		checkSaveMeta_RenameError,
		checkLaunchConfigThreeStateRoundTrip,
	}
	for i := range checks {
		f.Add(uint8(i))
	}
	f.Fuzz(func(t *testing.T, selector uint8) {
		checks[int(selector)%len(checks)](t)
	})
}
