package main

import (
	"encoding/json"
	"fmt"
	"reflect"
	"sort"
	"strings"
	"time"

	"primeradiant.com/serf/agent/events"
	"primeradiant.com/serf/appwire"
)

// generatedHeader marks types.gen.ts as generated so editors and reviewers
// don't hand-edit it; the drift test (TestGeneratedFileCurrent) is the real
// enforcement.
const generatedHeader = "// Code generated by internal/appwirets; DO NOT EDIT. Run make generate.\n"

// rawMessageType and timeTimeType get mapping rules of their own instead of
// the generic named-struct-recursion rule: json.RawMessage's fields are
// encoding/json internals, not wire shape, and time.Time never appears in
// the AppWire catalog today (timestamps ride as Unix-epoch int64) but is
// mapped defensively per the appwirets task brief.
var (
	rawMessageType          = reflect.TypeFor[json.RawMessage]()
	timeTimeType            = reflect.TypeFor[time.Time]()
	threadItemEventKindType = reflect.TypeFor[appwire.ThreadItemEventKind]()
)

// isOpaqueStruct reports whether t is a struct-kind type the registry must
// not walk into and independently register — today, only time.Time (its
// fields are encoding/json-invisible implementation detail: unexported wall/
// ext/loc). json.RawMessage does not belong in this check: its Kind is
// Slice, so registry.discover never reaches the Struct case for it at all —
// typeExpr's own t == rawMessageType case maps it directly instead.
func isOpaqueStruct(t reflect.Type) bool {
	return t == timeTimeType
}

// rawField is one JSON-visible field of a struct, midway between reflection
// and TypeScript rendering: the wire name and omitempty bit are resolved,
// but the type is still a reflect.Type so callers can either stringify it
// (emitInterface) or walk it for further named types to register (registry).
type rawField struct {
	json      string
	elemType  reflect.Type // pointer already stripped
	isPointer bool
	optional  bool // omitempty
}

// rawFieldsOf returns t's JSON-visible fields in declaration order,
// flattening anonymous embedded structs inline: an embedded field with no
// explicit tag name contributes its own fields directly to the parent,
// matching encoding/json. Unexported fields and json:"-" fields are skipped.
func rawFieldsOf(t reflect.Type) []rawField {
	if t == nil || t.Kind() != reflect.Struct {
		return nil
	}
	var out []rawField
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if !f.IsExported() {
			continue
		}
		name, opts, _ := strings.Cut(f.Tag.Get("json"), ",")
		if name == "-" {
			continue
		}
		ft := f.Type
		isPointer := ft.Kind() == reflect.Pointer
		for ft.Kind() == reflect.Pointer {
			ft = ft.Elem()
		}
		if f.Anonymous && name == "" && ft.Kind() == reflect.Struct {
			out = append(out, rawFieldsOf(ft)...)
			continue
		}
		if name == "" {
			name = f.Name
		}
		out = append(out, rawField{
			json:      name,
			elemType:  ft,
			isPointer: isPointer,
			optional:  strings.Contains(opts, "omitempty"),
		})
	}
	return out
}

// typeExpr returns the TypeScript type expression for t (a field's element
// type, already stripped of any top-level pointer by the caller). A named
// struct is referenced by its Go name only — discovering that struct and
// scheduling its own interface for emission is the registry's job, not
// this function's.
func typeExpr(t reflect.Type) string {
	switch {
	case t == threadItemEventKindType:
		return "ThreadItemEventKind"
	case t == rawMessageType:
		return "unknown"
	case t == timeTimeType:
		return "string"
	case t.Kind() == reflect.Interface:
		return "unknown"
	case t.Kind() == reflect.String:
		return "string"
	case t.Kind() == reflect.Bool:
		return "boolean"
	case isNumericKind(t.Kind()):
		return "number"
	case t.Kind() == reflect.Pointer:
		return typeExpr(t.Elem())
	case t.Kind() == reflect.Slice:
		if t.Elem().Kind() == reflect.Uint8 {
			return "string" // []byte marshals as a base64 JSON string
		}
		return typeExpr(t.Elem()) + "[]"
	case t.Kind() == reflect.Map:
		return "Record<" + typeExpr(t.Key()) + ", " + typeExpr(t.Elem()) + ">"
	case t.Kind() == reflect.Struct:
		if t.Name() == "" {
			panic("appwirets: anonymous struct type has no name to reference: " + t.String())
		}
		return t.Name()
	default:
		panic(fmt.Sprintf("appwirets: unsupported field kind %s (%s) has no TS mapping rule", t.Kind(), t.String()))
	}
}

func isNumericKind(k reflect.Kind) bool {
	switch k {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return true
	default:
		return false
	}
}

// emitInterface renders one TS interface for the named Go struct type t. t
// is nil for a notification payload with no dedicated Go type (see
// appwire.Notifications' doc comment on a nil Payload); that renders as an
// empty interface body, since no field data exists to reflect.
func emitInterface(name string, t reflect.Type) string {
	var b strings.Builder
	fmt.Fprintf(&b, "export interface %s {\n", name)
	for _, f := range rawFieldsOf(t) {
		tsType := typeExpr(f.elemType)
		if f.isPointer && !f.optional {
			tsType += " | null"
		}
		optMark := ""
		if f.optional {
			optMark = "?"
		}
		fmt.Fprintf(&b, "  %s%s: %s;\n", f.json, optMark, tsType)
	}
	b.WriteString("}\n")
	return b.String()
}

// registry accumulates named TS interfaces discovered while walking the
// catalog, keyed by name, so each is emitted exactly once regardless of how
// many methods/notifications/fields reference it.
type registry struct {
	order []string
	types map[string]reflect.Type
}

func newRegistry() *registry {
	return &registry{types: map[string]reflect.Type{}}
}

func (r *registry) has(name string) bool {
	_, ok := r.types[name]
	return ok
}

// addNamed registers t under name if not already present, then walks its
// fields to discover further nested named types transitively. t is nil for
// a notification payload with no dedicated Go type.
func (r *registry) addNamed(name string, t reflect.Type) {
	if r.has(name) {
		return
	}
	r.types[name] = t
	r.order = append(r.order, name)
	for _, f := range rawFieldsOf(t) {
		r.discover(f.elemType)
	}
}

// discover finds named struct types reachable from t (through slice/map
// elements) and registers each via addNamed. Kinds with no nested named
// type to find (string, number, bool, unknown) are ignored.
func (r *registry) discover(t reflect.Type) {
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	switch t.Kind() {
	case reflect.Slice, reflect.Array:
		r.discover(t.Elem())
	case reflect.Map:
		r.discover(t.Key())
		r.discover(t.Elem())
	case reflect.Struct:
		if isOpaqueStruct(t) {
			return
		}
		if t.Name() == "" {
			panic("appwirets: anonymous struct type has no name to register: " + t.String())
		}
		r.addNamed(t.Name(), t)
	}
}

// deriveName synthesizes a PascalCase TS type name from a wire name (e.g.
// "thread/started") and a suffix (e.g. "Payload"): "ThreadStartedPayload".
// Both "/" and "-" are word boundaries — "thread/reasoning-effort/set"
// segments the same way the catalog's own ThreadReasoningEffortSetParams
// does — since a "-" left in place would produce an invalid TS identifier
// (subtraction is not valid inside `export interface Name {`). Used only
// when a catalog entry has no dedicated Go type to name itself after —
// today that is exactly the notifications with a nil Payload (an inline
// object at the projector; see appwire.Notifications' doc comment).
func deriveName(wireName, suffix string) string {
	var b strings.Builder
	for _, seg := range strings.FieldsFunc(wireName, isNameBoundary) {
		b.WriteString(strings.ToUpper(seg[:1]))
		b.WriteString(seg[1:])
	}
	b.WriteString(suffix)
	return b.String()
}

func isNameBoundary(r rune) bool {
	return r == '/' || r == '-'
}

// registerTopLevel registers a catalog entry's Params/Result/Payload value v
// — nil for a notification with no dedicated Go type — into reg, using v's
// own Go type name when it has one, else the wire-derived fallbackName, and
// returns the name used.
func registerTopLevel(reg *registry, v any, fallbackName string) string {
	t := reflect.TypeOf(v)
	for t != nil && t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	name := fallbackName
	if t != nil && t.Name() != "" {
		name = t.Name()
	}
	reg.addNamed(name, t)
	return name
}

// writeNameCatalog emits a wire-name catalog as a runtime value plus the
// type derived from it:
//
//	export const <constName> = [\n  "a",\n  "b",\n] as const;
//	export type <typeName> = (typeof <constName>)[number];
//
// A type-only union would vanish at runtime, leaving the test doubles in
// protocol/testing/ nothing to validate a scripted name against; deriving
// the type from the value keeps the two from ever disagreeing.
func writeNameCatalog(b *strings.Builder, constName, typeName string, names []string) {
	fmt.Fprintf(b, "export const %s = [\n", constName)
	for _, name := range names {
		fmt.Fprintf(b, "  %q,\n", name)
	}
	b.WriteString("] as const;\n\n")
	fmt.Fprintf(b, "export type %s = (typeof %s)[number];\n\n", typeName, constName)
}

type methodEntry struct {
	name   string
	params string
	result string
}

type notificationEntry struct {
	name    string
	payload string
}

// EmitCatalog renders the full types.gen.ts from the appwire catalog. It
// walks appwire.Methods and appwire.Notifications, collecting every
// reachable named type, emits an interface for each (alphabetical, once
// each), then the MethodName/NotificationName unions and the
// MethodTypes/NotificationTypes/AnyNotification lookup tables (catalog
// order, matching internal/appwiredoc's convention for its own doc tables).
func EmitCatalog() string {
	reg := newRegistry()

	methods := make([]methodEntry, 0, len(appwire.Methods))
	for _, m := range appwire.Methods {
		methods = append(methods, methodEntry{
			name:   m.Name,
			params: registerTopLevel(reg, m.Params, deriveName(m.Name, "Params")),
			result: registerTopLevel(reg, m.Result, deriveName(m.Name, "Result")),
		})
	}

	notifications := make([]notificationEntry, 0, len(appwire.Notifications))
	for _, n := range appwire.Notifications {
		notifications = append(notifications, notificationEntry{
			name:    n.Name,
			payload: registerTopLevel(reg, n.Payload, deriveName(n.Name, "Payload")),
		})
	}

	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("\n")

	names := append([]string(nil), reg.order...)
	sort.Strings(names)
	for _, name := range names {
		b.WriteString(emitInterface(name, reg.types[name]))
		b.WriteString("\n")
	}

	methodNames := make([]string, len(methods))
	for i, m := range methods {
		methodNames[i] = m.name
	}
	writeNameCatalog(&b, "METHOD_NAMES", "MethodName", methodNames)

	notificationNames := make([]string, len(notifications))
	for i, n := range notifications {
		notificationNames[i] = n.name
	}
	writeNameCatalog(&b, "NOTIFICATION_NAMES", "NotificationName", notificationNames)

	writeNameCatalog(&b, "STEERING_KINDS", "SteeringKind", events.AllSteeringKinds)
	writeNameCatalog(&b, "THREAD_ITEM_EVENT_KINDS", "ThreadItemEventKind", appwire.AllThreadItemEventKinds)

	b.WriteString("export interface MethodTypes {\n")
	for _, m := range methods {
		fmt.Fprintf(&b, "  %q: { params: %s; result: %s };\n", m.name, m.params, m.result)
	}
	b.WriteString("}\n\n")

	b.WriteString("export interface NotificationTypes {\n")
	for _, n := range notifications {
		fmt.Fprintf(&b, "  %q: %s;\n", n.name, n.payload)
	}
	b.WriteString("}\n\n")

	b.WriteString("export type AnyNotification = { [K in NotificationName]: { method: K; params: NotificationTypes[K] } }[NotificationName];\n")

	return b.String()
}
