package main

import (
	"encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"sort"
	"strings"
	"time"

	"primeradiant.com/evener/agent/events"
	"primeradiant.com/evener/appwire"
	"primeradiant.com/evener/hubapi"
)

// generatedHeader marks types.gen.ts as generated so editors and reviewers
// don't hand-edit it; the drift test (TestGeneratedFileCurrent) is the real
// enforcement.
const generatedHeader = "// Code generated by internal/appwirets; DO NOT EDIT. Run make generate.\n"

// rawMessageType and timeTimeType get mapping rules of their own instead of
// the generic named-struct-recursion rule: json.RawMessage's fields are
// encoding/json internals, not wire shape, and time.Time never appears in
// the AppWire catalog today (timestamps ride as Unix-epoch int64) but is
// mapped defensively per the appwirets task brief.
var (
	rawMessageType           = reflect.TypeFor[json.RawMessage]()
	timeTimeType             = reflect.TypeFor[time.Time]()
	threadItemEventKindType  = reflect.TypeFor[appwire.ThreadItemEventKind]()
	navigationTargetKindType = reflect.TypeFor[appwire.NavigationTargetKind]()
)

// isOpaqueStruct reports whether t is a struct-kind type the registry must
// not walk into and independently register — today, only time.Time (its
// fields are encoding/json-invisible implementation detail: unexported wall/
// ext/loc). json.RawMessage does not belong in this check: its Kind is
// Slice, so registry.discover never reaches the Struct case for it at all —
// typeExpr's own t == rawMessageType case maps it directly instead.
func isOpaqueStruct(t reflect.Type) bool {
	return t == timeTimeType
}

// rawField is one JSON-visible field of a struct, midway between reflection
// and TypeScript rendering: the wire name and omitempty bit are resolved,
// but the type is still a reflect.Type so callers can either stringify it
// (emitInterface) or walk it for further named types to register (registry).
type rawField struct {
	json      string
	elemType  reflect.Type // pointer already stripped
	isPointer bool
	optional  bool // omitempty
	// doc is the Go doc comment above the field, verbatim lines joined by
	// "\n", or "" when the field is undocumented. reflect.Type carries no
	// comments, so fieldDoc reads it back out of the Go source.
	doc string
}

// rawFieldsOf returns t's JSON-visible fields in declaration order,
// flattening anonymous embedded structs inline: an embedded field with no
// explicit tag name contributes its own fields directly to the parent,
// matching encoding/json. Unexported fields and json:"-" fields are skipped.
func rawFieldsOf(t reflect.Type) []rawField {
	if t == nil || t.Kind() != reflect.Struct {
		return nil
	}
	var out []rawField
	for f := range t.Fields() {
		if !f.IsExported() {
			continue
		}
		name, opts, _ := strings.Cut(f.Tag.Get("json"), ",")
		if name == "-" {
			continue
		}
		ft := f.Type
		isPointer := ft.Kind() == reflect.Pointer
		for ft.Kind() == reflect.Pointer {
			ft = ft.Elem()
		}
		if f.Anonymous && name == "" && ft.Kind() == reflect.Struct {
			out = append(out, rawFieldsOf(ft)...)
			continue
		}
		if name == "" {
			name = f.Name
		}
		out = append(out, rawField{
			json:      name,
			elemType:  ft,
			isPointer: isPointer,
			// omitzero omits only the zero value, so a tagged field can still
			// be absent from a frame and is optional to a client just as an
			// omitempty one is. The two differ in what they send for an empty
			// slice, not in whether the key can be missing.
			optional: strings.Contains(opts, "omitempty") || strings.Contains(opts, "omitzero"),
			doc:      fieldDoc(t.PkgPath(), t.Name(), f.Name),
		})
	}
	return out
}

// modulePath is this module's import-path prefix. The catalog's wire types all
// live in this module (appwire, hubapi, events), so packageDir can turn a
// reflect.Type's PkgPath into a source directory.
const modulePath = "primeradiant.com/evener"

// parsedFieldDocs caches parsed doc comments per package import path: type
// name -> field Go name -> comment text. A present key with a nil value is a
// package whose comments were already looked for and are simply absent (or
// unreadable), so a miss is not re-parsed. Parsing is lazy and one package is
// read at most once per process, which keeps EmitCatalog deterministic.
var parsedFieldDocs = map[string]map[string]map[string]string{}

// fieldDoc returns the doc comment text for a struct field, or "" when the
// field, type, or package has none. pkgPath, typeName, and fieldName come from
// reflection, so a type defined in a test's own package (pkgPath "main") has no
// source under the module and resolves to "" — undocumented test types must
// keep emitting byte-identically.
func fieldDoc(pkgPath, typeName, fieldName string) string {
	if pkgPath == "" || typeName == "" {
		return ""
	}
	docs, ok := parsedFieldDocs[pkgPath]
	if !ok {
		docs = parsePackageFieldDocs(pkgPath)
		parsedFieldDocs[pkgPath] = docs
	}
	return docs[typeName][fieldName]
}

// parsePackageFieldDocs parses every non-test .go file in pkgPath's directory
// and records the doc comment on each named struct's fields. A package that
// cannot be located or read yields an empty map rather than an error: a missing
// comment is not a codegen failure.
func parsePackageFieldDocs(pkgPath string) map[string]map[string]string {
	dir, ok := packageDir(pkgPath)
	if !ok {
		return nil
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil
	}
	result := map[string]map[string]string{}
	fset := token.NewFileSet()
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		file, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.ParseComments)
		if err != nil {
			continue
		}
		collectStructFieldDocs(file, result)
	}
	return result
}

// collectStructFieldDocs records field.Doc from every named struct type
// declaration in file. Embedded fields carry no names of their own, so their
// flattened fields take their comment from the embedded type's own declaration
// during rawFieldsOf's recursion.
func collectStructFieldDocs(file *ast.File, result map[string]map[string]string) {
	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}
		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok || structType.Fields == nil {
				continue
			}
			for _, field := range structType.Fields.List {
				if field.Doc == nil {
					continue
				}
				fields := result[typeSpec.Name.Name]
				if fields == nil {
					fields = map[string]string{}
					result[typeSpec.Name.Name] = fields
				}
				for _, name := range field.Names {
					fields[name.Name] = commentText(field.Doc)
				}
			}
		}
	}
}

// commentText flattens a comment group to its text, one line per source line,
// dropping the "//" or "/* */" markers and the conventional leading space.
func commentText(group *ast.CommentGroup) string {
	var lines []string
	for _, comment := range group.List {
		if text, ok := strings.CutPrefix(comment.Text, "//"); ok {
			lines = append(lines, strings.TrimPrefix(text, " "))
			continue
		}
		text := strings.TrimSuffix(strings.TrimPrefix(comment.Text, "/*"), "*/")
		for line := range strings.SplitSeq(text, "\n") {
			lines = append(lines, strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(line), "*")))
		}
	}
	return strings.Join(lines, "\n")
}

// packageDir resolves a module import path to its source directory.
func packageDir(pkgPath string) (string, bool) {
	if pkgPath != modulePath && !strings.HasPrefix(pkgPath, modulePath+"/") {
		return "", false
	}
	root, ok := moduleRoot()
	if !ok {
		return "", false
	}
	rel := strings.TrimPrefix(strings.TrimPrefix(pkgPath, modulePath), "/")
	return filepath.Join(root, filepath.FromSlash(rel)), true
}

// moduleRoot finds the directory of this module's go.mod. It walks up from the
// working directory first: that path is always real, whereas this file's own
// compiled-in path is module-relative under `-trimpath` (a build flag this
// repo's shard runner forwards), which would make a runtime.Caller-only
// resolver silently find no sources and strip every JSDoc comment.
func moduleRoot() (string, bool) {
	if wd, err := os.Getwd(); err == nil {
		if root, ok := findModuleRoot(wd); ok {
			return root, true
		}
	}
	_, file, _, ok := runtime.Caller(0)
	if !ok || !filepath.IsAbs(file) {
		return "", false
	}
	return findModuleRoot(filepath.Dir(file))
}

// findModuleRoot walks up from dir to the nearest directory whose go.mod
// declares this module, so a nested module on the way up (the repo has one
// under agent/) is skipped rather than mistaken for the root.
func findModuleRoot(dir string) (string, bool) {
	if abs, err := filepath.Abs(dir); err == nil {
		dir = abs
	}
	for {
		if data, err := os.ReadFile(filepath.Join(dir, "go.mod")); err == nil && declaresModule(data) {
			return dir, true
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", false
		}
		dir = parent
	}
}

func declaresModule(goMod []byte) bool {
	for line := range strings.SplitSeq(string(goMod), "\n") {
		if fields := strings.Fields(line); len(fields) == 2 && fields[0] == "module" && fields[1] == modulePath {
			return true
		}
	}
	return false
}

// writeFieldDoc emits doc as an indented JSDoc block above a field, or nothing
// when doc is empty. Silence for an empty comment is what keeps types.gen.ts
// byte-identical for undocumented fields.
func writeFieldDoc(b *strings.Builder, doc string) {
	if doc == "" {
		return
	}
	b.WriteString("  /**\n")
	for line := range strings.SplitSeq(doc, "\n") {
		if line == "" {
			b.WriteString("   *\n")
			continue
		}
		fmt.Fprintf(b, "   * %s\n", strings.ReplaceAll(line, "*/", `*\/`))
	}
	b.WriteString("   */\n")
}

// typeExpr returns the TypeScript type expression for t (a field's element
// type, already stripped of any top-level pointer by the caller). A named
// struct is referenced by its Go name only — discovering that struct and
// scheduling its own interface for emission is the registry's job, not
// this function's.
func typeExpr(t reflect.Type) string {
	switch {
	case t == threadItemEventKindType:
		return "ThreadItemEventKind"
	case t == navigationTargetKindType:
		return navigationTargetKindTypeExpr()
	case t == rawMessageType:
		return "unknown"
	case t == timeTimeType:
		return "string"
	case t.Kind() == reflect.Interface:
		return "unknown"
	case t.Kind() == reflect.String:
		return "string"
	case t.Kind() == reflect.Bool:
		return "boolean"
	case isNumericKind(t.Kind()):
		return "number"
	case t.Kind() == reflect.Pointer:
		return typeExpr(t.Elem())
	case t.Kind() == reflect.Slice:
		if t.Elem().Kind() == reflect.Uint8 {
			return "string" // []byte marshals as a base64 JSON string
		}
		return typeExpr(t.Elem()) + "[]"
	case t.Kind() == reflect.Map:
		return "Record<" + typeExpr(t.Key()) + ", " + typeExpr(t.Elem()) + ">"
	case t.Kind() == reflect.Struct:
		if t.Name() == "" {
			panic("appwirets: anonymous struct type has no name to reference: " + t.String())
		}
		return t.Name()
	default:
		panic(fmt.Sprintf("appwirets: unsupported field kind %s (%s) has no TS mapping rule", t.Kind(), t.String()))
	}
}

func navigationTargetKindTypeExpr() string {
	kinds := make([]string, len(appwire.AllNavigationTargetKinds))
	for i, kind := range appwire.AllNavigationTargetKinds {
		kinds[i] = fmt.Sprintf("%q", kind)
	}
	return strings.Join(kinds, " | ")
}

func isNumericKind(k reflect.Kind) bool {
	switch k {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return true
	default:
		return false
	}
}

// emitInterface renders one TS interface for the named Go struct type t. t
// is nil for a notification payload with no dedicated Go type (see
// appwire.Notifications' doc comment on a nil Payload); that renders as an
// empty interface body, since no field data exists to reflect.
func emitInterface(name string, t reflect.Type) string {
	var b strings.Builder
	fmt.Fprintf(&b, "export interface %s {\n", name)
	for _, f := range rawFieldsOf(t) {
		writeFieldDoc(&b, f.doc)
		tsType := typeExpr(f.elemType)
		if f.isPointer && !f.optional {
			tsType += " | null"
		}
		optMark := ""
		if f.optional {
			optMark = "?"
		}
		fmt.Fprintf(&b, "  %s%s: %s;\n", f.json, optMark, tsType)
	}
	b.WriteString("}\n")
	return b.String()
}

// registry accumulates named TS interfaces discovered while walking the
// catalog, keyed by name, so each is emitted exactly once regardless of how
// many methods/notifications/fields reference it.
//
// A TS interface has one bare name, but two Go types in different packages can
// share one. reflect.Type identity is package-qualified (two same-named structs
// in different packages are distinct reflect.Types), so a second claimant of an
// already-registered name is detected here rather than silently dropped: if the
// two render byte-identically the dedup is invisible and safe, but if they
// differ, emitting either would quietly mistype the other, so the generator
// panics. A same-named pair that diverges is exactly the #1016 trap — before
// this, the first claimant won and the second type was never emitted at all.
type registry struct {
	order []string
	types map[string]reflect.Type
	// walked records every reflect.Type whose fields have been visited, so the
	// emission-equal dedup path still surfaces a divergent same-named *nested*
	// type instead of skipping the second claimant's subtree, and so a type
	// reachable through two paths cannot recurse forever.
	walked map[reflect.Type]bool
}

func newRegistry() *registry {
	return &registry{
		types:  map[string]reflect.Type{},
		walked: map[reflect.Type]bool{},
	}
}

// addNamed registers t under name if not already present, then walks its
// fields to discover further nested named types transitively. t is nil for
// a notification payload with no dedicated Go type.
func (r *registry) addNamed(name string, t reflect.Type) {
	if prev, ok := r.types[name]; ok {
		if prev == t {
			return
		}
		// Distinct types claiming one TS name. When both render the same
		// interface the generated file cannot tell them apart, so dropping one
		// is safe; otherwise there is no correct single interface to emit.
		if emitInterface(name, prev) != emitInterface(name, t) {
			panic(fmt.Sprintf(
				"appwirets: type name %q collides between %s and %s; give one a distinct Go type name so the generated TypeScript has a single, correct interface",
				name, typeIdentity(prev), typeIdentity(t)))
		}
		r.walkFields(t)
		return
	}
	r.types[name] = t
	r.order = append(r.order, name)
	r.walkFields(t)
}

// walkFields discovers the named types nested in t's fields, once per
// reflect.Type. A nil t (a notification payload with no dedicated Go type) has
// no fields to walk.
func (r *registry) walkFields(t reflect.Type) {
	if t == nil || r.walked[t] {
		return
	}
	r.walked[t] = true
	for _, f := range rawFieldsOf(t) {
		r.discover(f.elemType)
	}
}

// typeIdentity renders t package-qualified for a collision diagnostic.
func typeIdentity(t reflect.Type) string {
	if t == nil {
		return "<nil>"
	}
	if pkg := t.PkgPath(); pkg != "" {
		return pkg + "." + t.Name()
	}
	return t.String()
}

// discover finds named struct types reachable from t (through slice/map
// elements) and registers each via addNamed. Kinds with no nested named
// type to find (string, number, bool, unknown) are ignored.
func (r *registry) discover(t reflect.Type) {
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	switch t.Kind() {
	case reflect.Slice, reflect.Array:
		r.discover(t.Elem())
	case reflect.Map:
		r.discover(t.Key())
		r.discover(t.Elem())
	case reflect.Struct:
		if isOpaqueStruct(t) {
			return
		}
		if t.Name() == "" {
			panic("appwirets: anonymous struct type has no name to register: " + t.String())
		}
		r.addNamed(t.Name(), t)
	}
}

// deriveName synthesizes a PascalCase TS type name from a wire name (e.g.
// "thread/started") and a suffix (e.g. "Payload"): "ThreadStartedPayload".
// Both "/" and "-" are word boundaries — "thread/reasoning-effort/set"
// segments the same way the catalog's own ThreadReasoningEffortSetParams
// does — since a "-" left in place would produce an invalid TS identifier
// (subtraction is not valid inside `export interface Name {`). Used only
// when a catalog entry has no dedicated Go type to name itself after —
// today that is exactly the notifications with a nil Payload (an inline
// object at the projector; see appwire.Notifications' doc comment).
func deriveName(wireName, suffix string) string {
	var b strings.Builder
	for _, seg := range strings.FieldsFunc(wireName, isNameBoundary) {
		b.WriteString(strings.ToUpper(seg[:1]))
		b.WriteString(seg[1:])
	}
	b.WriteString(suffix)
	return b.String()
}

func isNameBoundary(r rune) bool {
	return r == '/' || r == '-'
}

// registerTopLevel registers a catalog entry's Params/Result/Payload value v
// — nil for a notification with no dedicated Go type — into reg, using v's
// own Go type name when it has one, else the wire-derived fallbackName, and
// returns the name used.
func registerTopLevel(reg *registry, v any, fallbackName string) string {
	t := reflect.TypeOf(v)
	for t != nil && t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	name := fallbackName
	if t != nil && t.Name() != "" {
		name = t.Name()
	}
	reg.addNamed(name, t)
	return name
}

// writeNameCatalog emits a wire-name catalog as a runtime value plus the
// type derived from it:
//
//	export const <constName> = [\n  "a",\n  "b",\n] as const;
//	export type <typeName> = (typeof <constName>)[number];
//
// A type-only union would vanish at runtime, leaving the test doubles in
// protocol/testing/ nothing to validate a scripted name against; deriving
// the type from the value keeps the two from ever disagreeing.
func writeNameCatalog(b *strings.Builder, constName, typeName string, names []string) {
	fmt.Fprintf(b, "export const %s = [\n", constName)
	for _, name := range names {
		fmt.Fprintf(b, "  %q,\n", name)
	}
	b.WriteString("] as const;\n\n")
	fmt.Fprintf(b, "export type %s = (typeof %s)[number];\n\n", typeName, constName)
}

type methodEntry struct {
	name   string
	params string
	result string
}

type notificationEntry struct {
	name    string
	payload string
}

// EmitCatalog renders the full types.gen.ts from the appwire catalog. It
// walks appwire.Methods and appwire.Notifications, collecting every
// reachable named type, emits an interface for each (alphabetical, once
// each), then the MethodName/NotificationName unions and the
// MethodTypes/NotificationTypes/AnyNotification lookup tables (catalog
// order, matching internal/appwiredoc's convention for its own doc tables).
func EmitCatalog() string {
	reg := newRegistry()
	for _, v := range appwire.AllJobActivityTypes {
		registerTopLevel(reg, v, deriveName("evener/jobs/tree", "Payload"))
	}
	for _, v := range navigationRESTRoots {
		registerTopLevel(reg, v, "")
	}

	methods := make([]methodEntry, 0, len(appwire.Methods))
	for _, m := range appwire.Methods {
		methods = append(methods, methodEntry{
			name:   m.Name,
			params: registerTopLevel(reg, m.Params, deriveName(m.Name, "Params")),
			result: registerTopLevel(reg, m.Result, deriveName(m.Name, "Result")),
		})
	}

	notifications := make([]notificationEntry, 0, len(appwire.Notifications))
	for _, n := range appwire.Notifications {
		notifications = append(notifications, notificationEntry{
			name:    n.Name,
			payload: registerTopLevel(reg, n.Payload, deriveName(n.Name, "Payload")),
		})
	}

	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("\n")

	names := append([]string(nil), reg.order...)
	sort.Strings(names)
	for _, name := range names {
		b.WriteString(emitInterface(name, reg.types[name]))
		b.WriteString("\n")
	}

	methodNames := make([]string, len(methods))
	for i, m := range methods {
		methodNames[i] = m.name
	}
	writeNameCatalog(&b, "METHOD_NAMES", "MethodName", methodNames)

	notificationNames := make([]string, len(notifications))
	for i, n := range notifications {
		notificationNames[i] = n.name
	}
	writeNameCatalog(&b, "NOTIFICATION_NAMES", "NotificationName", notificationNames)

	writeNameCatalog(&b, "STEERING_KINDS", "SteeringKind", events.AllSteeringKinds)
	writeNameCatalog(&b, "THREAD_ITEM_EVENT_KINDS", "ThreadItemEventKind", appwire.AllThreadItemEventKinds)

	b.WriteString("export interface MethodTypes {\n")
	for _, m := range methods {
		fmt.Fprintf(&b, "  %q: { params: %s; result: %s };\n", m.name, m.params, m.result)
	}
	b.WriteString("}\n\n")

	b.WriteString("export interface NotificationTypes {\n")
	for _, n := range notifications {
		fmt.Fprintf(&b, "  %q: %s;\n", n.name, n.payload)
	}
	b.WriteString("}\n\n")

	b.WriteString("export type AnyNotification = { [K in NotificationName]: { method: K; params: NotificationTypes[K] } }[NotificationName];\n")

	return b.String()
}

var navigationRESTRoots = []any{
	hubapi.NavigationManifest{},
	hubapi.NavigationSectionResource{},
	hubapi.NavigationPinSectionCatalog{},
	hubapi.NavigationProjectCatalog{},
	hubapi.NavigationProjectResource{},
	hubapi.NavigationProjectPage{},
	hubapi.NavigationSessionLocation{},
	hubapi.NavigationSessionSummary{},
	hubapi.NavigationEntityRecord{},
	hubapi.NavigationContainerOwner{},
	hubapi.NavigationOrderContainer{},
	hubapi.NavigationSnapshot{},
	hubapi.NavigationDelta{},
	appwire.NavigationMutation{},
}
