//go:build serffuzz

package agent

import (
	"context"
	"errors"
	"fmt"
	"io"
	"reflect"
	"regexp"
	"strings"
	"testing"

	"primeradiant.com/serf/agent/execenv"
	"primeradiant.com/serf/agent/internal/agenttest"
	"primeradiant.com/serf/agent/internal/clock"
	"primeradiant.com/serf/agent/internal/jobstore"
	tooldefs "primeradiant.com/serf/agent/internal/tool"
	"primeradiant.com/serf/agent/schema"
	"primeradiant.com/serf/llm"
)

// FuzzJobReadRecoveryGrant drives the two recovery/read-only branches of the
// real job_read_output implementation that an owner-local call does not take:
//
//   - a watch-granted observer reads the parent's retained output through a
//     grantedJobRead snapshot; and
//   - a closed owner's store redirects to its caller's forwarded durable copy.
//
// Both sessions use scripted LLM clients, DenyEnv, FakeClock, and test-owned
// state roots. Shell output comes from jrfgStreamingExecutor, which only writes
// the bounded fuzzer-generated bytes to the real OutputStore and never starts a
// subprocess. The semantic differential oracle is that the direct owner read,
// the granted observer read, and the closed-store fallback all describe the
// same durable job/output window. A grant is snapshot-only, so a positive
// max_wait_ms must be rejected before any wait is attempted.
//
// Registry: native:agent:.:FuzzJobReadRecoveryGrant::session_tools_jobs.go;jobs.go;job_shell.go
func FuzzJobReadRecoveryGrant(f *testing.F) {
	for _, seed := range [][]byte{
		nil,
		{0},
		jrfgSeed(0, false, false), // default digest
		jrfgSeed(1, true, false),  // head lines
		jrfgSeed(2, false, false), // tail lines
		jrfgSeed(3, true, false),  // head + tail digest
		jrfgSeed(4, false, false), // from_line window
		jrfgSeed(5, true, true),   // grep plus fallback grep snapshot
		[]byte("granted read fallback replay"),
	} {
		f.Add(seed)
	}

	f.Fuzz(func(t *testing.T, data []byte) {
		program := jrfgDecode(data)
		first := jrfgRun(t, program)
		if replay := jrfgRun(t, program); !reflect.DeepEqual(first, replay) {
			t.Fatalf("job-read recovery replay changed:\nfirst:  %#v\nreplay: %#v", first, replay)
		}
	})
}

type jrfgReader struct {
	data []byte
	pos  int
}

func (r *jrfgReader) next() byte {
	if r.pos >= len(r.data) {
		return 0
	}
	v := r.data[r.pos]
	r.pos++
	return v
}

func (r *jrfgReader) intn(n int) int {
	if n <= 0 {
		return 0
	}
	return int(r.next()) % n
}

type jrfgProgram struct {
	seed      uint64
	mode      int
	fromLine  int
	lineCount int
	readBytes int
	fromHead  bool
	grep      bool
	output    string
}

// jrfgSeed keeps all selector bytes before the variable-length payload draws.
// This makes the committed corpus cover each job_read_output mode rather than
// relying on coverage-guided search to extend a short input past line content.
func jrfgSeed(mode byte, fromHead, grep bool) []byte {
	seed := make([]byte, 16)
	seed[8] = mode
	seed[9] = 200 // 203 lines: enough to make the default digest elide a middle
	seed[10] = 23
	seed[11] = 7
	seed[12] = 3
	seed[13] = 3
	if fromHead {
		seed[14] = 1
	}
	if grep {
		seed[15] = 1
	}
	return seed
}

func jrfgDecode(data []byte) jrfgProgram {
	r := &jrfgReader{data: data}
	var seed uint64
	for i := 0; i < 8; i++ {
		seed |= uint64(r.next()) << (8 * i)
	}
	mode := r.intn(6)
	lineTotal := 3 + r.intn(220)
	lineWidth := r.intn(28)
	fromLine := 1 + r.intn(lineTotal)
	lineCount := 1 + r.intn(12)
	readBytes := []int{1, 17, 256, 1024, 8192}[r.intn(5)]
	fromHead := r.next()&1 != 0
	grep := r.next()&1 != 0
	parts := []string{"x", "e", "é", "世界"}
	var out strings.Builder
	for i := 0; i < lineTotal; i++ {
		fmt.Fprintf(&out, "line-%03d needle %s\n", i, strings.Repeat(parts[r.intn(len(parts))], lineWidth))
	}
	return jrfgProgram{
		seed:      seed,
		mode:      mode,
		fromLine:  fromLine,
		lineCount: lineCount,
		readBytes: readBytes,
		fromHead:  fromHead,
		grep:      grep,
		output:    out.String(),
	}
}

// jrfgStreamingExecutor is deliberately a bounded in-process streaming boundary:
// it writes the decoded bytes then returns a completed handle. It never invokes
// a shell or observes host process state.
type jrfgStreamingExecutor struct{ output []byte }

func (e jrfgStreamingExecutor) StreamCommand(_ context.Context, _ string, _ string, _ map[string]string, out io.Writer) (*execenv.StreamHandle, error) {
	if _, err := out.Write(e.output); err != nil {
		return nil, err
	}
	return &execenv.StreamHandle{
		Wait:   func() (int, error) { return 0, nil },
		Signal: func() {},
	}, nil
}

// jrfgTrace intentionally excludes generated job/session ids. It is the
// externally meaningful result projection used for the fresh-fixture replay
// oracle above.
type jrfgTrace struct {
	Type         string
	Status       string
	Reason       string
	Content      string
	TotalBytes   int64
	DroppedBytes int64
	OutputStatus string
	Truncated    bool
	MatchOffsets []int64
	MatchLines   []string
	LastActivity string
	HasExitCode  bool
	ExitCode     int
}

func jrfgRun(t *testing.T, p jrfgProgram) jrfgTrace {
	t.Helper()
	owner := jrfgNewSession(t, p.seed)
	defer owner.Close()
	observer := jrfgNewSession(t, p.seed+1)
	defer observer.Close()

	res := runShell(context.Background(), owner.jobManager, jrfgStreamingExecutor{output: []byte(p.output)}, shellArgs{
		Command:        "jrfg",
		BlockTimeoutMS: minShellBlockTimeoutMS,
	})
	if res.Status != string(jobstore.StatusCompleted) || res.settle == nil {
		t.Fatalf("scripted shell = %+v, want completed result with settle", res)
	}
	jobID := res.settle(true)
	if jobID == "" {
		t.Fatal("settle(keep) returned an empty durable job id")
	}

	ownerRec, err := findJobRecord(owner.jobManager, jobID)
	if err != nil {
		t.Fatalf("load durable shell %q: %v", jobID, err)
	}
	grant := &grantedJobRead{
		record: cloneJobRecord(ownerRec),
		readWindow: func(bytes int, fromHead bool) (string, int64, int64, bool, error) {
			return owner.jobManager.readJobWindow(jobID, bytes, fromHead)
		},
		grepOutput: func(re *regexp.Regexp) ([]jobstore.Match, error) {
			return owner.jobManager.grepOutput(jobID, re)
		},
	}
	observer.cfg.spawn.parentGrantedJobRead = func(observerID, requestedID string) (*grantedJobRead, bool) {
		if observerID != observer.ID() || requestedID != jobID {
			return nil, false
		}
		return grant, true
	}

	args := jrfgReadArgs(p, jobID)
	ownerResult := jrfgReadToolResult(t, owner, args)
	grantedResult := jrfgReadToolResult(t, observer, args)
	if !reflect.DeepEqual(ownerResult, grantedResult) {
		t.Fatalf("grant projection diverged from direct owner read:\nowner:  %#v\ngrant:  %#v\nargs: %#v", ownerResult, grantedResult, args)
	}

	// A granted read is a point-in-time parent-store snapshot. It must reject an
	// inline wait rather than silently pretending it observed future output.
	waitArgs := jrfgCloneArgs(args)
	waitArgs["max_wait_ms"] = float64(1)
	value, waitErr := jobReadOutputTool(context.Background(), observer, waitArgs, jobToolResultDefaultMaxChar)
	if waitErr == nil || value != "" || !strings.Contains(waitErr.Error(), grantedReadBlockUnsupportedErr) {
		t.Fatalf("granted max_wait = (%#v, %v), want empty result plus %q", value, waitErr, grantedReadBlockUnsupportedErr)
	}

	var grepRE *regexp.Regexp
	if p.grep {
		grepRE = regexp.MustCompile("needle")
	}
	direct, err := owner.readJobOutputSnapshot(owner.jobManager, owner, jobID, p.readBytes, p.fromHead, grepRE)
	if err != nil {
		t.Fatalf("direct snapshot: %v", err)
	}
	closed, err := newJobManagerNoSync(t.TempDir(), "jrfg-closed-source", nil)
	if err != nil {
		t.Fatalf("new closed source manager: %v", err)
	}
	if err := closed.closeStoreOnly(); err != nil {
		t.Fatalf("close source store: %v", err)
	}
	recovered, err := owner.readJobOutputSnapshot(closed, owner, jobID, p.readBytes, p.fromHead, grepRE)
	if err != nil {
		t.Fatalf("closed-store fallback snapshot: %v", err)
	}
	if !reflect.DeepEqual(direct, recovered) {
		t.Fatalf("closed-store fallback diverged from direct snapshot:\ndirect:    %#v\nrecovered: %#v", direct, recovered)
	}
	if recovered.Manager != owner.jobManager {
		t.Fatalf("closed-store fallback manager = %p, want owner manager %p", recovered.Manager, owner.jobManager)
	}

	// The fallback is intentionally a one-hop repair only for a closed foreign
	// manager. A local closed-store error and any non-store error pass through.
	if next, ok, fallbackErr := owner.jobReadClosedStoreFallback(owner.jobManager, jobstore.ErrStoreClosed); next != nil || ok || !errors.Is(fallbackErr, jobstore.ErrStoreClosed) {
		t.Fatalf("local closed fallback = (%p,%v,%v), want no redirect", next, ok, fallbackErr)
	}
	plainErr := errors.New("jrfg ordinary read failure")
	if next, ok, fallbackErr := owner.jobReadClosedStoreFallback(closed, plainErr); next != nil || ok || !errors.Is(fallbackErr, plainErr) {
		t.Fatalf("non-store fallback = (%p,%v,%v), want original error", next, ok, fallbackErr)
	}

	return jrfgTraceFrom(grantedResult)
}

func jrfgReadArgs(p jrfgProgram, jobID string) map[string]any {
	args := map[string]any{"job_id": jobID}
	switch p.mode {
	case 1:
		args["head_lines"] = float64(p.lineCount)
	case 2:
		args["tail_lines"] = float64(p.lineCount)
	case 3:
		args["head_lines"] = float64(p.lineCount)
		args["tail_lines"] = float64(p.lineCount)
	case 4:
		args["from_line"] = float64(p.fromLine)
		args["line_count"] = float64(p.lineCount)
	case 5:
		args["grep"] = "needle"
	}
	return args
}

func jrfgCloneArgs(in map[string]any) map[string]any {
	out := make(map[string]any, len(in)+1)
	for key, value := range in {
		out[key] = value
	}
	return out
}

func jrfgReadToolResult(t *testing.T, s *Session, args map[string]any) jobReadOutputResult {
	t.Helper()
	value, err := jobReadOutputTool(context.Background(), s, jrfgCloneArgs(args), jobToolResultDefaultMaxChar)
	if err != nil {
		t.Fatalf("job_read_output(%#v): %v", args, err)
	}
	state, ok := value.(tooldefs.StateResult)
	if !ok {
		t.Fatalf("job_read_output type = %T, want StateResult", value)
	}
	result, ok := state.State.(jobReadOutputResult)
	if !ok {
		t.Fatalf("job_read_output state type = %T, want jobReadOutputResult", state.State)
	}
	return result
}

func jrfgTraceFrom(result jobReadOutputResult) jrfgTrace {
	trace := jrfgTrace{
		Type:         result.Type,
		Status:       result.Status,
		Reason:       derefString(result.Reason),
		Content:      result.Content,
		TotalBytes:   result.TotalBytes,
		DroppedBytes: result.DroppedBytes,
		OutputStatus: result.OutputStatus,
		Truncated:    result.Truncated,
		LastActivity: derefString(result.LastActivity),
	}
	if result.ExitCode != nil {
		trace.HasExitCode = true
		trace.ExitCode = *result.ExitCode
	}
	if result.Matches != nil {
		for _, match := range *result.Matches {
			trace.MatchOffsets = append(trace.MatchOffsets, match.ByteOffset)
			trace.MatchLines = append(trace.MatchLines, match.Line)
		}
	}
	return trace
}

func jrfgNewSession(t *testing.T, seed uint64) *Session {
	t.Helper()
	client := llm.NewClient()
	client.Register(&agenttest.ScriptedAdapter{
		Provider: "openai",
		Responder: func(llm.Request) llm.Response {
			return agenttest.FinalResponse("jrfg scripted boundary")
		},
	})
	cfg := SessionConfig{
		StateDir:         t.TempDir(),
		MaxSubagentDepth: 1,
		NoProjectPrompts: true,
		clock:            agenttest.NewFakeClock(),
	}
	cfg.testOnly = testConfig{
		skipGitSnapshot:     true,
		environmentInfo:     jrfgEnvironmentInfo,
		minimalSystemPrompt: true,
		noSyncJobStore:      true,
	}
	s, err := NewSession(client, NewOpenAIProfile("gpt-5.2"), &agenttest.DenyEnv{WorkDir: t.TempDir(), Seed: seed}, cfg)
	if err != nil {
		t.Fatalf("NewSession: %v", err)
	}
	return s
}

func jrfgEnvironmentInfo(env execenv.ExecutionEnvironment, clk clock.Clock) schema.EnvironmentInfo {
	return schema.EnvironmentInfo{
		WorkingDir: env.WorkingDirectory(),
		Platform:   "jrfg",
		OSVersion:  "jrfg",
		Today:      clk.Now().UTC().Format("2006-01-02"),
	}
}
