package agent

import (
	"context"
	"errors"
	"fmt"
	"path/filepath"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"

	"primeradiant.com/serf/agent/events"
	"primeradiant.com/serf/agent/internal/sessionlog"
	"primeradiant.com/serf/agent/provider"
	"primeradiant.com/serf/agent/schema"
	"primeradiant.com/serf/llm"
)

const (
	sessionNameSourcePrompt     = "prompt"
	sessionNameSourceCompaction = "compaction"
	sessionNameMaxRunes         = 60
	sessionNameTimeout          = 15 * time.Second
)

// sessionNameResult is the advisory output of the cheap-model session namer.
type sessionNameResult struct {
	// Name is the sanitized session title generated by the model.
	Name string
	// Source is the normalized origin of the name ("prompt" or "compaction").
	Source string
	// Usage is the token usage reported for the naming LLM call.
	Usage llm.Usage
}

// nameSession derives a short human-readable session title using a single cheap-model LLM call.
func nameSession(ctx context.Context, client *llm.Client, profile *provider.Profile, source, text string) (sessionNameResult, error) {
	if client == nil {
		return sessionNameResult{}, errors.New("session namer: llm client is nil")
	}
	if profile == nil {
		return sessionNameResult{}, errors.New("session namer: profile is nil")
	}
	source = normalizeSessionNameSource(source)
	text = strings.TrimSpace(text)
	if text == "" {
		return sessionNameResult{}, errors.New("session namer: source text is empty")
	}
	if ctx == nil {
		ctx = context.Background()
	}
	callCtx, cancel := context.WithTimeout(ctx, sessionNameTimeout)
	defer cancel()

	model := sessionNamerModel(profile)
	if model == "" {
		return sessionNameResult{}, errors.New("session namer: model is empty")
	}
	maxTokens := 80
	temp := 0.0
	res, err := llm.GenerateObject(callCtx, llm.GenerateObjectOptions{
		GenerateOptions: llm.GenerateOptions{
			Client:      client,
			Provider:    profile.ID(),
			Model:       model,
			System:      ptrString(sessionNamerSystemPrompt),
			Prompt:      ptrString(sessionNamerUserPrompt(source, text)),
			Temperature: &temp,
			MaxTokens:   &maxTokens,
		},
		Schema: sessionNameSchema(),
	})
	if err != nil {
		return sessionNameResult{}, fmt.Errorf("session namer: %w", err)
	}

	obj, _ := res.Output.(map[string]any)
	name, _ := obj["name"].(string)
	name = sanitizeSessionName(name)
	if name == "" {
		return sessionNameResult{}, errors.New("session namer: generated name is empty")
	}
	return sessionNameResult{Name: name, Source: source, Usage: res.TotalUsage}, nil
}

func sessionNamerEnabled(profile *provider.Profile) bool {
	if profile == nil {
		return false
	}
	return configuredSessionNamerModel(profile) != ""
}

func sessionNamerModel(profile *provider.Profile) string {
	if profile == nil {
		return ""
	}
	if model := configuredSessionNamerModel(profile); model != "" {
		return model
	}
	return strings.TrimSpace(profile.Model())
}

func configuredSessionNamerModel(profile *provider.Profile) string {
	if profile == nil {
		return ""
	}
	return profile.ConfiguredCheapModel()
}

const sessionNamerSystemPrompt = `You generate concise session titles for a developer assistant.
Return only JSON matching the requested schema.
Rules:
- 2 to 6 words.
- Maximum 60 characters.
- Use Title Case.
- No ending punctuation.
- No quotes or markdown.
- Prefer the concrete task or outcome over generic wording.`

func sessionNamerUserPrompt(source, text string) string {
	var label string
	switch normalizeSessionNameSource(source) {
	case sessionNameSourceCompaction:
		label = "Use this compaction summary/checkpoint to refresh the session title"
	default:
		label = "Use this initial user prompt to name the session"
	}
	return label + ":\n\n" + trimForSessionNamer(text)
}

func sessionNameSchema() map[string]any {
	return map[string]any{
		"type":                 "object",
		"additionalProperties": false,
		"properties": map[string]any{
			"name": map[string]any{
				"type":        "string",
				"description": "A short human-readable session title.",
				"minLength":   1,
				"maxLength":   sessionNameMaxRunes,
			},
		},
		"required": []string{"name"},
	}
}

func normalizeSessionNameSource(source string) string {
	switch strings.TrimSpace(source) {
	case sessionNameSourceCompaction:
		return sessionNameSourceCompaction
	default:
		return sessionNameSourcePrompt
	}
}

func trimForSessionNamer(text string) string {
	text = strings.TrimSpace(text)
	const maxRunes = 4000
	if utf8.RuneCountInString(text) <= maxRunes {
		return text
	}
	runes := []rune(text)
	return string(runes[:maxRunes]) + "\n...[truncated]"
}

func sanitizeSessionName(name string) string {
	name = strings.TrimSpace(name)
	name = strings.Trim(name, "\"'`“”‘’")
	name = strings.Join(strings.Fields(name), " ")
	name = strings.TrimRightFunc(name, func(r rune) bool {
		return unicode.IsPunct(r) || unicode.IsSpace(r)
	})
	if utf8.RuneCountInString(name) > sessionNameMaxRunes {
		runes := []rune(name)
		name = strings.TrimSpace(string(runes[:sessionNameMaxRunes]))
		name = strings.TrimRightFunc(name, func(r rune) bool {
			return unicode.IsPunct(r) || unicode.IsSpace(r)
		})
	}
	return name
}

func ptrString(s string) *string { return &s }

func (s *Session) launchInitialPromptNamer(ctx context.Context, input string) {
	if s.stateDir == "" {
		return
	}
	if !sessionNamerEnabled(s.currentProfile()) {
		return
	}
	if strings.TrimSpace(input) == "" {
		return
	}
	s.mu.Lock()
	if s.naming.set || s.naming.promptPending || strings.TrimSpace(s.naming.value) != "" || s.closingOrClosedLocked() {
		s.mu.Unlock()
		return
	}
	s.naming.promptPending = true
	s.sendersWG.Add(1)
	s.mu.Unlock()
	go func() {
		defer s.sendersWG.Done()
		nameCtx := ctx
		if nameCtx == nil {
			nameCtx = context.Background()
		}
		err := s.nameSessionFromText(nameCtx, sessionNameSourcePrompt, input)
		s.clearPromptNamePendingAfterAttempt(err)
	}()
}

func (s *Session) clearPromptNamePendingAfterAttempt(err error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if err != nil || strings.TrimSpace(s.naming.value) == "" {
		s.naming.promptPending = false
	}
}

func (s *Session) launchCompactionNamer(ctx context.Context, turn schema.Turn) {
	if s.stateDir == "" {
		return
	}
	if !sessionNamerEnabled(s.currentProfile()) {
		return
	}
	if !isSessionNameCompactionTurn(turn) || strings.TrimSpace(turn.Message.Text()) == "" {
		return
	}
	if !s.shouldNameFromCompaction() {
		return
	}
	s.mu.Lock()
	if s.closingOrClosedLocked() {
		s.mu.Unlock()
		return
	}
	s.sendersWG.Add(1)
	s.mu.Unlock()
	go func() {
		defer s.sendersWG.Done()
		nameCtx := ctx
		if nameCtx == nil {
			nameCtx = context.Background()
		}
		_ = s.nameSessionFromCompactionTurn(nameCtx, turn)
	}()
}

func (s *Session) nameSessionFromCompactionTurn(ctx context.Context, turn schema.Turn) error {
	if !isSessionNameCompactionTurn(turn) {
		return nil
	}
	text := strings.TrimSpace(turn.Message.Text())
	if text == "" {
		return nil
	}
	if !s.shouldNameFromCompaction() {
		return nil
	}
	return s.nameSessionFromText(ctx, sessionNameSourceCompaction, text)
}

func isSessionNameCompactionTurn(turn schema.Turn) bool {
	return turn.Kind == schema.TurnSummary || turn.Kind == schema.TurnCheckpoint
}

func (s *Session) handleCompactionTurn(t schema.Turn) {
	if s.transcript != nil {
		if err := s.transcript.Append(t); err != nil {
			s.emit(events.EventWarning, events.WarningData{Message: fmt.Sprintf("transcript compaction write: %v", err)})
		}
	}
	if isSessionNameCompactionTurn(t) {
		s.emit(events.EventCompactionTurn, events.CompactionTurnData{Kind: string(t.Kind), Text: t.Message.Text()})
	}
	s.launchCompactionNamer(s.sessionCtx, t)
	// After compaction, inject full task list if tasks exist.
	if s.taskStore != nil {
		if reminder := taskReminderFull(s.taskStore); reminder != "" {
			s.Steer(reminder)
		}
	}
	// Tell the agent how to inspect the full pre-compaction transcript.
	if s.stateDir != "" && s.id != "" {
		ref := encodeRef("", s.id)
		s.Steer("<SYSTEM-REMINDER>If you need the exact transcript of this session before compaction, use the transcript tool instead of reading raw transcript files directly. Default read: read_session_transcript({\"transcript_ref\": \"" + ref + "\", \"format\": \"markdown\"}). For long sessions, first get a turn map with read_session_transcript({\"transcript_ref\": \"" + ref + "\", \"format\": \"outline\"}), then read a focused range with read_session_transcript({\"transcript_ref\": \"" + ref + "\", \"range\": \"A-B\"}).</SYSTEM-REMINDER>")
	}
}

func (s *Session) shouldNameFromCompaction() bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	if strings.TrimSpace(s.naming.value) == "" {
		return true
	}
	source := strings.TrimSpace(s.naming.source)
	return source == sessionNameSourcePrompt || source == sessionNameSourceCompaction
}

func (s *Session) nameSessionFromText(ctx context.Context, source, text string) error {
	source = normalizeSessionNameSource(source)
	if !s.shouldApplySessionName(source) {
		return nil
	}
	if s.nameSessionFromTextFunc != nil {
		return s.nameSessionFromTextFunc(ctx, source, text)
	}

	result, err := nameSession(ctx, s.client, s.currentProfile(), source, text)
	if err != nil {
		s.appendSessionNamerLog(sessionlog.SessionLogEntry{
			Kind:     "advisory",
			Action:   "session_namer",
			Summary:  fmt.Sprintf("Failed to generate %s-derived session name", sessionNameSourceLabel(source)),
			Outcome:  "failure",
			Failures: []string{err.Error()},
		})
		return err
	}

	s.mu.Lock()
	if s.closingOrClosedLocked() {
		s.mu.Unlock()
		return context.Canceled
	}
	if !s.shouldApplySessionNameLocked(result.Source) {
		s.mu.Unlock()
		return nil
	}
	s.naming.value = result.Name
	s.naming.source = result.Source
	s.naming.updated = time.Now().UTC()
	s.naming.set = true
	s.mu.Unlock()

	s.appendSessionNamerLog(sessionlog.SessionLogEntry{
		Kind:    "advisory",
		Action:  "session_namer",
		Summary: fmt.Sprintf("Suggested %s-derived session name: %s", sessionNameSourceLabel(result.Source), result.Name),
		Outcome: "success",
	})
	s.maybeAutoSave()
	return nil
}

func (s *Session) shouldApplySessionName(source string) bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.shouldApplySessionNameLocked(source)
}

func (s *Session) shouldApplySessionNameLocked(source string) bool {
	source = normalizeSessionNameSource(source)
	if strings.TrimSpace(s.naming.value) == "" {
		return true
	}
	currentSource := strings.TrimSpace(s.naming.source)
	switch source {
	case sessionNameSourceCompaction:
		return currentSource == sessionNameSourcePrompt || currentSource == sessionNameSourceCompaction
	case sessionNameSourcePrompt:
		return false
	default:
		return false
	}
}

func (s *Session) appendSessionNamerLog(entry sessionlog.SessionLogEntry) {
	if s.stateDir == "" {
		return
	}
	entry.Kind = "advisory"
	entry.Action = "session_namer"
	logPath := filepath.Join(s.stateDir, sessionsSubdir, s.id+".log.jsonl")
	log, err := sessionlog.NewSessionLog(logPath)
	if err != nil {
		s.emit(events.EventWarning, events.WarningData{Message: fmt.Sprintf("session namer log open failed: %v", err)})
		return
	}
	if err := log.Append(entry); err != nil {
		s.emit(events.EventWarning, events.WarningData{Message: fmt.Sprintf("session namer log append failed: %v", err)})
	}
}

func sessionNameSourceLabel(source string) string {
	switch normalizeSessionNameSource(source) {
	case sessionNameSourceCompaction:
		return "compaction"
	default:
		return "prompt"
	}
}
