package agent

import "primeradiant.com/serf/llm"

type SessionConfig struct {
	MaxToolRoundsPerInput   int `json:"max_tool_rounds_per_input,omitempty"`
	MaxTurns                int `json:"max_turns,omitempty"`
	DefaultCommandTimeoutMS int `json:"default_command_timeout_ms,omitempty"`
	MaxCommandTimeoutMS     int `json:"max_command_timeout_ms,omitempty"`
	MaxSubagentDepth        int `json:"max_subagent_depth,omitempty"`

	// ToolOutputLimits overrides default per-tool truncation behavior.
	ToolOutputLimits map[string]ToolOutputLimit `json:"tool_output_limits,omitempty"`

	// UserInstructionOverride is appended to the end of the system prompt (highest priority).
	UserInstructionOverride string `json:"user_instruction_override,omitempty"`

	// AgentName selects a persona for prompt composition. When set, the persona's
	// role prompt is used instead of the default agent profile. Looked up from
	// built-in agents, then plugin agents.
	AgentName string `json:"agent_name,omitempty"`

	// ReasoningEffort is passed through to the Unified LLM request when non-empty.
	// Valid values are provider-dependent but typically include: low|medium|high.
	ReasoningEffort string `json:"reasoning_effort,omitempty"`

	// SkillsDirs are extra directories to scan for skills (each is treated
	// as a directory whose subdirectories contain SKILL.md files).
	SkillsDirs []string `json:"skills_dirs,omitempty"`

	// MCPConfigFiles are paths to .mcp.json files (--mcp-config flag).
	MCPConfigFiles []string `json:"mcp_config_files,omitempty"`

	// MCPInline are inline MCP server specs (--mcp flag, format: name:command args...).
	MCPInline []string `json:"mcp_inline,omitempty"`

	// PluginDirs are directories to scan for plugins (each contains a plugin.yaml manifest).
	PluginDirs []string `json:"plugin_dirs,omitempty"`

	// SessionStartKind controls the matcher target for plugin SessionStart hooks.
	// Empty means startup for new sessions. Restore paths force resume.
	SessionStartKind SessionStartKind `json:"-"`

	// SystemPromptFile replaces the built-in base instruction prelude for the
	// top-level session only, while keeping the dynamic sections (tools,
	// environment, role, project docs, etc.) generated by the template system.
	SystemPromptFile string `json:"system_prompt_file,omitempty"`

	// SystemPromptAppend are file paths whose contents are appended to the system prompt.
	// Always applied, even when SystemPromptFile is set (CLI --system-prompt-append flag).
	SystemPromptAppend []string `json:"system_prompt_append,omitempty"`

	// NoProjectPrompts suppresses loading .serf/prompts/ from the project directory.
	// Useful for A/B testing to match Docker container behavior (no project prompts).
	NoProjectPrompts bool `json:"no_project_prompts,omitempty"`

	// NonInteractive indicates no human is available for questions or confirmation.
	// The task prompt is the complete specification; the agent must make all decisions
	// autonomously. Appends guidance to the system prompt adapting skill behavior.
	NonInteractive bool `json:"non_interactive,omitempty"`

	// ContextStrategy selects the context management strategy: compact|recall|session-log|ooda.
	ContextStrategy string `json:"context_strategy,omitempty"`

	// ShareTasksWithChildren, when true, passes the parent's task store to
	// child sessions spawned via spawn_agent. Both parent and children see
	// the same task list, enabling cross-session task coordination.
	ShareTasksWithChildren bool `json:"share_tasks_with_children,omitempty"`

	// ResultToolName overrides the name of the result tool.
	// When set, all internal references use this name instead of "communicate".
	// Used for A/B testing tool names. Empty means "communicate".
	ResultToolName string `json:"result_tool_name,omitempty"`

	EnableLoopDetection *bool `json:"enable_loop_detection,omitempty"`
	LoopDetectionWindow int   `json:"loop_detection_window,omitempty"`

	// LLMRetryPolicy controls retries for retryable Unified LLM errors (429, 5xx, etc).
	// Nil means use llm.DefaultRetryPolicy().
	LLMRetryPolicy *llm.RetryPolicy `json:"-"`
	LLMSleep       llm.SleepFunc    `json:"-"`

	// ModelFallbacks is a literal-order chain of "provider/model" identifiers
	// to try when the primary model returns a Permanent-class provider error
	// (403/404/422/etc — see llm.Classify). Empty means no fallback. Kata cxw8.
	ModelFallbacks []string `json:"model_fallbacks,omitempty"`

	// ContextStrategyOverride, when non-nil, is used instead of creating
	// a strategy from the ContextStrategy string. For testing.
	ContextStrategyOverride ContextStrategy `json:"-"`

	// CompactionThresholdScale multiplies all compaction thresholds by this
	// factor. 1.0 = defaults, 0.1 = trigger at 10% of normal pressure.
	// Used for evaluation testing. 0 means use defaults.
	CompactionThresholdScale float64 `json:"compaction_threshold_scale,omitempty"`

	// ParentSessionID links sub-agent sessions to their parent (set by spawnAgent).
	ParentSessionID string `json:"-"`

	// ParentToolCallID is the tool call ID that spawned this sub-agent session.
	ParentToolCallID string `json:"-"`

	// SubagentTask is the task description passed to spawn_agent.
	SubagentTask string `json:"-"`

	// Depth is the sub-agent nesting depth (0 for root sessions).
	Depth int `json:"-"`

	// StateDir, when non-empty, enables incremental session persistence.
	// Snapshots are written to <StateDir>/sessions/ and tasks to <StateDir>/tasks/.
	StateDir string `json:"-"`

	// ExportATIFPath, when non-empty, causes Session.Close to export an ATIF v1.6
	// trajectory JSON file to this path. Only root sessions (Depth==0) export.
	ExportATIFPath string `json:"-"`

	// SystemPromptAsUser, when true, combines the system prompt into the first
	// user message instead of sending it as a separate system/developer message.
	// Workaround for models (e.g. GPT-5.4) that ignore the instructions
	// parameter when given specific task delegations in user messages.
	SystemPromptAsUser bool `json:"system_prompt_as_user,omitempty"`

	// SharedTaskStore, when non-nil, is used instead of creating a per-session
	// task store. Set by spawnAgent when ShareTasksWithChildren is true.
	SharedTaskStore *TaskStore `json:"-"`

	// ResolveProfile, when non-nil, maps a "provider/model" ref to the
	// corresponding ProviderProfile. Injected by cmd/serf so that
	// Session.SetModel can perform cross-provider switches without
	// importing the provider constructors directly (which would create a
	// cycle). When nil the session falls back to profile.WithModel which
	// only handles same-provider (or strip/keep) refs.
	ResolveProfile func(ref string) (ProviderProfile, error) `json:"-"`

	// Internal prompt/session shaping for restricted subagents and reviewer runs.
	RolePromptOverride   string   `json:"-"`
	ActivatedSkillBodies []string `json:"-"`
	AllowedToolNames     []string `json:"-"`
	DeniedToolNames      []string `json:"-"`
}

func (c *SessionConfig) applyDefaults() {
	if c.MaxToolRoundsPerInput == 0 {
		c.MaxToolRoundsPerInput = 200
	}
	if c.DefaultCommandTimeoutMS <= 0 {
		c.DefaultCommandTimeoutMS = 10_000
	}
	if c.MaxCommandTimeoutMS <= 0 {
		c.MaxCommandTimeoutMS = 600_000
	}
	if c.MaxSubagentDepth <= 0 {
		c.MaxSubagentDepth = 1
	}
	if c.EnableLoopDetection == nil {
		v := true
		c.EnableLoopDetection = &v
	}
	if c.LoopDetectionWindow <= 0 {
		c.LoopDetectionWindow = 10
	}
}
