package agent

import (
	"primeradiant.com/serf/agent/internal/contextmgr"
	"primeradiant.com/serf/agent/internal/jobstore"
	"primeradiant.com/serf/agent/plugin"
	"primeradiant.com/serf/agent/provider"
	"primeradiant.com/serf/agent/schema"
	"primeradiant.com/serf/agent/task"
	"primeradiant.com/serf/llm"
)

// SessionConfig holds the configuration options for an agent session,
// covering tool-round and turn limits, command timeouts, prompt composition,
// context-management strategy, sub-agent behavior, LLM retry and fallback
// settings, and session persistence. Zero-valued fields are filled in by
// applyDefaults where defaults apply.
type SessionConfig struct {
	// MaxToolRoundsPerInput caps how many tool-call rounds a single
	// ProcessInput may run before the turn stops with a TURN_LIMIT event.
	// Zero defaults to 200.
	MaxToolRoundsPerInput int `json:"max_tool_rounds_per_input,omitempty"`

	// MaxTurns caps the number of user inputs the session will accept over its
	// lifetime; the (N+1)th input stops with a TURN_LIMIT event. Zero means
	// unlimited.
	MaxTurns int `json:"max_turns,omitempty"`

	// DefaultCommandTimeoutMS is the timeout applied to a shell/exec tool call
	// when the model does not request one. Zero defaults to 10000 (10s).
	DefaultCommandTimeoutMS int `json:"default_command_timeout_ms,omitempty"`

	// MaxCommandTimeoutMS is the ceiling on any per-command timeout the model
	// may request. Zero defaults to 600000 (10m).
	MaxCommandTimeoutMS int `json:"max_command_timeout_ms,omitempty"`

	// MaxSubagentDepth limits how deeply sub-agents may spawn further
	// sub-agents (root session is depth 0). Zero defaults to 1.
	MaxSubagentDepth int `json:"max_subagent_depth,omitempty"`

	// ToolOutputLimits overrides default per-tool truncation behavior.
	ToolOutputLimits map[string]schema.ToolOutputLimit `json:"tool_output_limits,omitempty"`

	// UserInstructionOverride is appended to the end of the system prompt (highest priority).
	UserInstructionOverride string `json:"user_instruction_override,omitempty"`

	// AgentName selects a persona for prompt composition. When set, the persona's
	// role prompt is used instead of the default agent profile. Looked up from
	// built-in agents, then plugin agents.
	AgentName string `json:"agent_name,omitempty"`

	// ReasoningEffort is passed through to the Unified LLM request when non-empty.
	// Valid values are provider-dependent but typically include: low|medium|high.
	ReasoningEffort string `json:"reasoning_effort,omitempty"`

	// SkillsDirs are extra directories to scan for skills (each is treated
	// as a directory whose subdirectories contain SKILL.md files).
	SkillsDirs []string `json:"skills_dirs,omitempty"`

	// MCPConfigFiles are paths to .mcp.json files (--mcp-config flag).
	MCPConfigFiles []string `json:"mcp_config_files,omitempty"`

	// MCPInline are inline MCP server specs (--mcp flag, format: name:command args...).
	MCPInline []string `json:"mcp_inline,omitempty"`

	// PluginDirs are directories to scan for plugins (each contains a plugin.yaml manifest).
	PluginDirs []string `json:"plugin_dirs,omitempty"`

	// SessionStartKind controls the matcher target for plugin SessionStart hooks.
	// Empty means startup for new sessions. Restore paths force resume.
	SessionStartKind plugin.SessionStartKind `json:"-"`

	// SystemPromptFile replaces the built-in base instruction prelude for the
	// top-level session only, while keeping the dynamic sections (tools,
	// environment, role, project docs, etc.) generated by the template system.
	SystemPromptFile string `json:"system_prompt_file,omitempty"`

	// SystemPromptAppend are file paths whose contents are appended to the system prompt.
	// Always applied, even when SystemPromptFile is set (CLI --system-prompt-append flag).
	SystemPromptAppend []string `json:"system_prompt_append,omitempty"`

	// NoProjectPrompts suppresses loading .serf/prompts/ from the project directory.
	// Useful for A/B testing to match Docker container behavior (no project prompts).
	NoProjectPrompts bool `json:"no_project_prompts,omitempty"`

	// NonInteractive indicates no human is available for questions or confirmation.
	// The task prompt is the complete specification; the agent must make all decisions
	// autonomously. Appends guidance to the system prompt adapting skill behavior.
	NonInteractive bool `json:"non_interactive,omitempty"`

	// ContextStrategy selects the context management strategy: compact|session-log|ooda.
	// The value "recall" is accepted as a compatibility alias for compact.
	ContextStrategy string `json:"context_strategy,omitempty"`

	// ShareTasksWithChildren, when true, passes the parent's task store to
	// child sessions created for delegate jobs. Both parent and children see
	// the same task list, enabling cross-session task coordination.
	ShareTasksWithChildren bool `json:"share_tasks_with_children,omitempty"`

	// ResultToolName overrides the name of the result tool.
	// When set, all internal references use this name instead of "communicate".
	// Used for A/B testing tool names. Empty means "communicate".
	ResultToolName string `json:"result_tool_name,omitempty"`

	// EnableLoopDetection toggles repeated-tool-call loop detection, which
	// nudges the model with an escalating warning when it repeats the same tool
	// signatures. A nil pointer defaults to enabled; set to a pointer to false
	// to disable.
	EnableLoopDetection *bool `json:"enable_loop_detection,omitempty"`

	// LoopDetectionWindow is the number of recent tool-call signatures examined
	// for a repeating pattern. Zero defaults to 10.
	LoopDetectionWindow int `json:"loop_detection_window,omitempty"`

	// LLMRetryPolicy controls retries for retryable Unified LLM errors (429, 5xx, etc).
	// Nil means use llm.DefaultRetryPolicy().
	//
	// LLMRetryPolicy and LLMSleep are not set by app callers in production; they
	// exist as test-injection points (including from the external agent_test
	// package, which constructs SessionConfig literals through NewSession and so
	// cannot reach an unexported field). They are json:"-" and carry no
	// serialization cost, so they stay on the public struct.
	LLMRetryPolicy *llm.RetryPolicy `json:"-"`
	// LLMSleep is the sleep function used between LLM retries; nil uses the
	// default time.Sleep. A test-injection point (see LLMRetryPolicy above).
	LLMSleep llm.SleepFunc `json:"-"`

	// ModelFallbacks is a literal-order chain of "provider/model" identifiers
	// to try when the primary model returns a Permanent-class provider error
	// (403/404/422/etc — see llm.Classify). Empty means no fallback. Kata cxw8.
	ModelFallbacks []string `json:"model_fallbacks,omitempty"`

	// StateDir, when non-empty, enables incremental session persistence.
	// Snapshots are written to <StateDir>/sessions/ and tasks to <StateDir>/tasks/.
	StateDir string `json:"-"`

	// ExportATIFPath, when non-empty, causes Session.Close to export an ATIF v1.6
	// trajectory JSON file to this path. Only root sessions (spawn.depth==0) export.
	ExportATIFPath string `json:"-"`

	// SystemPromptAsUser, when true, combines the system prompt into the first
	// user message instead of sending it as a separate system/developer message.
	// Workaround for models (e.g. GPT-5.4) that ignore the instructions
	// parameter when given specific task delegations in user messages.
	SystemPromptAsUser bool `json:"system_prompt_as_user,omitempty"`

	// ResolveProfile, when non-nil, maps a "provider/model" ref to the
	// corresponding *provider.Profile. Injected by cmd/serf so that
	// Session.SetModel can perform cross-provider switches without
	// importing the provider constructors directly (which would create a
	// cycle). When nil the session falls back to profile.WithModel which
	// only handles same-provider (or strip/keep) refs.
	ResolveProfile func(ref string) (*provider.Profile, error) `json:"-"`

	// spawn holds the fields that only spawnAgent (plus the init-time
	// role-prompt derivation) populates when creating a child session. It is
	// never set by package consumers and never persisted (json:"-"), matching
	// the pre-refactor json:"-" behavior of each individual field.
	spawn spawnConfig `json:"-"`

	// testOnly holds injection points used only by package-internal tests. It is
	// never set by app callers and never persisted (json:"-").
	testOnly testConfig `json:"-"`
}

// testConfig holds injection points used ONLY by package-internal (package
// agent) tests to make context-strategy selection and compaction thresholds
// deterministic. Never set by app callers; never persisted (json:"-" on the
// parent field).
type testConfig struct {
	// contextStrategyOverride, when non-nil, is used instead of creating a
	// strategy from the ContextStrategy string.
	contextStrategyOverride contextmgr.Strategy

	// compactionThresholdScale multiplies all compaction thresholds by this
	// factor. 1.0 = defaults, 0.1 = trigger at 10% of normal pressure. 0 means
	// use defaults.
	compactionThresholdScale float64
}

// spawnConfig holds the SessionConfig fields that only spawnAgent (plus the
// init-time role-prompt derivation in applyAgentRolePromptOverride) populates
// when creating a child session. They are never set by package consumers and
// never persisted: the parent field is json:"-", so the whole struct drops on
// marshal and is the zero spawnConfig on unmarshal. Restored sessions
// reconstruct parent linkage from the transcript header, NOT from this struct;
// do NOT add json tags or repopulate these on restore, or restored subagents
// would gain a non-zero depth and break ATIF root-export gating and the
// subagent-management-is-top-level guards.
type spawnConfig struct {
	// parentSessionID links sub-agent sessions to their parent (set by spawnAgent).
	parentSessionID string

	// parentToolCallID is the tool call ID that spawned this sub-agent session.
	parentToolCallID string

	// parentJobID is the delegate job ID that spawned this sub-agent session.
	parentJobID string

	// forwardJobEvent lets child job managers send nested job events to the
	// parent manager. The forwarding behavior is installed by later phases.
	forwardJobEvent func(jobstore.Event) error

	// parentSteer routes runtime alias messages from a live sub-agent to its caller.
	parentSteer func(string)

	// parentSteerDelivered reports whether a runtime alias message was accepted
	// by the caller. It is used where durable watch-send state depends on delivery.
	parentSteerDelivered func(string) bool

	// parentGrantedJobRead resolves watch-granted cross-session reads against
	// the parent's job store (spec §5.1 read grants): given the child's
	// (observer) session id and a job id the child cannot resolve locally, the
	// parent returns a read-only view when a durable watch_read_grant covers
	// the pair. The lookup is jobstore-level only — the child never touches
	// parent Session state through it.
	parentGrantedJobRead func(observerSessionID, jobID string) (*grantedJobRead, bool)

	// subagentTask is the task description passed to delegate.
	subagentTask string

	// depth is the sub-agent nesting depth (0 for root sessions).
	depth int

	// delegationAllowance is the number of additional sub-agent delegation
	// levels this session is permitted to grant. The delegate restore
	// descriptor (DelegateRestoreDescriptor.DelegationAllowance) carries it
	// across a delegate resume; never populated by json unmarshal (json:"-"
	// on the parent struct, like its siblings).
	delegationAllowance int

	// treeCounter is the tree-wide running delegate-turn counter. Created once
	// by the root session (when parentSessionID == "") and inherited by all
	// child sessions via spawnConfig. reserve/release are wired into the
	// spawn/resume/drive paths (reserveTreeSlot) and the finalize/abandon paths.
	treeCounter *treeCounter

	// sharedTaskStore, when non-nil, is used instead of creating a per-session
	// task store. Set by spawnAgent when ShareTasksWithChildren is true.
	sharedTaskStore *task.TaskStore

	// rolePromptOverride and the three fields below carry internal prompt and
	// session shaping for restricted subagents and reviewer runs.
	rolePromptOverride      string
	activatedSkillBodies    []string
	allowedToolNames        []string
	deniedToolNames         []string
	communicateOutputSchema map[string]any
}

func (c *SessionConfig) applyDefaults() {
	if c.MaxToolRoundsPerInput == 0 {
		c.MaxToolRoundsPerInput = 200
	}
	if c.DefaultCommandTimeoutMS <= 0 {
		c.DefaultCommandTimeoutMS = 10_000
	}
	if c.MaxCommandTimeoutMS <= 0 {
		c.MaxCommandTimeoutMS = 600_000
	}
	if c.MaxSubagentDepth <= 0 {
		c.MaxSubagentDepth = 1
	}
	if c.EnableLoopDetection == nil {
		v := true
		c.EnableLoopDetection = &v
	}
	if c.LoopDetectionWindow <= 0 {
		c.LoopDetectionWindow = 10
	}
}

// toSnapshot projects the persisted wire fields of a SessionConfig into a
// schema.ConfigSnapshot, dropping the engine-only json:"-" fields that are never
// serialized. The field set mirrors schema.ConfigSnapshot exactly; the converter
// round-trip test guards against any field being dropped or misrouted.
func (c SessionConfig) toSnapshot() schema.ConfigSnapshot {
	return schema.ConfigSnapshot{
		MaxToolRoundsPerInput:   c.MaxToolRoundsPerInput,
		MaxTurns:                c.MaxTurns,
		DefaultCommandTimeoutMS: c.DefaultCommandTimeoutMS,
		MaxCommandTimeoutMS:     c.MaxCommandTimeoutMS,
		MaxSubagentDepth:        c.MaxSubagentDepth,
		ToolOutputLimits:        c.ToolOutputLimits,
		UserInstructionOverride: c.UserInstructionOverride,
		AgentName:               c.AgentName,
		ReasoningEffort:         c.ReasoningEffort,
		SkillsDirs:              c.SkillsDirs,
		MCPConfigFiles:          c.MCPConfigFiles,
		MCPInline:               c.MCPInline,
		PluginDirs:              c.PluginDirs,
		SystemPromptFile:        c.SystemPromptFile,
		SystemPromptAppend:      c.SystemPromptAppend,
		NoProjectPrompts:        c.NoProjectPrompts,
		NonInteractive:          c.NonInteractive,
		ContextStrategy:         c.ContextStrategy,
		ShareTasksWithChildren:  c.ShareTasksWithChildren,
		ResultToolName:          c.ResultToolName,
		EnableLoopDetection:     c.EnableLoopDetection,
		LoopDetectionWindow:     c.LoopDetectionWindow,
		ModelFallbacks:          c.ModelFallbacks,
		SystemPromptAsUser:      c.SystemPromptAsUser,
	}
}

// configFromSnapshot rebuilds a SessionConfig from its persisted wire fields.
// Engine-only fields (StateDir, ResolveProfile, retry policy, spawn linkage,
// test hooks) are not persisted and are left zero for the caller to repopulate —
// matching the pre-carve behavior, where those json:"-" fields were always zero
// after loading a meta.json or snapshot from disk.
func configFromSnapshot(s schema.ConfigSnapshot) SessionConfig {
	return SessionConfig{
		MaxToolRoundsPerInput:   s.MaxToolRoundsPerInput,
		MaxTurns:                s.MaxTurns,
		DefaultCommandTimeoutMS: s.DefaultCommandTimeoutMS,
		MaxCommandTimeoutMS:     s.MaxCommandTimeoutMS,
		MaxSubagentDepth:        s.MaxSubagentDepth,
		ToolOutputLimits:        s.ToolOutputLimits,
		UserInstructionOverride: s.UserInstructionOverride,
		AgentName:               s.AgentName,
		ReasoningEffort:         s.ReasoningEffort,
		SkillsDirs:              s.SkillsDirs,
		MCPConfigFiles:          s.MCPConfigFiles,
		MCPInline:               s.MCPInline,
		PluginDirs:              s.PluginDirs,
		SystemPromptFile:        s.SystemPromptFile,
		SystemPromptAppend:      s.SystemPromptAppend,
		NoProjectPrompts:        s.NoProjectPrompts,
		NonInteractive:          s.NonInteractive,
		ContextStrategy:         s.ContextStrategy,
		ShareTasksWithChildren:  s.ShareTasksWithChildren,
		ResultToolName:          s.ResultToolName,
		EnableLoopDetection:     s.EnableLoopDetection,
		LoopDetectionWindow:     s.LoopDetectionWindow,
		ModelFallbacks:          s.ModelFallbacks,
		SystemPromptAsUser:      s.SystemPromptAsUser,
	}
}
