package agent

import (
	"context"
	"errors"
	"fmt"
	"path/filepath"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"

	"primeradiant.com/evener/agent/events"
	"primeradiant.com/evener/agent/internal/sessionlog"
	"primeradiant.com/evener/agent/provider"
	"primeradiant.com/evener/agent/schema"
	"primeradiant.com/evener/llm"
)

const (
	sessionNameSourcePrompt     = "prompt"
	sessionNameSourceCompaction = "compaction"
	sessionNameSourceUser       = "user"
	sessionNameMaxRunes         = 60
	sessionNameTimeout          = 15 * time.Second
)

// sessionNameResult is the advisory output of the session namer.
type sessionNameResult struct {
	// Name is the sanitized session title generated by the model.
	Name string
	// Source is the normalized origin of the name ("prompt" or "compaction").
	Source string
	// Usage is the token usage reported for the naming LLM call.
	Usage llm.Usage
}

// nameSession generates a short human-readable title with one LLM call, routed
// to the configured cheap model when present or the active model otherwise.
// sleep is the backoff function used between the GenerateObject retries;
// production passes s.cfg.LLMSleep (nil, so GenerateObject uses the real
// DefaultSleep), while tests inject a no-op so a retryable provider error
// doesn't burn the full 1+2+4+8s backoff as real wall time.
func nameSession(ctx context.Context, client *llm.Client, profile *provider.Profile, source, text string, sleep llm.SleepFunc) (sessionNameResult, error) {
	if client == nil {
		return sessionNameResult{}, errors.New("session namer: llm client is nil")
	}
	if profile == nil {
		return sessionNameResult{}, errors.New("session namer: profile is nil")
	}
	source = normalizeSessionNameSource(source)
	text = strings.TrimSpace(text)
	if text == "" {
		return sessionNameResult{}, errors.New("session namer: source text is empty")
	}
	callCtx, cancel := context.WithTimeout(ctx, sessionNameTimeout)
	defer cancel()

	model := sessionNamerModel(profile)
	if model == "" {
		return sessionNameResult{}, errors.New("session namer: model is empty")
	}
	maxTokens := 80
	temp := 0.0
	// Naming is best-effort decoration with its own short deadline. It opts out
	// of the turn retry wall budget so a naming storm does not add load while a
	// real turn waits on the same provider bucket.
	namerPolicy := llm.DefaultRetryPolicy()
	namerPolicy.RateLimitWallBudget = 0
	res, err := llm.GenerateObject(callCtx, llm.GenerateObjectOptions{
		Client:      client,
		Provider:    profile.CheapProvider(),
		Model:       model,
		System:      new(sessionNamerSystemPrompt),
		Prompt:      new(sessionNamerUserPrompt(source, text)),
		Temperature: &temp,
		MaxTokens:   &maxTokens,
		Sleep:       sleep,
		RetryPolicy: &namerPolicy,
		Schema:      sessionNameSchema(),
	})
	if err != nil {
		return sessionNameResult{}, fmt.Errorf("session namer: %w", err)
	}

	obj, _ := res.Output.(map[string]any)
	name, _ := obj["name"].(string)
	name = sanitizeSessionName(name)
	if name == "" {
		return sessionNameResult{}, errors.New("session namer: generated name is empty")
	}
	return sessionNameResult{Name: name, Source: source, Usage: res.TotalUsage}, nil
}

func sessionNamerEnabled(profile *provider.Profile) bool {
	if profile == nil {
		return false
	}
	return sessionNamerModel(profile) != ""
}

// sessionNamerUsable reports whether a naming call is worth making at all: the
// profile must resolve a naming model, and the session must not already have
// learned that the current model choice's allowance is spent.
//
// Every launch path asks this one question, which is why the question has one
// name. sessionNamerEnabled answers only the model-resolution half and cannot
// see session state; a quota exhaustion is the same category of fact ("the
// namer cannot run") but is learned at runtime rather than read from config.
func (s *Session) sessionNamerUsable() bool {
	if !sessionNamerEnabled(s.currentProfile()) {
		return false
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	return !s.naming.quotaExhausted
}

func sessionNamerModel(profile *provider.Profile) string {
	if profile == nil {
		return ""
	}
	if model := configuredSessionNamerModel(profile); model != "" {
		return model
	}
	return strings.TrimSpace(profile.Model())
}

func configuredSessionNamerModel(profile *provider.Profile) string {
	if profile == nil {
		return ""
	}
	return profile.ConfiguredCheapModel()
}

const sessionNamerSystemPrompt = `You generate concise session titles for a developer assistant.
The title is a durable label a human uses to find this session in a list, so it
must name the session's overarching goal: the problem the user wants solved
across the whole session.
Return only JSON matching the requested schema.
Rules:
- 2 to 6 words.
- Maximum 60 characters.
- Use Title Case.
- No ending punctuation.
- No quotes or markdown.
- Name the overall goal, not what was happening at one moment. Do not title the
  session after the current activity, the file being edited, or the test being
  debugged.`

func sessionNamerUserPrompt(source, text string) string {
	var label string
	switch normalizeSessionNameSource(source) {
	case sessionNameSourceCompaction:
		label = "Use this compaction summary to refresh the session title. The title must still name the session's overarching goal, not the momentary activity: the summary's Current State and Pending Work sections describe what was happening at one instant, so do not title the session after them. Look for the goal in the user's original request and the conversation timeline."
	default:
		label = "Use this initial user prompt to name the session"
	}
	return label + ":\n\n" + trimForSessionNamer(text)
}

func sessionNameSchema() map[string]any {
	return map[string]any{
		"type":                 "object",
		"additionalProperties": false,
		"properties": map[string]any{
			"name": map[string]any{
				"type":        "string",
				"description": "A short human-readable session title.",
				"minLength":   1,
				"maxLength":   sessionNameMaxRunes,
			},
		},
		"required": []string{"name"},
	}
}

func normalizeSessionNameSource(source string) string {
	switch strings.TrimSpace(source) {
	case sessionNameSourceCompaction:
		return sessionNameSourceCompaction
	default:
		return sessionNameSourcePrompt
	}
}

func trimForSessionNamer(text string) string {
	text = strings.TrimSpace(text)
	const maxRunes = 4000
	if utf8.RuneCountInString(text) <= maxRunes {
		return text
	}
	runes := []rune(text)
	return string(runes[:maxRunes]) + "\n...[truncated]"
}

func sanitizeSessionName(name string) string {
	const boundaryQuotes = "\"'`“”‘’"
	trimTrailingBoundary := func(r rune) bool {
		return unicode.IsPunct(r) || unicode.IsSpace(r) || strings.ContainsRune(boundaryQuotes, r)
	}
	trimLeadingBoundary := func(r rune) bool {
		return unicode.IsSpace(r) || strings.ContainsRune(boundaryQuotes, r)
	}

	name = strings.TrimSpace(name)
	name = strings.Trim(name, boundaryQuotes)
	name = strings.Join(strings.Fields(name), " ")
	name = strings.TrimLeftFunc(name, trimLeadingBoundary)
	name = strings.TrimRightFunc(name, trimTrailingBoundary)
	if utf8.RuneCountInString(name) > sessionNameMaxRunes {
		runes := []rune(name)
		name = strings.TrimSpace(string(runes[:sessionNameMaxRunes]))
		name = strings.TrimRightFunc(name, trimTrailingBoundary)
	}
	return name
}

//go:fix inline
func (s *Session) launchInitialPromptNamer(ctx context.Context, input string) {
	if s.stateDir == "" && !s.cfg.testOnly.forceSessionNamer {
		return
	}
	if !s.sessionNamerUsable() {
		return
	}
	if strings.TrimSpace(input) == "" {
		return
	}
	s.mu.Lock()
	if s.naming.set || s.naming.promptPending || strings.TrimSpace(s.naming.value) != "" || s.closingOrClosedLocked() {
		s.mu.Unlock()
		return
	}
	s.naming.promptPending = true
	s.sendersWG.Add(1)
	s.mu.Unlock()
	go func() {
		defer s.sendersWG.Done()
		err := s.nameSessionFromText(ctx, sessionNameSourcePrompt, input)
		s.clearPromptNamePendingAfterAttempt(err)
	}()
}

// suppressSessionNamerIfQuotaExhausted disables naming for the rest of this
// session when err says the resolved naming model's allowance is spent, and
// reports whether it did.
//
// Only a quota exhaustion earns this. An ordinary rate limit shares its HTTP
// status but clears in seconds, so retrying it on a later turn is exactly
// right; a spent allowance can be days from returning, and re-dispatching it
// every turn buys nothing but a wasted round trip and a duplicate advisory.
//
// The error arrives wrapped (nameSession adds "session namer: %w"), so this
// reads it with llm.Kind, which walks the chain, rather than llm.DeclaredKind.
// That is safe here and not in the API-log capture path: this error came from
// this process's own llm client, not from an adapter of unverified provenance.
func (s *Session) suppressSessionNamerIfQuotaExhausted(err error) bool {
	if llm.Kind(err) != llm.KindQuotaExceeded {
		return false
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.naming.quotaExhausted {
		return false
	}
	s.naming.quotaExhausted = true
	return true
}

// forgetSessionNamerQuotaExhaustionLocked lets the namer try again after the
// session's model changes. Caller must hold s.mu.
//
// The suppression latch records a fact about an allowance, not about the
// session: the exhausted allowance belongs to the account behind whichever
// provider the namer was calling. Switching providers is the very remedy the
// quota error pushes a user toward, so a latch that outlived the switch would
// leave naming dead on a provider with a perfectly good allowance.
//
// Any switch clears it, not just a cross-provider one. A same-provider switch
// usually shares the spent allowance, so clearing costs one round trip to
// relearn the fact -- cheaper than the alternative error of staying silent for
// a session that could have named itself, and it keeps the rule one sentence
// long instead of a per-provider special case.
func (s *Session) forgetSessionNamerQuotaExhaustionLocked() {
	s.naming.quotaExhausted = false
}

func (s *Session) clearPromptNamePendingAfterAttempt(err error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if err != nil || strings.TrimSpace(s.naming.value) == "" {
		s.naming.promptPending = false
	}
}

func (s *Session) launchCompactionNamer(ctx context.Context, turn schema.Turn) {
	if s.stateDir == "" {
		return
	}
	if !s.sessionNamerUsable() {
		return
	}
	if !isSessionNameCompactionTurn(turn) || strings.TrimSpace(turn.Message.Text()) == "" {
		return
	}
	if !s.shouldNameFromCompaction() {
		return
	}
	s.mu.Lock()
	if s.closingOrClosedLocked() {
		s.mu.Unlock()
		return
	}
	s.sendersWG.Add(1)
	s.mu.Unlock()
	go func() {
		defer s.sendersWG.Done()
		_ = s.nameSessionFromCompactionTurn(ctx, turn)
	}()
}

func (s *Session) nameSessionFromCompactionTurn(ctx context.Context, turn schema.Turn) error {
	if !isSessionNameCompactionTurn(turn) {
		return nil
	}
	text := strings.TrimSpace(turn.Message.Text())
	if text == "" {
		return nil
	}
	if !s.shouldNameFromCompaction() {
		return nil
	}
	return s.nameSessionFromText(ctx, sessionNameSourceCompaction, text)
}

func isSessionNameCompactionTurn(turn schema.Turn) bool {
	return turn.Kind == schema.TurnSummary || turn.Kind == schema.TurnCheckpoint
}

func (s *Session) handleCompactionTurn(t schema.Turn) {
	s.reportCompactionTranscriptAppend(s.writeTranscript(t))
	if isSessionNameCompactionTurn(t) {
		// A CHECKPOINT/SUMMARY turn replaces history: any ENVIRONMENT turns
		// folded away with it are gone from what the model sees, so the
		// environment-context tracker must forget what it last reported (see
		// resetEnvContextTrackerAfterCompaction's doc comment). This is the
		// single choke point every compaction completion path (Compact,
		// applyPendingForceCompact, and the automatic per-request
		// ManageContext) funnels through via contextMgr.OnCompactionTurn /
		// WithCompactionTurnCallback.
		s.resetEnvContextTrackerAfterCompaction()
		s.emit(events.EventCompactionTurn, events.CompactionTurnData{Kind: string(t.Kind), Text: t.Message.Text()})
	}
	s.launchCompactionNamer(s.sessionCtx, t)
	// After compaction, inject full task list if tasks exist.
	if s.taskStore != nil {
		if reminder := taskReminderFull(s.taskStore); reminder != "" {
			s.SteerKind(reminder, events.SteeringKindTaskList)
		}
	}
}

func (s *Session) reportCompactionTranscriptAppend(err error) {
	if err != nil {
		s.emit(events.EventWarning, events.WarningData{Message: fmt.Sprintf("transcript compaction write: %v", err)})
	}
}

func (s *Session) shouldNameFromCompaction() bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	if strings.TrimSpace(s.naming.value) == "" {
		return true
	}
	source := strings.TrimSpace(s.naming.source)
	return source == sessionNameSourcePrompt || source == sessionNameSourceCompaction
}

func (s *Session) nameSessionFromText(ctx context.Context, source, text string) error {
	source = normalizeSessionNameSource(source)
	if !s.shouldApplySessionName(source) {
		return nil
	}
	ctx = s.apiLogContext(ctx)
	if s.nameSessionFromTextFunc != nil {
		return s.nameSessionFromTextFunc(ctx, source, text)
	}

	namerClient := s.client
	if s.cfg.testOnly.namerClient != nil {
		namerClient = s.cfg.testOnly.namerClient
	}
	result, err := nameSession(ctx, namerClient, s.currentProfile(), source, text, s.cfg.LLMSleep)
	if err != nil {
		// Record the suppression before writing the advisory: the advisory is
		// the only externally observable marker that this attempt finished, so
		// anything that waits on it must find the decision already made.
		suppressed := s.suppressSessionNamerIfQuotaExhausted(err)
		summary := fmt.Sprintf("Failed to generate %s-derived session name", sessionNameSourceLabel(source))
		if suppressed {
			summary += "; session naming disabled for this session (provider allowance spent)"
		}
		s.appendSessionNamerLog(sessionlog.SessionLogEntry{
			Kind:     "advisory",
			Action:   "session_namer",
			Summary:  summary,
			Outcome:  "failure",
			Failures: []string{err.Error()},
		})
		return err
	}
	return s.applySessionNameResult(result)
}

func (s *Session) applySessionNameResult(result sessionNameResult) error {
	s.mu.Lock()
	if s.closingOrClosedLocked() {
		s.mu.Unlock()
		return context.Canceled
	}
	if !s.shouldApplySessionNameLocked(result.Source) {
		s.mu.Unlock()
		return nil
	}
	s.naming.value = result.Name
	s.naming.source = result.Source
	s.naming.updated = s.sclock().Now().UTC()
	s.naming.set = true
	s.mu.Unlock()
	s.emit(events.EventSessionNameChanged, events.SessionNameChangedData{Name: result.Name, Source: result.Source})

	s.appendSessionNamerLog(sessionlog.SessionLogEntry{
		Kind:    "advisory",
		Action:  "session_namer",
		Summary: fmt.Sprintf("Suggested %s-derived session name: %s", sessionNameSourceLabel(result.Source), result.Name),
		Outcome: "success",
	})
	s.maybeAutoSave()
	return nil
}

func (s *Session) shouldApplySessionName(source string) bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.shouldApplySessionNameLocked(source)
}

func (s *Session) shouldApplySessionNameLocked(source string) bool {
	source = normalizeSessionNameSource(source)
	if strings.TrimSpace(s.naming.value) == "" {
		return true
	}
	currentSource := strings.TrimSpace(s.naming.source)
	return source == sessionNameSourceCompaction &&
		(currentSource == sessionNameSourcePrompt || currentSource == sessionNameSourceCompaction)
}

func (s *Session) appendSessionNamerLog(entry sessionlog.SessionLogEntry) {
	if s.stateDir == "" {
		return
	}
	entry.Kind = "advisory"
	entry.Action = "session_namer"
	logPath := filepath.Join(s.stateDir, sessionsSubdir, s.id+".log.jsonl")
	log, err := sessionlog.NewSessionLog(logPath)
	if err != nil {
		s.emit(events.EventWarning, events.WarningData{Message: fmt.Sprintf("session namer log open failed: %v", err)})
		return
	}
	s.reportSessionNamerLogAppend(log.Append(entry))
}

func (s *Session) reportSessionNamerLogAppend(err error) {
	if err != nil {
		s.emit(events.EventWarning, events.WarningData{Message: fmt.Sprintf("session namer log append failed: %v", err)})
	}
}

func sessionNameSourceLabel(source string) string {
	switch normalizeSessionNameSource(source) {
	case sessionNameSourceCompaction:
		return "compaction"
	default:
		return "prompt"
	}
}
