package openai

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strconv"
	"strings"
	"time"
)

const (
	defaultPollMaxWait     = 15 * time.Minute
	defaultDeviceInterval  = 5 * time.Second
	deviceAPIPath          = "/api/accounts/deviceauth"
	deviceVerificationPath = "/codex/device"
	deviceRedirectPath     = "/deviceauth/callback"
)

// ErrDeviceCodeNotEnabled means the OpenAI client does not support the
// device-code flow (the usercode endpoint returned 404). Callers can branch
// on this to fall back to the browser/redirect flow.
var ErrDeviceCodeNotEnabled = errors.New("device-code login is not enabled for this OpenAI client")

// DeviceCode is the public handle returned by RequestDeviceCode. It carries
// what the CLI needs to display to the user as well as the opaque values that
// PollDeviceAuth needs to drive the polling loop.
type DeviceCode struct {
	VerificationURL string
	UserCode        string
	DeviceAuthID    string
	Interval        time.Duration
}

// DeviceCodeSuccess is the server-issued bundle returned from a successful
// poll. The CodeVerifier is generated by the server (not by the client) for
// the device-code flow — the eventual /oauth/token exchange must use this
// value, not a locally generated PKCE verifier.
type DeviceCodeSuccess struct {
	AuthorizationCode string
	CodeChallenge     string
	CodeVerifier      string
}

type deviceUserCodeRequest struct {
	ClientID string `json:"client_id"`
}

type deviceUserCodeResponse struct {
	DeviceAuthID string         `json:"device_auth_id"`
	UserCode     string         `json:"user_code"`
	Interval     flexibleNumber `json:"interval"`
}

type devicePollRequest struct {
	DeviceAuthID string `json:"device_auth_id"`
	UserCode     string `json:"user_code"`
}

type devicePollResponse struct {
	AuthorizationCode string `json:"authorization_code"`
	CodeChallenge     string `json:"code_challenge"`
	CodeVerifier      string `json:"code_verifier"`
}

// flexibleNumber decodes a JSON value that may arrive as either a string or a
// number. Codex serializes `interval` as a string (`"5"`); a defensive Go
// decoder accepts both forms so an upstream change to a numeric encoding
// would not break us.
type flexibleNumber uint64

func (n *flexibleNumber) UnmarshalJSON(data []byte) error {
	if len(data) == 0 || bytes.Equal(data, []byte("null")) {
		*n = 0
		return nil
	}
	trimmed := bytes.TrimSpace(data)
	if len(trimmed) >= 2 && trimmed[0] == '"' && trimmed[len(trimmed)-1] == '"' {
		raw := strings.TrimSpace(string(trimmed[1 : len(trimmed)-1]))
		if raw == "" {
			*n = 0
			return nil
		}
		v, err := strconv.ParseUint(raw, 10, 64)
		if err != nil {
			return fmt.Errorf("device interval: %w", err)
		}
		*n = flexibleNumber(v)
		return nil
	}
	v, err := strconv.ParseUint(string(trimmed), 10, 64)
	if err != nil {
		return fmt.Errorf("device interval: %w", err)
	}
	*n = flexibleNumber(v)
	return nil
}

// RequestDeviceCode kicks off the device-code flow by asking the issuer for a
// short user code and an associated device_auth_id. The returned DeviceCode
// should be shown to the user, then handed to PollDeviceAuth.
func RequestDeviceCode(ctx context.Context, client *http.Client, cfg Config) (DeviceCode, error) {
	cfg = mergeConfigDefaults(cfg)
	if client == nil {
		client = &http.Client{Timeout: cfg.HTTPTimeout}
	}

	body, err := json.Marshal(deviceUserCodeRequest{ClientID: cfg.clientID()})
	if err != nil {
		return DeviceCode{}, fmt.Errorf("marshal device usercode request: %w", err)
	}

	base := strings.TrimRight(cfg.issuerBaseURL(), "/")
	endpoint := base + deviceAPIPath + "/usercode"
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint, bytes.NewReader(body))
	if err != nil {
		return DeviceCode{}, err
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := client.Do(req)
	if err != nil {
		return DeviceCode{}, err
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode == http.StatusNotFound {
		return DeviceCode{}, fmt.Errorf("%w; use the browser flow (`serf openai login`) instead", ErrDeviceCodeNotEnabled)
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return DeviceCode{}, fmt.Errorf("device code request failed with status %d", resp.StatusCode)
	}

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return DeviceCode{}, fmt.Errorf("read device usercode response: %w", err)
	}

	var payload deviceUserCodeResponse
	if err := json.Unmarshal(respBody, &payload); err != nil {
		return DeviceCode{}, fmt.Errorf("decode device usercode response: %w", err)
	}
	if strings.TrimSpace(payload.DeviceAuthID) == "" || strings.TrimSpace(payload.UserCode) == "" {
		return DeviceCode{}, errors.New("device usercode response missing device_auth_id or user_code")
	}

	interval := time.Duration(payload.Interval) * time.Second
	if interval <= 0 {
		interval = defaultDeviceInterval
	}

	return DeviceCode{
		VerificationURL: base + deviceVerificationPath,
		UserCode:        payload.UserCode,
		DeviceAuthID:    payload.DeviceAuthID,
		Interval:        interval,
	}, nil
}

// PollDeviceAuthOnce makes a single poll attempt against the device token
// endpoint. pending is true when the server reports the user has not finished
// authorizing yet (HTTP 403/404). A non-2xx status that is not pending is
// returned as err.
func PollDeviceAuthOnce(ctx context.Context, client *http.Client, cfg Config, dc DeviceCode) (DeviceCodeSuccess, bool, error) {
	cfg = mergeConfigDefaults(cfg)
	if client == nil {
		client = &http.Client{Timeout: cfg.HTTPTimeout}
	}
	body, err := json.Marshal(devicePollRequest{DeviceAuthID: dc.DeviceAuthID, UserCode: dc.UserCode})
	if err != nil {
		return DeviceCodeSuccess{}, false, fmt.Errorf("marshal device poll request: %w", err)
	}
	endpoint := strings.TrimRight(cfg.issuerBaseURL(), "/") + deviceAPIPath + "/token"
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint, bytes.NewReader(body))
	if err != nil {
		return DeviceCodeSuccess{}, false, err
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := client.Do(req)
	if err != nil {
		return DeviceCodeSuccess{}, false, err
	}
	defer func() { _ = resp.Body.Close() }()
	status := resp.StatusCode
	if status >= 200 && status < 300 {
		var payload devicePollResponse
		if err := json.NewDecoder(resp.Body).Decode(&payload); err != nil {
			return DeviceCodeSuccess{}, false, fmt.Errorf("decode device poll response: %w", err)
		}
		if payload.AuthorizationCode == "" || payload.CodeVerifier == "" {
			return DeviceCodeSuccess{}, false, errors.New("device poll response missing authorization_code or code_verifier")
		}
		return DeviceCodeSuccess(payload), false, nil
	}
	if status == http.StatusForbidden || status == http.StatusNotFound {
		return DeviceCodeSuccess{}, true, nil
	}
	return DeviceCodeSuccess{}, false, fmt.Errorf("device auth failed with status %d", status)
}

// PollDeviceAuth blocks until the server reports authorization, the overall
// 15-minute window expires, or the context is cancelled. Pending responses
// (403/404) trigger a sleep of dc.Interval and a retry; all other non-2xx
// responses are surfaced as errors.
func PollDeviceAuth(ctx context.Context, client *http.Client, cfg Config, dc DeviceCode) (DeviceCodeSuccess, error) {
	return pollDeviceAuth(ctx, client, cfg, dc, pollOptions{})
}

// pollOptions threads test-only overrides through the internal polling helper
// without bloating the public surface. Zero values mean "use defaults" so the
// public PollDeviceAuth call site stays a one-liner.
type pollOptions struct {
	maxWait time.Duration
	sleep   func(context.Context, time.Duration) error
	now     func() time.Time
}

func pollDeviceAuth(ctx context.Context, client *http.Client, cfg Config, dc DeviceCode, opts pollOptions) (DeviceCodeSuccess, error) {
	cfg = mergeConfigDefaults(cfg)
	if client == nil {
		client = &http.Client{Timeout: cfg.HTTPTimeout}
	}

	maxWait := opts.maxWait
	if maxWait <= 0 {
		maxWait = defaultPollMaxWait
	}
	now := opts.now
	if now == nil {
		now = time.Now
	}
	sleep := opts.sleep
	if sleep == nil {
		sleep = ctxSleep
	}

	interval := dc.Interval
	if interval <= 0 {
		interval = defaultDeviceInterval
	}

	start := now()

	for {
		if err := ctx.Err(); err != nil {
			return DeviceCodeSuccess{}, err
		}

		success, pending, err := PollDeviceAuthOnce(ctx, client, cfg, dc)
		if err != nil {
			return DeviceCodeSuccess{}, err
		}
		if !pending {
			return success, nil
		}

		elapsed := now().Sub(start)
		if elapsed >= maxWait {
			return DeviceCodeSuccess{}, errors.New("device auth timed out after 15 minutes")
		}
		wait := interval
		if remaining := maxWait - elapsed; wait > remaining {
			wait = remaining
		}
		if err := sleep(ctx, wait); err != nil {
			return DeviceCodeSuccess{}, err
		}
	}
}

// ExchangeDeviceCode finishes the device flow by exchanging the server-issued
// authorization code (plus the server-issued PKCE verifier) for a token set
// at the standard OAuth2 token endpoint. The redirect URI must match what the
// device-code flow expects ({issuer}/deviceauth/callback).
func ExchangeDeviceCode(ctx context.Context, client *http.Client, cfg Config, authorizationCode, codeVerifier string) (TokenSet, error) {
	cfg = mergeConfigDefaults(cfg)
	redirectURI := strings.TrimRight(cfg.issuerBaseURL(), "/") + deviceRedirectPath
	return ExchangeCode(ctx, client, cfg, TokenExchangeRequest{
		Code:         authorizationCode,
		RedirectURI:  redirectURI,
		CodeVerifier: codeVerifier,
	})
}

// ctxSleep sleeps for d, returning early with ctx.Err() if the context is
// cancelled. A zero or negative d returns immediately (after a context check).
func ctxSleep(ctx context.Context, d time.Duration) error {
	if d <= 0 {
		if err := ctx.Err(); err != nil {
			return err
		}
		return nil
	}
	timer := time.NewTimer(d)
	defer timer.Stop()
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-timer.C:
		return nil
	}
}
