//go:build serffuzz

package openai

import "testing"

// FuzzAuthOpenAISeedReplay keeps the package's deterministic native scenarios
// in the fuzz-only coverage run. Each seed selects one real HTTP, filesystem,
// callback, device, clock, or parser exercise; no provider or external network
// is involved.
func FuzzAuthOpenAISeedReplay(f *testing.F) {
	scenarios := []struct {
		name string
		run  func(*testing.T)
	}{
		{name: "TestAuthFilePathContainsTraversal", run: TestAuthFilePathContainsTraversal},
		{name: "TestAuthFilePathCustomInstance", run: TestAuthFilePathCustomInstance},
		{name: "TestAuthFilePathDefaultInstance", run: TestAuthFilePathDefaultInstance},
		{name: "TestAuthRecordValidateAcceptsEmptyProvider", run: TestAuthRecordValidateAcceptsEmptyProvider},
		{name: "TestAuthRecordValidateAcceptsNonOpenAIProvider", run: TestAuthRecordValidateAcceptsNonOpenAIProvider},
		{name: "TestAuthRecordValidateRejectsMissingFields", run: TestAuthRecordValidateRejectsMissingFields},
		{name: "TestAuthStorageDeleteRemovesRecord", run: TestAuthStorageDeleteRemovesRecord},
		{name: "TestAuthStorageInstanceIsolation", run: TestAuthStorageInstanceIsolation},
		{name: "TestAuthStorageLoadAcceptsAnyProvider", run: TestAuthStorageLoadAcceptsAnyProvider},
		{name: "TestAuthStorageLoadRejectsMissingAccessToken", run: TestAuthStorageLoadRejectsMissingAccessToken},
		{name: "TestAuthStorageLoadRejectsUnsupportedVersion", run: TestAuthStorageLoadRejectsUnsupportedVersion},
		{name: "TestAuthStorageLoadReturnsCorruptionErrorForMalformedJSON", run: TestAuthStorageLoadReturnsCorruptionErrorForMalformedJSON},
		{name: "TestAuthStorageLoadReturnsNotFoundCleanly", run: TestAuthStorageLoadReturnsNotFoundCleanly},
		{name: "TestAuthStorageSaveIsAtomic", run: TestAuthStorageSaveIsAtomic},
		{name: "TestAuthStorageSaveUsesOwnerOnlyPermissions", run: TestAuthStorageSaveUsesOwnerOnlyPermissions},
		{name: "TestAuthStorageSaveWritesExpectedPath", run: TestAuthStorageSaveWritesExpectedPath},
		{name: "TestAuthorizeURLContainsRequiredQueryParams", run: TestAuthorizeURLContainsRequiredQueryParams},
		{name: "TestAuthorizeURLIgnoresBrowserOpenFlag", run: TestAuthorizeURLIgnoresBrowserOpenFlag},
		{name: "TestAuthorizeURLPropagatesStateAndPKCEChallenge", run: TestAuthorizeURLPropagatesStateAndPKCEChallenge},
		{name: "TestAuthorizeURLRejectsMissingRequiredFields", run: TestAuthorizeURLRejectsMissingRequiredFields},
		{name: "TestAuthorizeURLRejectsUnparseableIssuer", run: TestAuthorizeURLRejectsUnparseableIssuer},
		{name: "TestAuthorizeURLUsesLocalhostCallbackRedirect", run: TestAuthorizeURLUsesLocalhostCallbackRedirect},
		{name: "TestCallbackServerCapturesSuccessfulCallback", run: TestCallbackServerCapturesSuccessfulCallback},
		{name: "TestCallbackServerCloseShutsDownListener", run: TestCallbackServerCloseShutsDownListener},
		{name: "TestCallbackServerRejectsStateMismatch", run: TestCallbackServerRejectsStateMismatch},
		{name: "TestCallbackServerWaitAcceptsNilContext", run: TestCallbackServerWaitAcceptsNilContext},
		{name: "TestCallbackServerWaitTimesOut", run: TestCallbackServerWaitTimesOut},
		{name: "TestClaimNestedStringHandlesNonMapParent", run: TestClaimNestedStringHandlesNonMapParent},
		{name: "TestClaimStringUnwrapsIDObject", run: TestClaimStringUnwrapsIDObject},
		{name: "TestConfigAccessorsFallBackToDefaults", run: TestConfigAccessorsFallBackToDefaults},
		{name: "TestConfigDefaults", run: TestConfigDefaults},
		{name: "TestCtxSleepZeroDuration", run: TestCtxSleepZeroDuration},
		{name: "TestDefaultStateDirIsUserScoped", run: TestDefaultStateDirIsUserScoped},
		{name: "TestDefaultStateDirWithStateHomeFallsBackToTempDir", run: TestDefaultStateDirWithStateHomeFallsBackToTempDir},
		{name: "TestDefaultStateDirWithStateHomeFallsBackToUserHome", run: TestDefaultStateDirWithStateHomeFallsBackToUserHome},
		{name: "TestDefaultStateDirWithStateHomeUsesChildEnvStateHome", run: TestDefaultStateDirWithStateHomeUsesChildEnvStateHome},
		{name: "TestDeleteAuthMissingFileReportsNotDeleted", run: TestDeleteAuthMissingFileReportsNotDeleted},
		{name: "TestDeleteAuthSurfacesUnexpectedRemoveError", run: TestDeleteAuthSurfacesUnexpectedRemoveError},
		{name: "TestExchangeCodeCreatesClientWhenNil", run: TestExchangeCodeCreatesClientWhenNil},
		{name: "TestExchangeCodeErrorPayloadWithoutJSON", run: TestExchangeCodeErrorPayloadWithoutJSON},
		{name: "TestExchangeCodeSuccess", run: TestExchangeCodeSuccess},
		{name: "TestExchangeDeviceCodeUsesDeviceRedirectURI", run: TestExchangeDeviceCodeUsesDeviceRedirectURI},
		{name: "TestFlexibleNumberRejectsNonIntegerJSONNumber", run: TestFlexibleNumberRejectsNonIntegerJSONNumber},
		{name: "TestFlexibleNumberUnmarshalJSON", run: TestFlexibleNumberUnmarshalJSON},
		{name: "TestGeneratePKCEProducesVerifierAndChallenge", run: TestGeneratePKCEProducesVerifierAndChallenge},
		{name: "TestGenerateStateProducesRandomBase64URLState", run: TestGenerateStateProducesRandomBase64URLState},
		{name: "TestIsPermanentRefreshError", run: TestIsPermanentRefreshError},
		{name: "TestListenCallbackPortFallsBackToFallbackPort", run: TestListenCallbackPortFallsBackToFallbackPort},
		{name: "TestListenCallbackPortSurfacesNonDefaultBindFailure", run: TestListenCallbackPortSurfacesNonDefaultBindFailure},
		{name: "TestListenerPortRejectsNonTCPAddr", run: TestListenerPortRejectsNonTCPAddr},
		{name: "TestLoadAuthUnexpectedReadError", run: TestLoadAuthUnexpectedReadError},
		{name: "TestLoginAcceptsNilContext", run: TestLoginAcceptsNilContext},
		{name: "TestLoginAuthorizeURLFailurePropagates", run: TestLoginAuthorizeURLFailurePropagates},
		{name: "TestLoginBrowserOpenFailureIsNonFatal", run: TestLoginBrowserOpenFailureIsNonFatal},
		{name: "TestLoginExchangeCodeFailurePropagates", run: TestLoginExchangeCodeFailurePropagates},
		{name: "TestLoginManualPastebackDoesNotWaitForCallbackTimeout", run: TestLoginManualPastebackDoesNotWaitForCallbackTimeout},
		{name: "TestLoginManualRedirectParseFailure", run: TestLoginManualRedirectParseFailure},
		{name: "TestLoginManualRedirectStateMismatch", run: TestLoginManualRedirectStateMismatch},
		{name: "TestLoginSaveFailurePropagates", run: TestLoginSaveFailurePropagates},
		{name: "TestLoginStartCallbackServerFailurePropagates", run: TestLoginStartCallbackServerFailurePropagates},
		{name: "TestLoginSucceedsViaCallbackPath", run: TestLoginSucceedsViaCallbackPath},
		{name: "TestLoginSucceedsViaManualPastebackPath", run: TestLoginSucceedsViaManualPastebackPath},
		{name: "TestLoginWithDeviceAppliesIDTokenClaimsAndNilContext", run: TestLoginWithDeviceAppliesIDTokenClaimsAndNilContext},
		{name: "TestLoginWithDeviceDetectsConcurrentSuccess", run: TestLoginWithDeviceDetectsConcurrentSuccess},
		{name: "TestLoginWithDeviceDetectsConcurrentSuccessWrittenDuringPrompt", run: TestLoginWithDeviceDetectsConcurrentSuccessWrittenDuringPrompt},
		{name: "TestLoginWithDeviceEndToEnd", run: TestLoginWithDeviceEndToEnd},
		{name: "TestLoginWithDeviceExchangeFailure", run: TestLoginWithDeviceExchangeFailure},
		{name: "TestLoginWithDeviceIgnoresPreExistingState", run: TestLoginWithDeviceIgnoresPreExistingState},
		{name: "TestLoginWithDeviceSaveFailure", run: TestLoginWithDeviceSaveFailure},
		{name: "TestLoginWithDeviceUsercodeFailureLeavesNoAuth", run: TestLoginWithDeviceUsercodeFailureLeavesNoAuth},
		{name: "TestLogoutDeletesStoredAuth", run: TestLogoutDeletesStoredAuth},
		{name: "TestNeedsRefreshTreatsZeroExpiryAsStale", run: TestNeedsRefreshTreatsZeroExpiryAsStale},
		{name: "TestNewServiceAppliesDefaultHTTPTimeoutForPartialConfig", run: TestNewServiceAppliesDefaultHTTPTimeoutForPartialConfig},
		{name: "TestNewServiceDefaultReadRedirectBlocksUntilCancel", run: TestNewServiceDefaultReadRedirectBlocksUntilCancel},
		{name: "TestNewServiceDefaultStartCallbackServer", run: TestNewServiceDefaultStartCallbackServer},
		{name: "TestParseRedirectURLExtractsCodeAndState", run: TestParseRedirectURLExtractsCodeAndState},
		{name: "TestParseRedirectURLRejectsInvalidURLShape", run: TestParseRedirectURLRejectsInvalidURLShape},
		{name: "TestParseRedirectURLRejectsMissingCode", run: TestParseRedirectURLRejectsMissingCode},
		{name: "TestParseRedirectURLRejectsMissingSchemeOrHost", run: TestParseRedirectURLRejectsMissingSchemeOrHost},
		{name: "TestParseRedirectURLRejectsUnparseableInput", run: TestParseRedirectURLRejectsUnparseableInput},
		{name: "TestPollDeviceAuthContextCancellationDuringSleep", run: TestPollDeviceAuthContextCancellationDuringSleep},
		{name: "TestPollDeviceAuthDefaultsAndContextCancel", run: TestPollDeviceAuthDefaultsAndContextCancel},
		{name: "TestPollDeviceAuthHappyPathAfterTwoPending", run: TestPollDeviceAuthHappyPathAfterTwoPending},
		{name: "TestPollDeviceAuthOnceCreatesClientWhenNil", run: TestPollDeviceAuthOnceCreatesClientWhenNil},
		{name: "TestPollDeviceAuthOncePendingOnForbidden", run: TestPollDeviceAuthOncePendingOnForbidden},
		{name: "TestPollDeviceAuthOnceRejectsInvalidJSON", run: TestPollDeviceAuthOnceRejectsInvalidJSON},
		{name: "TestPollDeviceAuthOnceRejectsMissingFields", run: TestPollDeviceAuthOnceRejectsMissingFields},
		{name: "TestPollDeviceAuthOnceSuccess", run: TestPollDeviceAuthOnceSuccess},
		{name: "TestPollDeviceAuthOnceSurfacesRequestBuildError", run: TestPollDeviceAuthOnceSurfacesRequestBuildError},
		{name: "TestPollDeviceAuthOnceSurfacesTransportError", run: TestPollDeviceAuthOnceSurfacesTransportError},
		{name: "TestPollDeviceAuthOnceSurfacesUnexpectedStatus", run: TestPollDeviceAuthOnceSurfacesUnexpectedStatus},
		{name: "TestPollDeviceAuthSurfacesUnexpectedStatus", run: TestPollDeviceAuthSurfacesUnexpectedStatus},
		{name: "TestPollDeviceAuthTimesOut", run: TestPollDeviceAuthTimesOut},
		{name: "TestRefreshTokenSuccess", run: TestRefreshTokenSuccess},
		{name: "TestRequestDeviceCodeAcceptsNumericInterval", run: TestRequestDeviceCodeAcceptsNumericInterval},
		{name: "TestRequestDeviceCodeCreatesClientWhenNil", run: TestRequestDeviceCodeCreatesClientWhenNil},
		{name: "TestRequestDeviceCodeDefaultsIntervalWhenMissing", run: TestRequestDeviceCodeDefaultsIntervalWhenMissing},
		{name: "TestRequestDeviceCodeNotEnabledIsSentinel", run: TestRequestDeviceCodeNotEnabledIsSentinel},
		{name: "TestRequestDeviceCodeNotFoundIsClearError", run: TestRequestDeviceCodeNotFoundIsClearError},
		{name: "TestRequestDeviceCodeRejectsInvalidJSON", run: TestRequestDeviceCodeRejectsInvalidJSON},
		{name: "TestRequestDeviceCodeRejectsMissingFields", run: TestRequestDeviceCodeRejectsMissingFields},
		{name: "TestRequestDeviceCodeSuccessParsesInterval", run: TestRequestDeviceCodeSuccessParsesInterval},
		{name: "TestRequestDeviceCodeSurfacesBodyReadError", run: TestRequestDeviceCodeSurfacesBodyReadError},
		{name: "TestRequestDeviceCodeSurfacesRequestBuildError", run: TestRequestDeviceCodeSurfacesRequestBuildError},
		{name: "TestRequestDeviceCodeSurfacesTransportError", run: TestRequestDeviceCodeSurfacesTransportError},
		{name: "TestRequestDeviceCodeSurfacesUnexpectedStatus", run: TestRequestDeviceCodeSurfacesUnexpectedStatus},
		{name: "TestResolveRuntimeCredentialsBlankRefreshTokenRequiresRelogin", run: TestResolveRuntimeCredentialsBlankRefreshTokenRequiresRelogin},
		{name: "TestResolveRuntimeCredentialsSaveFailureAfterRefresh", run: TestResolveRuntimeCredentialsSaveFailureAfterRefresh},
		{name: "TestResolveRuntimeCredentialsSurfacesCorruptRecordError", run: TestResolveRuntimeCredentialsSurfacesCorruptRecordError},
		{name: "TestRuntimeCredentialsFallsBackToEnvWhenNoStoredAuth", run: TestRuntimeCredentialsFallsBackToEnvWhenNoStoredAuth},
		{name: "TestRuntimeCredentialsNoStoredAuthUnwrapsToErrAuthNotFound", run: TestRuntimeCredentialsNoStoredAuthUnwrapsToErrAuthNotFound},
		{name: "TestRuntimeCredentialsRefreshFailureRequiresRelogin", run: TestRuntimeCredentialsRefreshFailureRequiresRelogin},
		{name: "TestRuntimeCredentialsRefreshesNearExpiryToken", run: TestRuntimeCredentialsRefreshesNearExpiryToken},
		{name: "TestRuntimeCredentialsReturnsStoredTokenWhenFresh", run: TestRuntimeCredentialsReturnsStoredTokenWhenFresh},
		{name: "TestRuntimeCredentialsStoredAuthWinsOverEnv", run: TestRuntimeCredentialsStoredAuthWinsOverEnv},
		{name: "TestRuntimeCredentialsTransientRefreshFailureDoesNotRequireRelogin", run: TestRuntimeCredentialsTransientRefreshFailureDoesNotRequireRelogin},
		{name: "TestSaveAuthMkdirFailureSurfaces", run: TestSaveAuthMkdirFailureSurfaces},
		{name: "TestSaveAuthTempFileCreationFailure", run: TestSaveAuthTempFileCreationFailure},
		{name: "TestStartCallbackServerSurfacesListenFailure", run: TestStartCallbackServerSurfacesListenFailure},
		{name: "TestStatusPrefersStoredOAuthOverEnv", run: TestStatusPrefersStoredOAuthOverEnv},
		{name: "TestStatusReflectsStoredOAuthState", run: TestStatusReflectsStoredOAuthState},
		{name: "TestStatusSignedOutWhenNoEnvOrStoredAuth", run: TestStatusSignedOutWhenNoEnvOrStoredAuth},
		{name: "TestStatusSurfacesCorruptRecordError", run: TestStatusSurfacesCorruptRecordError},
		{name: "TestStatusUsesEnvWhenNoStoredAuth", run: TestStatusUsesEnvWhenNoStoredAuth},
		{name: "TestTokenClaimsEmptyIDTokenIsBestEffort", run: TestTokenClaimsEmptyIDTokenIsBestEffort},
		{name: "TestTokenClaimsMalformedIDTokenReturnsSentinel", run: TestTokenClaimsMalformedIDTokenReturnsSentinel},
		{name: "TestTokenClaimsParsesAccountAndWorkspaceMetadata", run: TestTokenClaimsParsesAccountAndWorkspaceMetadata},
		{name: "TestTokenClaimsParsesChatGPTAccountID", run: TestTokenClaimsParsesChatGPTAccountID},
		{name: "TestTokenClaimsParsesEmailFromIDToken", run: TestTokenClaimsParsesEmailFromIDToken},
		{name: "TestTokenEndpointErrorIsCompact", run: TestTokenEndpointErrorIsCompact},
		{name: "TestTokenEndpointInvalidJSONResponse", run: TestTokenEndpointInvalidJSONResponse},
		{name: "TestTokenResponseExpiryTime", run: TestTokenResponseExpiryTime},
		{name: "TestValidateStateAcceptsMatchingState", run: TestValidateStateAcceptsMatchingState},
		{name: "TestValidateStateRejectsEmptyReturnedState", run: TestValidateStateRejectsEmptyReturnedState},
		{name: "TestValidateStateRejectsMismatchedState", run: TestValidateStateRejectsMismatchedState},
		{name: "TestWaitForLoginCompletion", run: TestWaitForLoginCompletion},
		{name: "TestWaitForLoginCompletionBothChannelsExhausted", run: TestWaitForLoginCompletionBothChannelsExhausted},
		{name: "TestWaitForLoginCompletionCallbackFatalError", run: TestWaitForLoginCompletionCallbackFatalError},
		{name: "TestWaitForLoginCompletionCallbackSuccess", run: TestWaitForLoginCompletionCallbackSuccess},
		{name: "TestWaitForLoginCompletionCallbackTransientThenManual", run: TestWaitForLoginCompletionCallbackTransientThenManual},
		{name: "TestWaitForLoginCompletionContextCancelled", run: TestWaitForLoginCompletionContextCancelled},
		{name: "TestWaitForLoginCompletionManualFatalError", run: TestWaitForLoginCompletionManualFatalError},
		{name: "TestWaitForLoginCompletionManualSuccess", run: TestWaitForLoginCompletionManualSuccess},
		{name: "TestWaitForLoginCompletionManualTransientThenCallback", run: TestWaitForLoginCompletionManualTransientThenCallback},
		{name: "TestWatchForConcurrentLoginSkipsNonOAuthRecord", run: TestWatchForConcurrentLoginSkipsNonOAuthRecord},
		{name: "TestWithOptionsChainReturnsReceiver", run: TestWithOptionsChainReturnsReceiver},
		{name: "TestWithOptionsSetCollaboratorsAndIgnoreNil", run: TestWithOptionsSetCollaboratorsAndIgnoreNil},
	}
	for i := range scenarios {
		f.Add(uint16(i))
	}
	f.Fuzz(func(t *testing.T, selector uint16) {
		scenario := scenarios[int(selector)%len(scenarios)]
		t.Run(scenario.name, scenario.run)
	})
}
