import { defineConfig } from "eslint/config";
import tseslint from "typescript-eslint";

export default defineConfig(
  {
    // Generated by internal/appwirets (go generate ./appwire/...); edit the
    // AppWire catalog and regenerate instead of hand-editing or linting it.
    ignores: ["src/protocol/types.gen.ts"],
  },
  {
    files: ["src/**/*.ts", "src/**/*.tsx"],
    extends: [tseslint.configs.recommended],
  },
);
